namespace = 'ConvexAnalysis'

[[node]]
id = 'epi'

[[node]]
id = 'hypo'

[[node]]
id = 'convexDom'

[[node]]
id = 'concaveDom'

[[node]]
id = 'ProperConvex'

[[node]]
id = 'ProperConcave'

[[node]]
id = 'convexRestrict'

[[node]]
id = 'concaveRestrict'

[[node]]
id = 'hypo_neg'

[[node]]
id = 'epi_neg'

[[node]]
id = 'concaveDom_eq_convexDom_neg'

[[node]]
id = 'properConcave_iff_properConvex_neg'

[[node]]
id = 'convexDom_coe_mul'

[[node]]
id = 'properConvex_coe_mul'

[[node]]
id = 'ConvexFn'

[[node]]
id = 'ConcaveFn'

[[node]]
id = 'concaveFn_iff_convexFn_neg'

[[node]]
id = 'convexFn_add_coe'

[[node]]
id = 'ConvexFn.comp_add_left'

[[node]]
id = 'scaleSnd'

[[node]]
id = 'convexFn_coe_mul'

[[node]]
id = 'convexFn_iff_forall_lt'

[[node]]
id = 'concaveFn_iff_forall_gt'

[[node]]
id = 'convexFn_iff_le'

[[node]]
id = 'concaveFn_iff_le'

[[node]]
id = 'ConvexFn.convex_lt'

[[node]]
id = 'ConcaveFn.convex_gt'

[[node]]
id = 'ConvexFn.convex_le'

[[node]]
id = 'ConcaveFn.convex_ge'

[[node]]
id = 'ConvexFn.convex_convexDom'

[[node]]
id = 'ConcaveFn.convex_concaveDom'

[[node]]
id = 'convexOn_iff_convexFn'

[[node]]
id = 'concaveOn_iff_concaveFn'

[[node]]
id = 'convexDom_coe'

[[node]]
id = 'concaveDom_coe'

[[node]]
id = 'properConvex_coe'

[[node]]
id = 'properConcave_coe'

[[node]]
id = 'convexDom_convexRestrict_coe'

[[node]]
id = 'concaveDom_concaveRestrict_coe'

[[node]]
id = 'properConvex_convexRestrict_coe'

[[node]]
id = 'properConcave_concaveRestrict_coe'

[[node]]
id = '_root_.ConvexOn.convexFn_convexRestrict_coe'

[[node]]
id = '_root_.ConcaveOn.concaveFn_concaveRestrict_coe'

[[node]]
id = '_root_.ConvexOn.convexFn_coe'

[[node]]
id = '_root_.ConcaveOn.concaveFn_coe'

[[node]]
id = 'ConvexFn.sum_le'
