namespace = 'ConvexAnalysis'

[[node]]
id = 'saddleSubdifferential'

[[node]]
id = 'domSaddleSubdifferential'

[[node]]
id = 'saddleTilt'

[[node]]
id = 'mem_saddleSubdifferential_iff_isSaddlePoint'

[[node]]
id = 'kernelSet_subset_domSaddleSubdifferential_subset_domSaddle'

[[node]]
id = 'IsBifunSubgradientPair'

[[node]]
id = 'mem_saddleSubdifferential_iff_isBifunSubgradientPair'

[[node]]
id = 'mem_saddleSubdifferential_upperConjSaddle_iff'

[[node]]
id = 'mem_saddleSubdifferential_upperConjSaddle_zero_iff'

[[node]]
id = 'exists_isSaddlePoint_of_zero_mem_kernelSet_upperConjSaddle'
