namespace = "ConjugateDirection"

[[node]]
id = "IsConjugateFamily"

[[node]]
id = "iterate"

[[node]]
id = "iterate_succ"

[[node]]
id = "iterate_succ_eq"

[[node]]
id = "residual_succ"

[[node]]
id = "iterate_sub_mem_span"

[[node]]
id = "iterate_add_eq_of_apply_eq"

[[node]]
id = "inner_residual_succ_direction_self_eq_zero"

[[node]]
id = "inner_residual_direction_eq_zero"

[[node]]
id = "inner_direction_residual_eq_zero"

[[node]]
id = "isGalerkin_iterate"

[[node]]
id = "IsConjugateFamily.linearIndependent"

[[node]]
id = "apply_iterate_eq_of_span_eq_top"

[[node]]
id = "apply_iterate_finrank_eq"

[[node]]
id = "iterate_eq_of_finrank_le"
