namespace = "AtkinsonHan.Chapter02"

[[node]]
id = "IsBoundedOperator"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.6"

[[node]]
id = "example_2_1_7"

[[node]]
id = "definition_2_1_1"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.1"

[[node]]
id = "definition_2_1_1_iff"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.1"

[[node]]
id = "definition_2_1_1_surjective"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.1"

[[node]]
id = "definition_2_1_1_surjective_iff"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.1"

[[node]]
id = "definition_2_1_1_bijection"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.1"

[[node]]
id = "definition_2_1_1_bijection_iff"
source = "Atkinson–Han, Theoretical Numerical Analysis, Definition 2.1.1"

[[node]]
id = "definition_2_1_1_inverse"
source = "Atkinson–Han, Theoretical Numerical Analysis, the remark after Definition 2.1.1"

[[node]]
id = "example_2_1_2"
source = "Atkinson–Han, Theoretical Numerical Analysis, Example 2.1.2"

[[node]]
id = "example_2_1_3"
source = "Atkinson–Han, Theoretical Numerical Analysis, Example 2.1.3"

[[node]]
id = "example_2_1_4"
source = "Atkinson–Han, Theoretical Numerical Analysis, Example 2.1.4"

[[node]]
id = "example_2_1_5"
source = "Atkinson–Han, Theoretical Numerical Analysis, Example 2.1.5"
