namespace = "AtkinsonHan.Chapter02"

[[node]]
id = "definition_2_8_1"

[[node]]
id = "proposition_2_8_4"

[[node]]
id = "proposition_2_8_6"

[[node]]
id = "proposition_2_8_7"

[[node]]
id = "theorem_2_8_10"

[[node]]
id = "theorem_2_8_10_inverse"

[[node]]
id = "theorem_2_8_12_1"

[[node]]
id = "theorem_2_8_12_2"

[[node]]
id = "theorem_2_8_12_4"

[[node]]
id = "lemma_2_8_13"

[[node]]
id = "theorem_2_8_14"

[[node]]
id = "theorem_2_8_14_isCompl"

[[node]]
id = "theorem_2_8_15"

[[node]]
id = "theorem_2_8_15_eigenvalue_real"

[[node]]
id = "theorem_2_8_15_closure_range"

[[node]]
id = "example_2_8_5"

[[node]]
id = "example_2_8_5_isCompactOperator"

[[node]]
id = "example_2_8_5_norm"

[[node]]
id = "example_2_8_8"

[[node]]
id = "example_2_8_8_interval"

[[node]]
id = "theorem_2_8_15_index"

[[node]]
id = "equation_2_8_2"

[[node]]
id = "equation_2_8_5"

[[node]]
id = "equation_2_8_6_le"

[[node]]
id = "equation_2_8_6"

[[node]]
id = "isCompactOperator_of_isAdmissibleKernel"

[[node]]
id = "example_2_8_2"

[[node]]
id = "example_2_8_9"

[[node]]
id = "theorem_2_8_12_3"

[[node]]
id = "theorem_2_8_12_5"

[[node]]
id = "theorem_2_8_12_6"

[[node]]
id = "theorem_2_8_14_dim"

[[node]]
id = "theorem_2_8_15_enumeration"

[[node]]
id = "theorem_2_8_14_hasEigenvalue_adjoint"
