namespace = "Tensor"

[[node]]
id = "_root_.Tensor"
deps = []

[[node]]
id = "frobenius_norm_def"

[[node]]
id = "rankOne"

[[node]]
id = "outer"

[[node]]
id = "eq_sum_rankOne_single"

[[node]]
id = "restrict"

[[node]]
id = "permute"

[[node]]
id = "ofMatrix"

[[node]]
id = "IsSymm"

[[node]]
id = "vecFin"

[[node]]
id = "vecFin_snoc"

[[node]]
id = "equivPiTensorProduct"
