namespace = "Tensor"

[[node]]
id = "ttPartial"
deps = []

[[node]]
id = "tensorTrain"

[[node]]
id = "exists_ttCore_of_rank"

[[node]]
id = "exists_ttPartial_eq_of_mem_span"

[[node]]
id = "exists_tensorTrain_of_ne_zero"
