namespace = "AtkinsonHan.Chapter04"

[[node]]
id = "bookConst"

[[node]]
id = "bookFourier"

[[node]]
id = "bookFourier_eq_fourier"

[[node]]
id = "bookFourierInv"

[[node]]
id = "equation_4_2_5"

[[node]]
id = "equation_4_2_6"

[[node]]
id = "equation_4_2_7_dim_one"

[[node]]
id = "definition_4_2_1"

[[node]]
id = "bookFourierCLM"

[[node]]
id = "equation_4_2_10"

[[node]]
id = "equation_4_2_11"

[[node]]
id = "definition_4_2_3"

[[node]]
id = "bookFourierTD"

[[node]]
id = "theorem_4_2_4"

[[node]]
id = "equation_4_2_7"

[[node]]
id = "equation_4_2_8"

[[node]]
id = "equation_4_2_12"

[[node]]
id = "bookFourierSchwartzEquiv"

[[node]]
id = "bookFourierL2"

[[node]]
id = "theorem_4_2_4_l2"
