import Numlib.Analysis.Wavelet.Daubechies
import Numlib.Analysis.Wavelet.Multiresolution
import NumlibSurface.AtkinsonHan.Chapter04.Section04

/-!
# Atkinson–Han §4.5: multiresolution analysis

Surface file for Kendall Atkinson and Weimin Han, *Theoretical Numerical Analysis: A Functional
Analysis Framework*, 3rd edition, Springer, 2009, §4.5.

Everything is the backbone `Numlib/Analysis/Wavelet/Multiresolution`: the bundled predicate
`IsMultiresolutionAnalysis`, the system `scalingSystem φ j k = 2^{j/2} φ(2^j x - k)` generated by
the scaling function, the wavelet `mraWavelet φ` of (4.5.4) with the systems and spaces it
generates, and the Haar instance `Haar.isMultiresolutionAnalysis` built from §4.4.

## Main results

* `definition_4_5_1` — the five axioms, as an equivalence with the bundled predicate.
* `proposition_4_5_2` — the level-`j` system is an orthonormal basis of `V_j`.
* `scalingCoeff`, `equation_4_5_2` — (4.5.1)–(4.5.3), the scaling equation and its dilated form.
* `haar_scalingCoeff` — the Haar coefficients `p₀ = p₁ = 1/√2`, and `p_k = 0` otherwise, and
  `haar_mraWavelet` — that (4.5.4) then gives back the Haar wavelet of §4.4.
* `exercise_4_5_2` — the necessary condition `∑_k p_k p_{k-2l} = δ_{0l}` on the coefficients.
* `equation_4_5_4` — the wavelet `ψ = ∑_k (-1)^k p_{1-k} √2 φ(2 · - k)`, and the convergence of
  that sum.
* `theorem_wavelet_spaces` — Mallat's theorem: `{ψ(· - k)}` is an orthonormal basis of
  `W_0 = V_1 ⊖ V_0`, the same at every level, the `W_j` are mutually orthogonal, and the whole
  family `{2^{j/2} ψ(2^j x - k)}_{j,k}` is an orthonormal basis of `L²(ℝ)`.
* `exercise_4_5_5`, `exercise_4_5_6_subset` — the values of the Daubechies `D4` scaling function
  at the first dyadic points, and the support bound for its wavelet, both under the hypothesis that
  a function with the properties (4.5.5)–(4.5.7) exists.
* `equation_4_5_6` — that such a function does exist: the Daubechies `D4` scaling function, with
  support exactly `[0, 3]`.  `exists_daubechies_values` combines the two, making the values of
  Exercise 4.5.5 unconditional.

## Conventions

Two of the book's five clauses are read differently from its prose, following the backbone.
*Shift invariance* is "the integer translates of `φ` are orthonormal and `V_0` is their closed
span", rather than "the translates are an orthonormal basis of `V_0`": the two say the same thing,
and the former is what a construction proves. *Scale invariance* is
`V_j = (V_0).map (dilation 2^j)` rather than the equivalence `f ∈ V_j ↔ f(2^{-j} ·) ∈ V_0`, for the
same reason and because images of spans compute under it.

"Orthonormal basis of `V_j`" is likewise not a bundled `HilbertBasis` here: `proposition_4_5_2`
gives orthonormality, the closed-span identity, and the expansion `f = ∑_k ⟪φ_{j,k}, f⟫ φ_{j,k}`
that consumers actually use, which avoids transporting a basis across `V_j = closure (span …)`.
`theorem_wavelet_spaces` reads the same way; the bundled form is
`IsMultiresolutionAnalysis.hilbertBasis` in the backbone.

The book writes the coefficients of the dilated scaling equation (4.5.3) as `p_{k-2l}`, the
*same* sequence that appears in (4.5.1) shifted by `2l`.  The second clause of `equation_4_5_2`
states (4.5.3) with the coefficients as they are, `⟪φ_{j+1,k}, φ_{j,l}⟫`.  What identifies those
with `p_{k-2l}` at level `0` is the backbone `translationₗᵢ_scalingSystem_one`, that a unit
translation at level `0` is a translation by two at level `1`; that is the lemma behind
`exercise_4_5_2`, and the backbone `IsMultiresolutionAnalysis.hasSum_scalingSystem_low` is (4.5.3)
in the book's own form, at every level.

## Not formalized here

Half of the existence theory that §4.5 defers to Daubechies: that a sequence `{p_k}` satisfying the
condition of Exercise 4.5.2 is the dilation-coefficient sequence of an actual scaling function.  The
quadrature mirror condition alone is *not* sufficient for that — `p₀ = p₃ = 1/√2` satisfies it and
its cascade limit `(1/3) 1_[0,3]` has non-orthonormal translates — so a correct statement needs a
further hypothesis such as Cohen's condition, and its standard proofs run on the Fourier side: the
periodisation `∑_k |φ̂(ξ + 2πk)|² = 1` characterising orthonormality of the integer translates, and
the relation `φ̂(ξ) = m₀(ξ/2) φ̂(ξ/2)`.  Of that theory the backbone has only the periodisation
identity, `Numlib/Analysis/Fourier/Periodisation`.  The *other* half,
the existence of the `D4` function of (4.5.5)–(4.5.7), is `equation_4_5_6`, and it needs none of it:
for one explicit mask the cascade iteration converges by an elementary matrix estimate.

The orthonormality of the integer translates of that `D4` function is not proved either; it is the
same Fourier-side statement.  So `equation_4_5_6` gives the function of (4.5.5)–(4.5.7), not a
multiresolution analysis built from it.

The stable-basis weakening of axiom (1) is left out too — the book only remarks that one may
renormalise to the orthonormal case.
-/

open MeasureTheory Real

namespace AtkinsonHan.Chapter04

/-! ### The five axioms -/

/-- **Definition 4.5.1.** A ladder `{V_j}` of subspaces of `L²(ℝ)` together with a scaling
function `φ` is a **multiresolution analysis** when it is

1. *shift invariant*: the integer translates `φ(· - k)` are orthonormal and `V_0` is their closed
   span;
2. *scale invariant*: `V_j` is the image of `V_0` under the unitary dilation by `2^j`;
3. *nested*: `V_j ⊆ V_{j+1}`;
4. *dense*: the union of the `V_j` is dense in `L²(ℝ)`;
5. *separated*: the `V_j` meet in `{0}`.

These five clauses are exactly the fields of the backbone `IsMultiresolutionAnalysis`. -/
theorem definition_4_5_1 (V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ)))
    (φ : Lp ℝ 2 (volume : Measure ℝ)) :
    IsMultiresolutionAnalysis V φ ↔
      ((Orthonormal ℝ (translates φ) ∧
          V 0 = (Submodule.span ℝ (Set.range (translates φ))).topologicalClosure) ∧
        (∀ j : ℤ, V j = (V 0).map (Lp.dilationₗᵢ ((2 : ℝ) ^ j)
          (zpow_ne_zero j two_ne_zero)).toLinearEquiv.toLinearMap) ∧
        (∀ j : ℤ, V j ≤ V (j + 1)) ∧
        (⨆ j : ℤ, V j).topologicalClosure = ⊤ ∧
        (⨅ j : ℤ, V j) = ⊥) :=
  ⟨fun h => ⟨⟨h.orthonormal_translates, h.eq_topologicalClosure_span⟩, h.eq_map_dilation,
      h.le_succ, h.topologicalClosure_iSup, h.iInf_eq_bot⟩,
    fun h => ⟨h.1.1, h.1.2, h.2.1, h.2.2.1, h.2.2.2.1, h.2.2.2.2⟩⟩

section

variable {V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ))}
  {φ : Lp ℝ 2 (volume : Measure ℝ)}

/-- **Proposition 4.5.2.** In a multiresolution analysis the functions
`2^{j/2} φ(2^j x - k)`, `k ∈ ℤ`, are an orthonormal basis of `V_j` for every `j`: they are
orthonormal, `V_j` is the closure of their span, and every `f ∈ V_j` is the sum of its
coefficients against them.

The expansion is stated instead of a bundled `HilbertBasis` because it is what every consumer
wants and it does not have to be transported across `V_j = closure (span …)`. -/
theorem proposition_4_5_2 (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    Orthonormal ℝ (scalingSystem φ j) ∧
      V j = (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure ∧
      ∀ f ∈ V j,
        HasSum (fun k : ℤ => (inner ℝ (scalingSystem φ j k) f) • scalingSystem φ j k) f :=
  ⟨h.orthonormal_scaled j, h.eq_topologicalClosure_span_scalingSystem j,
    fun _ hf => h.hasSum_inner_smul j hf⟩

/-! ### The scaling equation -/

/-- **(4.5.2)**, the dilation coefficients of a scaling function,
`p_l = ∫ √2 φ(2x - l) φ(x) dx = ⟪φ_{1,l}, φ⟫`. -/
noncomputable abbrev scalingCoeff (φ : Lp ℝ 2 (volume : Measure ℝ)) (k : ℤ) : ℝ :=
  _root_.scalingCoeff φ k

/-- **(4.5.1)** and **(4.5.3)**, the scaling equation and its dilated form.  In a multiresolution
analysis `φ ∈ V_0 ⊆ V_1`, so expanding it in the orthonormal system of `V_1` gives

`φ = ∑_k p_k √2 φ(2x - k)`,

and the same argument applied to `φ_{j,l} ∈ V_j ⊆ V_{j+1}` expands each level-`j` scaling function
in the level-`(j+1)` system.  The book writes the latter coefficients as `p_{k-2l}`; see the
conventions above. -/
theorem equation_4_5_2 (h : IsMultiresolutionAnalysis V φ) :
    HasSum (fun k : ℤ => scalingCoeff φ k • scalingSystem φ 1 k) φ ∧
      ∀ j l : ℤ, HasSum (fun k : ℤ =>
        (inner ℝ (scalingSystem φ (j + 1) k) (scalingSystem φ j l)) • scalingSystem φ (j + 1) k)
        (scalingSystem φ j l) :=
  ⟨h.hasSum_scalingEquation,
    fun j l => h.hasSum_inner_smul (j + 1) (h.le_succ j (h.scalingSystem_mem j l))⟩

/-- **Exercise 4.5.2**, the necessary condition on the dilation coefficients: for the integer
translates of the scaling function to be orthonormal, its coefficients must satisfy

`∑_k p_k p_{k - 2l} = δ_{0l}`.

The book gives this as the sample of the identities that constrain `{p_k}`, and remarks that it is
difficult to find coefficients satisfying them all; the constructions that do are what §4.5 leaves
to Daubechies. -/
theorem exercise_4_5_2 (h : IsMultiresolutionAnalysis V φ) (l : ℤ) :
    HasSum (fun k : ℤ => scalingCoeff φ k * scalingCoeff φ (k - 2 * l))
      (if l = 0 then (1 : ℝ) else 0) :=
  h.hasSum_scalingCoeff_mul l

/-! ### The wavelet and the wavelet spaces -/

/-- **(4.5.4)**, the wavelet attached to the scaling function of a multiresolution analysis:

`ψ(x) = ∑_k (-1)^k p_{1-k} √2 φ(2x - k)`.

The function itself is the backbone `mraWavelet φ`, defined by this very sum; the content of the
statement is that the sum converges in `L²(ℝ)`, which holds because `∑_k p_k² = 1`. -/
theorem equation_4_5_4 (h : IsMultiresolutionAnalysis V φ) :
    HasSum (fun k : ℤ => ((-1 : ℝ) ^ k * scalingCoeff φ (1 - k)) • scalingSystem φ 1 k)
      (mraWavelet φ) :=
  h.hasSum_mraWavelet

/-- **Mallat's theorem**, the properties of the wavelet spaces `W_j = V_{j+1} ⊖ V_j` that the
section lists without proof.  For the `ψ` of (4.5.4):

1. `ψ ∈ V_1`, its integer translates are orthonormal, and `W_0` is their closed span — that is,
   `{ψ(· - k)}` is an orthonormal basis of `W_0`;
2. the same holds at every level: `{2^{j/2} ψ(2^j x - k)}_k` is an orthonormal basis of `W_j`;
3. the wavelet spaces are mutually orthogonal;
4. the whole family `{2^{j/2} ψ(2^j x - k)}_{j,k}` is an orthonormal basis of `L²(ℝ)`, so every
   `f ∈ L²(ℝ)` is the sum of its wavelet coefficients.

The book refers the reader to Daubechies for the proof, which runs on the Fourier side.  The
backbone proves it without one: see the design note of `Numlib/Analysis/Wavelet/Multiresolution`.

Clause 2 of the book's list, that `f ∈ W_j` iff `f(2^{-j} ·) ∈ W_0`, is not restated: it is the
scale invariance of the ladder and holds by construction, `W_j` being defined from `V_j` and
`V_{j+1}`. -/
theorem theorem_wavelet_spaces (h : IsMultiresolutionAnalysis V φ) :
    mraWavelet φ ∈ V 1 ∧
      Orthonormal ℝ (translates (mraWavelet φ)) ∧
      waveletSpace V 0
        = (Submodule.span ℝ (Set.range (translates (mraWavelet φ)))).topologicalClosure ∧
      (∀ j : ℤ, Orthonormal ℝ (waveletSystem φ j) ∧
        waveletSpace V j
          = (Submodule.span ℝ (Set.range (waveletSystem φ j))).topologicalClosure) ∧
      (∀ i j : ℤ, i ≠ j → ∀ u ∈ waveletSpace V i, ∀ v ∈ waveletSpace V j,
        inner ℝ u v = (0 : ℝ)) ∧
      Orthonormal ℝ (fun jk : ℤ × ℤ => waveletSystem φ jk.1 jk.2) ∧
      ∀ f : Lp ℝ 2 (volume : Measure ℝ), HasSum (fun jk : ℤ × ℤ =>
        (inner ℝ (waveletSystem φ jk.1 jk.2) f) • waveletSystem φ jk.1 jk.2) f := by
  have h0 : waveletSystem φ 0 = translates (mraWavelet φ) := scalingSystem_zero (mraWavelet φ)
  refine ⟨h.mraWavelet_mem_V_one, ?_, ?_,
    fun j => ⟨h.orthonormal_waveletSystem j, h.waveletSpace_eq j⟩, ?_,
    h.orthonormal_waveletSystem_prod, h.hasSum_inner_smul_waveletSystem⟩
  · rw [← h0]
    exact h.orthonormal_waveletSystem 0
  · rw [← h0]
    exact h.waveletSpace_eq 0
  · intro i j hij u hu v hv
    rcases lt_or_gt_of_ne hij with hlt | hlt
    · exact h.inner_waveletSpace_eq_zero_of_lt hlt hu hv
    · rw [real_inner_comm]
      exact h.inner_waveletSpace_eq_zero_of_lt hlt hv hu

end

/-- The dilation coefficients of the **Haar** multiresolution analysis, whose scaling function is
the unit step `φ = 1_[0,1)`: `p₀ = p₁ = 1/√2` and every other `p_k` vanishes.  This is the
two-scale relation `φ(x) = φ(2x) + φ(2x - 1)` of §4.4 read in the normalised basis. -/
theorem haar_scalingCoeff :
    scalingCoeff (Haar.scalingFun 0 0) 0 = (√2)⁻¹ ∧
      scalingCoeff (Haar.scalingFun 0 0) 1 = (√2)⁻¹ ∧
      ∀ k : ℤ, k ≠ 0 → k ≠ 1 → scalingCoeff (Haar.scalingFun 0 0) k = 0 := by
  have hsys : ∀ k : ℤ, scalingSystem (Haar.scalingFun 0 0) 1 k = Haar.scalingFun 1 k := by
    intro k
    have h1 : scalingSystem (Haar.scalingFun 0 0) 1 k
        = Lp.dilationₗᵢ ((2 : ℝ) ^ (1 : ℤ)) (zpow_ne_zero 1 two_ne_zero)
          (translates (Haar.scalingFun 0 0) k) := rfl
    rw [h1, Haar.translates_scalingFun_zero, ← Haar.scalingFun_eq_dilation]
  have hexp : Haar.scalingFun 0 0 = (√2)⁻¹ • (Haar.scalingFun 1 0 + Haar.scalingFun 1 1) := by
    simpa using Haar.scalingFun_two_scale 0 0
  have hcoeff : ∀ k : ℤ, scalingCoeff (Haar.scalingFun 0 0) k
      = (√2)⁻¹ * (inner ℝ (Haar.scalingFun 1 k) (Haar.scalingFun 1 0)
          + inner ℝ (Haar.scalingFun 1 k) (Haar.scalingFun 1 1)) := by
    intro k
    change inner ℝ (scalingSystem (Haar.scalingFun 0 0) 1 k) (Haar.scalingFun 0 0) = _
    rw [hsys k, hexp, real_inner_smul_right, inner_add_right]
  refine ⟨?_, ?_, ?_⟩
  · rw [hcoeff, Haar.inner_scalingFun_self,
      Haar.inner_scalingFun_of_ne 1 (by norm_num : (0 : ℤ) ≠ 1)]
    ring
  · rw [hcoeff, Haar.inner_scalingFun_of_ne 1 (by norm_num : (1 : ℤ) ≠ 0),
      Haar.inner_scalingFun_self]
    ring
  · intro k hk0 hk1
    rw [hcoeff, Haar.inner_scalingFun_of_ne 1 hk0, Haar.inner_scalingFun_of_ne 1 hk1]
    ring

/-- **The general construction reproduces the Haar wavelet.** The Haar dilation coefficients are
`p₀ = p₁ = 1/√2`, so the high-pass coefficients `(-1)^k p_{1-k}` of (4.5.4) are `1/√2` at `k = 0`,
`-1/√2` at `k = 1` and zero elsewhere, and the wavelet (4.5.4) is
`ψ = (1/√2)(√2 φ(2x) - √2 φ(2x-1))`, the Haar wavelet of §4.4.

This is the sanity check on `mraWavelet`: the one multiresolution analysis with an explicit wavelet
gets the wavelet it should. -/
theorem haar_mraWavelet : mraWavelet (Haar.scalingFun 0 0) = Haar.waveletFun 0 0 := by
  obtain ⟨hp0, hp1, hpk⟩ := haar_scalingCoeff
  have hsys : ∀ k : ℤ, scalingSystem (Haar.scalingFun 0 0) 1 k = Haar.scalingFun 1 k := by
    intro k
    have h1 : scalingSystem (Haar.scalingFun 0 0) 1 k
        = Lp.dilationₗᵢ ((2 : ℝ) ^ (1 : ℤ)) (zpow_ne_zero 1 two_ne_zero)
          (translates (Haar.scalingFun 0 0) k) := rfl
    rw [h1, Haar.translates_scalingFun_zero, ← Haar.scalingFun_eq_dilation]
  have hfin : HasSum (fun k : ℤ => qmfHigh (scalingCoeff (Haar.scalingFun 0 0)) k
        • scalingSystem (Haar.scalingFun 0 0) 1 k)
      (∑ k ∈ ({0, 1} : Finset ℤ), qmfHigh (scalingCoeff (Haar.scalingFun 0 0)) k
        • scalingSystem (Haar.scalingFun 0 0) 1 k) :=
    hasSum_sum_of_ne_finset_zero (fun k hk => by
      simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hk
      rw [qmfHigh, hpk (1 - k) (by omega) (by omega), mul_zero, zero_smul])
  rw [Haar.isMultiresolutionAnalysis.hasSum_mraWavelet.unique hfin]
  rw [Finset.sum_insert (by decide), Finset.sum_singleton]
  simp only [qmfHigh, hsys, Haar.waveletFun, zpow_zero, zpow_one,
    show (1 : ℤ) - 0 = 1 from by ring, show (1 : ℤ) - 1 = 0 from by ring, hp0, hp1,
    show (2 : ℤ) * 0 = 0 from by ring, show (0 : ℤ) + 1 = 1 from by ring]
  module

/-! ### The Daubechies example -/

/-- **The values of the Daubechies `D4` scaling function at the first dyadic points.** For a
function `φ` with the three properties (4.5.5)–(4.5.7) — supported in `[0, 3]`, satisfying the
four-term scaling equation (4.5.6), and normalised by `φ(1) = (1+√3)/2`, `φ(2) = (1-√3)/2` — the
scaling equation determines `φ` at every dyadic point, and the first few values are those the book
computes and asks for in Exercise 4.5.5:

`φ(0) = φ(3) = 0`, `φ(1/2) = (2+√3)/4`, `φ(3/2) = 0` and `φ(1/4) = (5+3√3)/16`.

The vanishing at the endpoints is not assumed: it follows from the scaling equation, because the
coefficients `(1+√3)/4` and `(1-√3)/4` of the two end terms are not `1`.

That such a `φ` exists is Daubechies' construction, which the book states without proof; it is
`equation_4_5_6`, and this statement is stated independently of it.  `exists_daubechies_values`
puts the two together. -/
theorem exercise_4_5_5 {φ : ℝ → ℝ} (hsupp : ∀ x : ℝ, x < 0 ∨ 3 < x → φ x = 0)
    (hscal : ∀ x : ℝ, φ x = (1 + √3) / 4 * φ (2 * x) + (3 + √3) / 4 * φ (2 * x - 1)
      + (3 - √3) / 4 * φ (2 * x - 2) + (1 - √3) / 4 * φ (2 * x - 3))
    (hone : φ 1 = (1 + √3) / 2) (htwo : φ 2 = (1 - √3) / 2) :
    φ 0 = 0 ∧ φ 3 = 0 ∧ φ (1 / 2) = (2 + √3) / 4 ∧ φ (3 / 2) = 0 ∧
      φ (1 / 4) = (5 + 3 * √3) / 16 := by
  have hs3 : √3 * √3 = 3 := Real.mul_self_sqrt (by norm_num)
  have hs3lt : √3 < 3 := by nlinarith [Real.sqrt_nonneg 3]
  have hneg : ∀ x : ℝ, x < 0 → φ x = 0 := fun x hx => hsupp x (Or.inl hx)
  have hbig : ∀ x : ℝ, 3 < x → φ x = 0 := fun x hx => hsupp x (Or.inr hx)
  -- the endpoints, from the scaling equation alone
  have h0 : φ 0 = 0 := by
    have h := hscal 0
    rw [hneg ((2 : ℝ) * 0 - 1) (by norm_num), hneg ((2 : ℝ) * 0 - 2) (by norm_num),
      hneg ((2 : ℝ) * 0 - 3) (by norm_num), show (2 : ℝ) * 0 = 0 by norm_num] at h
    have hkey : ((3 - √3) / 4) * φ 0 = 0 := by linarith
    rcases mul_eq_zero.mp hkey with h' | h'
    · exact absurd h' (by intro hc; rw [div_eq_zero_iff] at hc; rcases hc with hc | hc <;> linarith)
    · exact h'
  have h3 : φ 3 = 0 := by
    have h := hscal 3
    rw [hbig ((2 : ℝ) * 3 - 1) (by norm_num), hbig ((2 : ℝ) * 3 - 2) (by norm_num),
      show (2 : ℝ) * 3 - 3 = 3 by norm_num, hbig ((2 : ℝ) * 3) (by norm_num)] at h
    have hkey : ((3 + √3) / 4) * φ 3 = 0 := by linarith
    rcases mul_eq_zero.mp hkey with h' | h'
    · exact absurd h' (by
        intro hc
        rw [div_eq_zero_iff] at hc
        rcases hc with hc | hc <;> nlinarith [Real.sqrt_nonneg 3])
    · exact h'
  -- the book's worked value at `1/2`, and Exercise 4.5.5
  have hhalf : φ (1 / 2) = (2 + √3) / 4 := by
    have h := hscal (1 / 2)
    rw [show (2 : ℝ) * (1 / 2) - 1 = 0 by norm_num,
      hneg ((2 : ℝ) * (1 / 2) - 2) (by norm_num), hneg ((2 : ℝ) * (1 / 2) - 3) (by norm_num),
      show (2 : ℝ) * (1 / 2) = 1 by norm_num, hone, h0] at h
    rw [h]
    linear_combination hs3 / 8
  refine ⟨h0, h3, hhalf, ?_, ?_⟩
  · have h := hscal (3 / 2)
    rw [show (2 : ℝ) * (3 / 2) - 1 = 2 by norm_num, show (2 : ℝ) * (3 / 2) - 2 = 1 by norm_num,
      show (2 : ℝ) * (3 / 2) - 3 = 0 by norm_num, show (2 : ℝ) * (3 / 2) = 3 by norm_num,
      h3, htwo, hone, h0] at h
    rw [h]
    linear_combination -hs3 / 4
  · have h := hscal (1 / 4)
    rw [hneg ((2 : ℝ) * (1 / 4) - 1) (by norm_num), hneg ((2 : ℝ) * (1 / 4) - 2) (by norm_num),
      hneg ((2 : ℝ) * (1 / 4) - 3) (by norm_num), show (2 : ℝ) * (1 / 4) = 1 / 2 by norm_num,
      hhalf] at h
    rw [h]
    linear_combination hs3 / 16

/-- **Half of Exercise 4.5.6**: the Daubechies wavelet (4.5.8) vanishes outside `[-1, 2]`, so its
support is contained in that interval.

Only the inclusion is proved, and it holds for any `φ` vanishing off `[0, 3]`.  The book asks for
the equality `supp ψ = [-1, 2]`, which is a statement about one particular `φ` and needs the
counterpart for `ψ` of `Daubechies.scalingFun_support` — that `ψ` vanishes identically on no
nondegenerate subinterval of `[-1, 2]`.  That is a separate argument, and is not made here. -/
theorem exercise_4_5_6_subset {φ ψ : ℝ → ℝ} (hsupp : ∀ x : ℝ, x < 0 ∨ 3 < x → φ x = 0)
    (hpsi : ∀ x : ℝ, ψ x = -((1 + √3) / 4) * φ (2 * x - 1) + (3 + √3) / 4 * φ (2 * x)
      - (3 - √3) / 4 * φ (2 * x + 1) + (1 - √3) / 4 * φ (2 * x + 2))
    {x : ℝ} (hx : x < -1 ∨ 2 < x) : ψ x = 0 := by
  rcases hx with hx | hx
  · rw [hpsi, hsupp (2 * x - 1) (Or.inl (by linarith)), hsupp (2 * x) (Or.inl (by linarith)),
      hsupp (2 * x + 1) (Or.inl (by linarith)), hsupp (2 * x + 2) (Or.inl (by linarith))]
    ring
  · rw [hpsi, hsupp (2 * x - 1) (Or.inr (by linarith)), hsupp (2 * x) (Or.inr (by linarith)),
      hsupp (2 * x + 1) (Or.inr (by linarith)), hsupp (2 * x + 2) (Or.inr (by linarith))]
    ring

/-- **(4.5.5)–(4.5.7): the Daubechies `D4` scaling function exists.**  There is a continuous
`φ : ℝ → ℝ` with

* `supp φ = [0, 3]`, that is `closure {x | φ x ≠ 0} = [0, 3]` — and in particular `φ` vanishes
  outside `[0, 3]`;
* the four-term scaling equation
  `φ(x) = (1+√3)/4 φ(2x) + (3+√3)/4 φ(2x-1) + (3-√3)/4 φ(2x-2) + (1-√3)/4 φ(2x-3)`;
* the normalisation `φ(1) = (1+√3)/2`, `φ(2) = (1-√3)/2`.

The book introduces this function by these three properties and computes its values from them —
that is `exercise_4_5_5`, which is stated of a function *assumed* to have them; that such a
function exists is Daubechies' theorem, which the book states without proof.  The backbone
`Numlib/Analysis/Wavelet/Daubechies` proves it by the cascade iteration, whose convergence rests
on an explicit joint-spectral-radius bound for the two matrices attached to this mask; the sharp
support statement then comes from the injectivity of their transposes. -/
theorem equation_4_5_6 :
    ∃ φ : ℝ → ℝ, Continuous φ ∧ (∀ x : ℝ, x < 0 ∨ 3 < x → φ x = 0) ∧
      closure (Function.support φ) = Set.Icc 0 3 ∧
      (∀ x : ℝ, φ x = (1 + √3) / 4 * φ (2 * x) + (3 + √3) / 4 * φ (2 * x - 1)
        + (3 - √3) / 4 * φ (2 * x - 2) + (1 - √3) / 4 * φ (2 * x - 3)) ∧
      φ 1 = (1 + √3) / 2 ∧ φ 2 = (1 - √3) / 2 :=
  Daubechies.exists_scalingFun

/-- **The Daubechies function of (4.5.5)–(4.5.7) has the values of Exercise 4.5.5.**  Combining
`equation_4_5_6` with `exercise_4_5_5` makes the exercise unconditional: the function whose
existence the section asserts really does have

`φ(0) = φ(3) = 0`, `φ(1/2) = (2+√3)/4`, `φ(3/2) = 0`, `φ(1/4) = (5+3√3)/16`. -/
theorem exists_daubechies_values :
    ∃ φ : ℝ → ℝ, Continuous φ ∧ closure (Function.support φ) = Set.Icc 0 3 ∧
      (∀ x : ℝ, φ x = (1 + √3) / 4 * φ (2 * x) + (3 + √3) / 4 * φ (2 * x - 1)
        + (3 - √3) / 4 * φ (2 * x - 2) + (1 - √3) / 4 * φ (2 * x - 3)) ∧
      φ 1 = (1 + √3) / 2 ∧ φ 2 = (1 - √3) / 2 ∧
      φ 0 = 0 ∧ φ 3 = 0 ∧ φ (1 / 2) = (2 + √3) / 4 ∧ φ (3 / 2) = 0 ∧
      φ (1 / 4) = (5 + 3 * √3) / 16 := by
  obtain ⟨φ, hcont, hsupp, hclos, hscal, hone, htwo⟩ := equation_4_5_6
  obtain ⟨h0, h3, hhalf, h32, h14⟩ := exercise_4_5_5 hsupp hscal hone htwo
  exact ⟨φ, hcont, hclos, hscal, hone, htwo, h0, h3, hhalf, h32, h14⟩

end AtkinsonHan.Chapter04
