import Numlib.Analysis.Wavelet.Multiresolution
import NumlibSurface.AtkinsonHan.Chapter04.Section04

/-!
# Atkinson–Han §4.5: multiresolution analysis

Surface file for Kendall Atkinson and Weimin Han, *Theoretical Numerical Analysis: A Functional
Analysis Framework*, 3rd edition, Springer, 2009, §4.5.

Everything is the backbone `Numlib/Analysis/Wavelet/Multiresolution`: the bundled predicate
`IsMultiresolutionAnalysis`, the system `scalingSystem φ j k = 2^{j/2} φ(2^j x - k)` generated by
the scaling function, and the Haar instance `Haar.isMultiresolutionAnalysis` built from §4.4.

## Main results

* `definition_4_5_1` — the five axioms, as an equivalence with the bundled predicate.
* `proposition_4_5_2` — the level-`j` system is an orthonormal basis of `V_j`.
* `scalingCoeff`, `equation_4_5_2` — (4.5.1)–(4.5.3), the scaling equation and its dilated form.
* `haar_scalingCoeff` — the Haar coefficients `p₀ = p₁ = 1/√2`, and `p_k = 0` otherwise.

## Conventions

Two of the book's five clauses are read differently from its prose, following the backbone.
*Shift invariance* is "the integer translates of `φ` are orthonormal and `V_0` is their closed
span", rather than "the translates are an orthonormal basis of `V_0`": the two say the same thing,
and the former is what a construction proves. *Scale invariance* is
`V_j = (V_0).map (dilation 2^j)` rather than the equivalence `f ∈ V_j ↔ f(2^{-j} ·) ∈ V_0`, for the
same reason and because images of spans compute under it.

"Orthonormal basis of `V_j`" is likewise not a bundled `HilbertBasis` here: `proposition_4_5_2`
gives orthonormality, the closed-span identity, and the expansion `f = ∑_k ⟪φ_{j,k}, f⟫ φ_{j,k}`
that consumers actually use, which avoids transporting a basis across `V_j = closure (span …)`.

The book writes the coefficients of the dilated scaling equation (4.5.3) as `p_{k-2l}`, the
*same* sequence that appears in (4.5.1) shifted by `2l`.  The second clause of `equation_4_5_2`
states (4.5.3) with the coefficients as they are, `⟪φ_{j+1,k}, φ_{j,l}⟫`; identifying them with
`p_{k-2l}` needs the commutation of translation with dilation on `L²(ℝ)`, which the backbone does
not yet state.  Nothing later in the book's development of this section is formalized, so nothing
depends on the reindexing.

## Not formalized here

Most of the rest of the section: the construction of a scaling function from its dilation
coefficients, the claim that the `ψ` of (4.5.4) generates the wavelet spaces, the four listed
properties of the `W_j` for a general multiresolution analysis, the fixed-point computation of `φ`
and the Daubechies example (4.5.5)–(4.5.6).  Atkinson–Han state all of these without proof and
refer to Daubechies; the standard arguments run through conditions on `φ̂`, a piece of harmonic
analysis Mathlib does not have.  The stable-basis weakening of axiom (1) is left out too — the
book only remarks that one may renormalise to the orthonormal case.
-/

open MeasureTheory Real

namespace AtkinsonHan.Chapter04

/-! ### The five axioms -/

/-- **Definition 4.5.1.** A ladder `{V_j}` of subspaces of `L²(ℝ)` together with a scaling
function `φ` is a **multiresolution analysis** when it is

1. *shift invariant*: the integer translates `φ(· - k)` are orthonormal and `V_0` is their closed
   span;
2. *scale invariant*: `V_j` is the image of `V_0` under the unitary dilation by `2^j`;
3. *nested*: `V_j ⊆ V_{j+1}`;
4. *dense*: the union of the `V_j` is dense in `L²(ℝ)`;
5. *separated*: the `V_j` meet in `{0}`.

These five clauses are exactly the fields of the backbone `IsMultiresolutionAnalysis`. -/
theorem definition_4_5_1 (V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ)))
    (φ : Lp ℝ 2 (volume : Measure ℝ)) :
    IsMultiresolutionAnalysis V φ ↔
      ((Orthonormal ℝ (translates φ) ∧
          V 0 = (Submodule.span ℝ (Set.range (translates φ))).topologicalClosure) ∧
        (∀ j : ℤ, V j = (V 0).map (Lp.dilationₗᵢ ((2 : ℝ) ^ j)
          (zpow_ne_zero j two_ne_zero)).toLinearEquiv.toLinearMap) ∧
        (∀ j : ℤ, V j ≤ V (j + 1)) ∧
        (⨆ j : ℤ, V j).topologicalClosure = ⊤ ∧
        (⨅ j : ℤ, V j) = ⊥) :=
  ⟨fun h => ⟨⟨h.orthonormal_translates, h.eq_topologicalClosure_span⟩, h.eq_map_dilation,
      h.le_succ, h.topologicalClosure_iSup, h.iInf_eq_bot⟩,
    fun h => ⟨h.1.1, h.1.2, h.2.1, h.2.2.1, h.2.2.2.1, h.2.2.2.2⟩⟩

section

variable {V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ))}
  {φ : Lp ℝ 2 (volume : Measure ℝ)}

/-- **Proposition 4.5.2.** In a multiresolution analysis the functions
`2^{j/2} φ(2^j x - k)`, `k ∈ ℤ`, are an orthonormal basis of `V_j` for every `j`: they are
orthonormal, `V_j` is the closure of their span, and every `f ∈ V_j` is the sum of its
coefficients against them.

The expansion is stated instead of a bundled `HilbertBasis` because it is what every consumer
wants and it does not have to be transported across `V_j = closure (span …)`. -/
theorem proposition_4_5_2 (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    Orthonormal ℝ (scalingSystem φ j) ∧
      V j = (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure ∧
      ∀ f ∈ V j,
        HasSum (fun k : ℤ => (inner ℝ (scalingSystem φ j k) f) • scalingSystem φ j k) f :=
  ⟨h.orthonormal_scaled j, h.eq_topologicalClosure_span_scalingSystem j,
    fun _ hf => h.hasSum_inner_smul j hf⟩

/-! ### The scaling equation -/

/-- **(4.5.2)**, the dilation coefficients of a scaling function,
`p_l = ∫ √2 φ(2x - l) φ(x) dx = ⟪φ_{1,l}, φ⟫`. -/
noncomputable abbrev scalingCoeff (φ : Lp ℝ 2 (volume : Measure ℝ)) (k : ℤ) : ℝ :=
  inner ℝ (scalingSystem φ 1 k) φ

/-- **(4.5.1)** and **(4.5.3)**, the scaling equation and its dilated form.  In a multiresolution
analysis `φ ∈ V_0 ⊆ V_1`, so expanding it in the orthonormal system of `V_1` gives

`φ = ∑_k p_k √2 φ(2x - k)`,

and the same argument applied to `φ_{j,l} ∈ V_j ⊆ V_{j+1}` expands each level-`j` scaling function
in the level-`(j+1)` system.  The book writes the latter coefficients as `p_{k-2l}`; see the
conventions above. -/
theorem equation_4_5_2 (h : IsMultiresolutionAnalysis V φ) :
    HasSum (fun k : ℤ => scalingCoeff φ k • scalingSystem φ 1 k) φ ∧
      ∀ j l : ℤ, HasSum (fun k : ℤ =>
        (inner ℝ (scalingSystem φ (j + 1) k) (scalingSystem φ j l)) • scalingSystem φ (j + 1) k)
        (scalingSystem φ j l) :=
  ⟨h.hasSum_scalingEquation,
    fun j l => h.hasSum_inner_smul (j + 1) (h.le_succ j (h.scalingSystem_mem j l))⟩

end

/-- The dilation coefficients of the **Haar** multiresolution analysis, whose scaling function is
the unit step `φ = 1_[0,1)`: `p₀ = p₁ = 1/√2` and every other `p_k` vanishes.  This is the
two-scale relation `φ(x) = φ(2x) + φ(2x - 1)` of §4.4 read in the normalised basis. -/
theorem haar_scalingCoeff :
    scalingCoeff (Haar.scalingFun 0 0) 0 = (√2)⁻¹ ∧
      scalingCoeff (Haar.scalingFun 0 0) 1 = (√2)⁻¹ ∧
      ∀ k : ℤ, k ≠ 0 → k ≠ 1 → scalingCoeff (Haar.scalingFun 0 0) k = 0 := by
  have hsys : ∀ k : ℤ, scalingSystem (Haar.scalingFun 0 0) 1 k = Haar.scalingFun 1 k := by
    intro k
    have h1 : scalingSystem (Haar.scalingFun 0 0) 1 k
        = Lp.dilationₗᵢ ((2 : ℝ) ^ (1 : ℤ)) (zpow_ne_zero 1 two_ne_zero)
          (translates (Haar.scalingFun 0 0) k) := rfl
    rw [h1, Haar.translates_scalingFun_zero, ← Haar.scalingFun_eq_dilation]
  have hexp : Haar.scalingFun 0 0 = (√2)⁻¹ • (Haar.scalingFun 1 0 + Haar.scalingFun 1 1) := by
    simpa using Haar.scalingFun_two_scale 0 0
  have hcoeff : ∀ k : ℤ, scalingCoeff (Haar.scalingFun 0 0) k
      = (√2)⁻¹ * (inner ℝ (Haar.scalingFun 1 k) (Haar.scalingFun 1 0)
          + inner ℝ (Haar.scalingFun 1 k) (Haar.scalingFun 1 1)) := by
    intro k
    change inner ℝ (scalingSystem (Haar.scalingFun 0 0) 1 k) (Haar.scalingFun 0 0) = _
    rw [hsys k, hexp, real_inner_smul_right, inner_add_right]
  refine ⟨?_, ?_, ?_⟩
  · rw [hcoeff, Haar.inner_scalingFun_self,
      Haar.inner_scalingFun_of_ne 1 (by norm_num : (0 : ℤ) ≠ 1)]
    ring
  · rw [hcoeff, Haar.inner_scalingFun_of_ne 1 (by norm_num : (1 : ℤ) ≠ 0),
      Haar.inner_scalingFun_self]
    ring
  · intro k hk0 hk1
    rw [hcoeff, Haar.inner_scalingFun_of_ne 1 hk0, Haar.inner_scalingFun_of_ne 1 hk1]
    ring

end AtkinsonHan.Chapter04
