namespace = "Matrix"

[[node]]
id = "blockTridiagonal"

[[node]]
id = "tridiagonalLUPivot"

[[node]]
id = "tridiagonalLUMultiplier"

[[node]]
id = "tridiagonalOf_eq_mul_of_isUnit_tridiagonalLUPivot"

[[node]]
id = "tridiagonalLUPivot_eq_thomasAlpha"

[[node]]
id = "IsStrictBlockColDiagDominant"

[[node]]
id = "isStrictBlockColDiagDominant_tridiagonalOf_iff"

[[node]]
id = "IsStrictBlockColDiagDominant.isUnit_tridiagonalLUPivot"

[[node]]
id = "IsStrictBlockColDiagDominant.lpOpNorm_tridiagonalLUMultiplier_le"

[[node]]
id = "IsStrictBlockColDiagDominant.lpOpNorm_tridiagonalLUPivot_le"

[[node]]
id = "IsStrictBlockColDiagDominant.isUnit_blockTridiagonal"

[[node]]
id = "blockTridiagonal_apply"

[[node]]
id = "tridiagonalLUPivot_succ"

[[node]]
id = "tridiagonalLUMultiplier_mul_tridiagonalLUPivot"
