namespace = "Matrix"

[[node]]
id = "PosSemidef.norm_apply_sq_le_mul_re_diag"

[[node]]
id = "PosDef.norm_apply_le_max_re_diag"

[[node]]
id = "PosDef.leadingPrincipalSubmatrix"

[[node]]
id = "PosDef.strictLeadingPrincipalSubmatrix"

[[node]]
id = "PosDef.det_leadingPrincipalSubmatrix_pos"

[[node]]
id = "PosDef.isUnit_leadingPrincipalSubmatrix"

[[node]]
id = "PosDef.isUnit_strictLeadingPrincipalSubmatrix"

[[node]]
id = "IsLowerTriangular.conjTranspose_isUpperTriangular"

[[node]]
id = "IsUpperTriangular.conjTranspose_isLowerTriangular"

[[node]]
id = "IsUnitLowerTriangular.conjTranspose_transpose"

[[node]]
id = "IsLDM.conjTranspose"

[[node]]
id = "IsLDM.eq_of_isHermitian"

[[node]]
id = "exists_isLDM_conjTranspose_of_isHermitian"

[[node]]
id = "IsLDM.posDef_iff"

[[node]]
id = "IsLDM.diag_pos_of_forall_det_pos"

[[node]]
id = "exists_isLDM_conjTranspose_of_posDef"

[[node]]
id = "posDef_iff_forall_det_leadingPrincipalSubmatrix_pos"

[[node]]
id = "posDef_iff_forall_principalSubmatrix_eigenvalues_pos"

[[node]]
id = "IsCholesky"

[[node]]
id = "IsCholesky.diag_ne_zero"

[[node]]
id = "IsCholesky.star_diag"

[[node]]
id = "IsCholesky.coe_re_diag"

[[node]]
id = "IsCholesky.isUnit"

[[node]]
id = "IsCholesky.posDef"

[[node]]
id = "IsCholesky.isHermitian"

[[node]]
id = "IsCholesky.apply_eq_sum"

[[node]]
id = "IsCholesky.star_apply_mul_diag_eq"

[[node]]
id = "IsCholesky.re_diag_eq_sqrt"

[[node]]
id = "IsCholesky.isLU"

[[node]]
id = "IsCholesky.unique"

[[node]]
id = "exists_isCholesky"

[[node]]
id = "existsUnique_isCholesky"

[[node]]
id = "posDef_iff_exists_isUnit_conjTranspose_mul_self"

[[node]]
id = "choleskyAux"

[[node]]
id = "cholesky"

[[node]]
id = "cholesky_apply_of_lt"

[[node]]
id = "cholesky_apply_self"

[[node]]
id = "cholesky_apply_of_gt"

[[node]]
id = "isLowerTriangular_cholesky"

[[node]]
id = "cholesky_eq_of_isCholesky"

[[node]]
id = "isCholesky_cholesky"

[[node]]
id = "cholesky_conjTranspose_eq_of_isCholesky"

[[node]]
id = "isCholesky_conjTranspose_mul_self_of_qr"

[[node]]
id = "cholesky_conjTranspose_mul_self_of_qr"

[[node]]
id = "LDL.lowerInv_apply_self"

[[node]]
id = "LDL.lowerInv_isUnitLowerTriangular"

[[node]]
id = "LDL.lower_isUnitLowerTriangular"

[[node]]
id = "LDL.diagEntries_pos"

[[node]]
id = "isLDM_ldl"

[[node]]
id = "LDL.lower_eq_of_isLDM"
