namespace = "Matrix"

[[node]]
id = "complexSpectralRadius"

[[node]]
id = "complexSpectralRadius_le_linfty_opNNNorm"

[[node]]
id = "complexSpectralRadius_le_of_norm"

[[node]]
id = "complexSpectralRadius_ne_top"

[[node]]
id = "complexSpectralRadius_smul"

[[node]]
id = "complexify"

[[node]]
id = "det_complexify"

[[node]]
id = "isUnit_complexify_iff"

[[node]]
id = "isUnit_one_sub_of_complexSpectralRadius_lt_one"

[[node]]
id = "mem_spectrum_complexify_iff"

[[node]]
id = "ofReal_mem_spectrum_complexify_iff"

[[node]]
id = "tendsto_pow_iff_complexSpectralRadius_lt_one"

[[node]]
id = "l2_opNorm_complexify"
source = "Saad, Iterative Methods for Sparse Linear Systems, Section 4.2.1"

[[node]]
id = "linfty_opNorm_complexify"

[[node]]
id = "frobenius_norm_complexify"

[[node]]
id = "tendsto_pow_of_algebraNorm_lt_one"
source = "Saad, Iterative Methods for Sparse Linear Systems, Corollary 4.2"

[[node]]
id = "tendsto_pow_rpow_complexSpectralRadius"
source = "Saad, Iterative Methods for Sparse Linear Systems, Section 4.2.1"

[[node]]
id = "limsup_norm_pow_mulVec_rpow_le"
source = "Saad, Iterative Methods for Sparse Linear Systems, Section 4.2.1"

[[node]]
id = "exists_limsup_norm_pow_mulVec_rpow_eq"
source = "Saad, Iterative Methods for Sparse Linear Systems, Section 4.2.1"
