namespace = "Matrix"

[[node]]
id = "IsThinCSD"

[[node]]
id = "exists_isThinCSD"

[[node]]
id = "IsCSD"

[[node]]
id = "exists_isCSD"

[[node]]
id = "l2_opNorm_toBlocks₂₁_eq_toBlocks₁₂"

[[node]]
id = "csdUpperRight"

[[node]]
id = "IsCSD.isThinCSD"
