namespace = "Matrix"

[[node]]
id = "IsTridiagonal"

[[node]]
id = "IsTridiagonal.isUpperHessenberg"

[[node]]
id = "IsUpperHessenberg"

[[node]]
id = "IsUpperHessenbergRect"

[[node]]
id = "diagPart"

[[node]]
id = "diagPart_add_strictLower_add_strictUpper"

[[node]]
id = "diagPart_sub_neg_strictLower_sub_neg_strictUpper"

[[node]]
id = "isUnit_diagPart_iff"

[[node]]
id = "strictLower"

[[node]]
id = "strictLower_blockTriangular"

[[node]]
id = "strictUpper"

[[node]]
id = "strictUpper_blockTriangular"

[[node]]
id = "hasLowerBandwidth_zero_iff"

[[node]]
id = "hasUpperBandwidth_zero_iff"

[[node]]
id = "isDiag_iff_hasBandwidth_zero"

[[node]]
id = "hasLowerBandwidth_iff_fin"

[[node]]
id = "HasLowerBandwidth.add"

[[node]]
id = "BlockTriangular.mul_apply_self_of_injective"

[[node]]
id = "IsUnitLowerTriangular"

[[node]]
id = "IsUnitLowerTriangular.mul"

[[node]]
id = "IsUnitLowerTriangular.det_eq_one"

[[node]]
id = "IsUnitLowerTriangular.isUnit"

[[node]]
id = "IsUnitLowerTriangular.inv"

[[node]]
id = "tridiagonalOf"

[[node]]
id = "isTridiagonal_tridiagonalOf"

[[node]]
id = "tridiagonalOf_transpose"

[[node]]
id = "tridiagonalOf_mulVec"

[[node]]
id = "HasLowerBandwidth"

[[node]]
id = "HasUpperBandwidth"

[[node]]
id = "isTridiagonal_iff_hasBandwidth_one"

[[node]]
id = "isUpperHessenberg_iff_hasLowerBandwidth_one"

[[node]]
id = "HasLowerBandwidth.mul"

[[node]]
id = "HasUpperBandwidth.mul"

[[node]]
id = "IsUpperTriangular.mul_isUpperHessenberg"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 5.6.4'

[[node]]
id = "IsUpperHessenberg.mul_isUpperTriangular"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 5.6.3'

[[node]]
id = "IsUpperHessenberg.add_smul_one"

[[node]]
id = "IsUpperHessenberg.sub_smul_one"

[[node]]
id = "IsUpperHessenberg.isTridiagonal_of_isHermitian"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Remark 5.4'

[[node]]
id = "IsUpperHessenberg.isTridiagonal_of_isSymm"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Remark 5.4'

[[node]]
id = "IsUpperBidiagonal"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.57)'

[[node]]
id = "IsLowerBidiagonal"

[[node]]
id = "IsUpperTriangular.inv"

[[node]]
id = "IsLowerTriangular.inv"

[[node]]
id = "charpoly_of_isLowerTriangular"

[[node]]
id = "strictLower_transpose"

[[node]]
id = "strictUpper_transpose"

[[node]]
id = "diagPart_transpose"

[[node]]
id = "diagPart_mulVec_apply"

[[node]]
id = "strictLower_mulVec_apply"

[[node]]
id = "strictUpper_mulVec_apply"

[[node]]
id = "mulVec_apply_eq_add_sum_erase"

[[node]]
id = "mul_apply_eq_zero_of_lt"

[[node]]
id = "isUpperHessenberg_iff_fin"
