namespace = "Matrix"

[[node]]
id = "mulVec_nonsing_inv_mulVec"

[[node]]
id = "nonsing_inv_mulVec_mulVec"

[[node]]
id = "nonsing_inv_mulVec_eq"

[[node]]
id = "add_mul_mul_mul_inv_eq_sub_of_isUnit_one_add"
source = "Quarteroni–Sacco–Saleri, Numerical Mathematics, (3.57)"

[[node]]
id = "inv_add_vecMulVec"
source = "Quarteroni–Sacco–Saleri, Numerical Mathematics, (3.57) and §7.2.7"

[[node]]
id = "isUnit_add_vecMulVec"
