namespace = "Matrix"

[[node]]
id = "EntrywiseLE"

[[node]]
id = "EntrywiseNonneg"

[[node]]
id = "abs"

[[node]]
id = "abs_mul_entrywiseLE"

[[node]]
id = "abs_mulVec_le"

[[node]]
id = "EntrywiseLE.mul_of_entrywiseNonneg_left"

[[node]]
id = "EntrywiseLE.mul_of_entrywiseNonneg_right"

[[node]]
id = "EntrywiseNonneg.mul"

[[node]]
id = "EntrywiseNonneg.pow"

[[node]]
id = "EntrywiseNonneg.mulVec_nonneg"
