namespace = "Matrix"

[[node]]
id = "planeEmbed"

[[node]]
id = "planeEmbed_apply"

[[node]]
id = "planeEmbed_apply_of_ne_left"

[[node]]
id = "planeEmbed_apply_of_ne_right"

[[node]]
id = "planeEmbed_apply_vecCons"

[[node]]
id = "planeEmbed_injective"

[[node]]
id = "planeEmbed_eq_one_iff"

[[node]]
id = "planeRotation"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.43)'

[[node]]
id = "planeRotation_apply"

[[node]]
id = "planeRotation_transpose"

[[node]]
id = "mul_planeRotation_apply"

[[node]]
id = "transpose_planeRotation_mul_apply"

[[node]]
id = "transpose_planeRotation_mulVec_apply"

[[node]]
id = "transpose_planeRotation_mul_self"

[[node]]
id = "conj_planeRotation_apply_of_ne"

[[node]]
id = "conj_planeRotation_apply_jj"

[[node]]
id = "conj_planeRotation_apply_kk"

[[node]]
id = "conj_planeRotation_apply_jk"

[[node]]
id = "conj_planeRotation_apply_col_j"

[[node]]
id = "conj_planeRotation_apply_col_k"

[[node]]
id = "conj_planeRotation_apply_row_j"

[[node]]
id = "conj_planeRotation_apply_row_k"

[[node]]
id = "mul_planeEmbed_apply"

[[node]]
id = "planeEmbed_mul_apply"

[[node]]
id = "planeEmbed_mul_planeEmbed"

[[node]]
id = "planeEmbed_one"

[[node]]
id = "planeEmbed_transpose"

[[node]]
id = "planeEmbed_conjTranspose"

[[node]]
id = "det_planeEmbed"

[[node]]
id = "planeEmbed_mem_unitaryGroup_iff"

[[node]]
id = "planeRotation_mem_orthogonalGroup"

[[node]]
id = "givensPair"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.51)'

[[node]]
id = "givensPair_of_not"

[[node]]
id = "givensPair_zero_zero"

[[node]]
id = "givensPair_sq_add_sq"

[[node]]
id = "givensPair_fst_mul_add_snd_mul"

[[node]]
id = "transpose_planeRotation_givensPair_mulVec"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.44)'

[[node]]
id = "planeEmbed_mulVec_apply"

[[node]]
id = "planeEmbed_mulVec_apply_of_ne"

[[node]]
id = "vecMul_planeEmbed_apply"
