namespace = "Matrix"

[[node]]
id = "frobenius_norm_sub_mul_sq"

[[node]]
id = "re_trace_mul_le_trace_of_posSemidef"
deps = []

[[node]]
id = "frobenius_norm_sub_mul_le_of_isPolarDecomposition"

[[node]]
id = "frobenius_norm_sub_mul_le_of_isSVD"

[[node]]
id = "re_trace_mul_le_sum_colSingularValues"

[[node]]
id = "IsPolarDecomposition.trace_eq_sum_colSingularValues"

[[node]]
id = "IsSVD.re_trace_mul_eq_sum"
