namespace = "Matrix"

[[node]]
id = "IsUnreducedUpperHessenberg"

[[node]]
id = "isUnreducedUpperHessenberg_iff_fin"

[[node]]
id = "isUnreducedUpperHessenberg_iff_succ"

[[node]]
id = "IsUnreducedUpperHessenberg.sub_smul_one"

[[node]]
id = "IsUnreducedUpperHessenberg.map"

[[node]]
id = "IsUnreducedUpperHessenberg.linearIndependent_init_cols"

[[node]]
id = "IsUnreducedUpperHessenberg.finrank_eigenspace_le_one"

[[node]]
id = "IsUnreducedUpperHessenberg.finrank_eigenspace_eq_one"

[[node]]
id = "krylovMatrix"

[[node]]
id = "aeval_mul_krylovMatrix"

[[node]]
id = "conj_pow_of_mem_unitaryGroup"

[[node]]
id = "conjTranspose_mul_krylovMatrix"

[[node]]
id = "IsUpperHessenberg.isUpperTriangular_krylovMatrix"

[[node]]
id = "IsUpperHessenberg.krylovMatrix_succ_succ"

[[node]]
id = "IsUnreducedUpperHessenberg.isUnit_krylovMatrix"

[[node]]
id = "isUnreducedUpperHessenberg_iff_krylovMatrix"

[[node]]
id = "isUnreducedUpperHessenberg_conj_iff_krylovMatrix"

[[node]]
id = "IsUnreducedUpperHessenberg.mul_mul_inv_of_isUpperTriangular"

[[node]]
id = "IsUnreducedUpperHessenberg.isUpperTriangular_star_mul_aeval"
