[[node]]
id = "Matrix.backwardGaussSeidelSplitting"

[[node]]
id = "Matrix.gaussSeidelSplitting"

[[node]]
id = "Matrix.gaussSeidelSplitting_n"

[[node]]
id = "Matrix.isUnit_diagPart_add_strictLower"

[[node]]
id = "Matrix.jacobiSplitting"

[[node]]
id = "Matrix.jacobiSplitting_iterationOperator"

[[node]]
id = "Matrix.sorSplitting"

[[node]]
id = "Matrix.sorSplitting_iterationOperator"

[[node]]
id = "Matrix.sorSplitting_one"

[[node]]
id = "Matrix.ssorSplitting"

[[node]]
id = "Stationary.Splitting.eq_iterationOperator_mul_add_iff"

[[node]]
id = "Stationary.Splitting.iterationOperator"

[[node]]
id = "Stationary.Splitting.iterationOperator_eq"

[[node]]
id = "Stationary.Splitting.m_sub_n"

[[node]]
id = "Stationary.Splitting.n"

[[node]]
id = "Stationary.Splitting.one_sub_iterationOperator"

[[node]]
id = "Stationary.Splitting.richardson"

[[node]]
id = "Stationary.Splitting.richardson_iterationOperator"

[[node]]
id = "Stationary.Splitting"

[[node]]
id = "Matrix.complexify_jacobi_iterationOperator"

[[node]]
id = "Matrix.complexify_gaussSeidel_iterationOperator"

[[node]]
id = "Matrix.backwardSorSplitting"

[[node]]
id = "Matrix.backwardSorSplitting_iterationOperator"

[[node]]
id = "Matrix.backwardSorSplitting_one"

[[node]]
id = "Matrix.sorSplitting_m_add_backwardSorSplitting_m_sub"

[[node]]
id = "Matrix.ringInverse_ssorSplitting_m"

[[node]]
id = "Matrix.ssorSplitting_iterationOperator_eq_mul"

[[node]]
id = "Matrix.ssorSplitting_one_m"

[[node]]
id = "Stationary.Splitting.iterationOperator_eq_mul_of_inverse_m_eq"

[[node]]
id = "Stationary.Splitting.inverse_m_eq_iterationOperator_mul_inverse_add"

[[node]]
id = "Matrix.isUnit_smul_diagPart_add_smul_strictLower"

[[node]]
id = "Matrix.isUnit_smul_diagPart_add_smul_strictUpper"

[[node]]
id = "Matrix.isUnit_diagPart_add_smul_strictLower"

[[node]]
id = "Matrix.isUnit_diagPart_add_smul_strictUpper"

[[node]]
id = "Matrix.isUnit_diagPart_add_strictUpper"

[[node]]
id = "Matrix.jorSplitting"

[[node]]
id = "Matrix.jorSplitting_iterationOperator"

[[node]]
id = "Matrix.jorSplitting_one"

[[node]]
id = "Matrix.jorSplitting_iterationOperator_eq_one_sub"

[[node]]
id = "Stationary.Splitting.map"

[[node]]
id = "Stationary.Splitting.map_iterationOperator"

[[node]]
id = "Stationary.Splitting.complexify"

[[node]]
id = "Stationary.Splitting.complexify_iterationOperator"

[[node]]
id = "Stationary.Splitting.complexSpectralRadius_iterationOperator"

[[node]]
id = "Matrix.complexify_sor_iterationOperator"
