namespace = "EulerMaclaurin"

[[node]]
id = "integral_bernoulliFun_mul_eq"

[[node]]
id = "integral_eq_sub_sum_sub_integral"

[[node]]
id = "bernoulliFun_sub_bernoulli_sign"

[[node]]
id = "integral_bernoulliFun_sub_bernoulli"

[[node]]
id = "neg_one_pow_mul_bernoulli_pos"

[[node]]
id = "exists_integral_eq_mul"

[[node]]
id = "exists_integral_eq_of_contDiffOn"

[[node]]
id = "trapezoidSum_eq_integral_add_sum_add_mul"

[[node]]
id = "_root_.bernoulli_eq_tsum_two_div_pow"
