import Numlib.Analysis.Fourier.FourierIntegral
import Numlib.Analysis.Wavelet.Multiresolution

/-!
# The continuous wavelet transform

The family of **wavelets** generated from an elementary wavelet `h : ℝ → ℂ` by dilation and
translation,

`h_{s,τ}(t) = s^{-1/2} h((t − τ)/s)`, `s > 0`, `τ ∈ ℝ`,

its Fourier transform `𝓕 h_{s,τ}(ν) = √s 𝓕h(sν) e^{−2πiντ}` — the *filter* of the wavelet
transform — the **continuous wavelet transform** `W_f(s, τ) = ∫ f conj (h_{s,τ}) = ⟪h_{s,τ}, f⟫`
of `f ∈ L²(ℝ)`, its expression on the Fourier side through Plancherel, and the **discrete
wavelets** `h_{j,k}(t) = s₀^{−j/2} h(s₀^{−j} t − k τ₀)` obtained by sampling the scale
logarithmically and the shift proportionally to the scale, with the identification, at the dyadic
parameters `s₀ = 2`, `τ₀ = 1`, with the system `waveletSystem ψ j' k = 2^{j'/2} ψ(2^{j'} x − k)` of
`Numlib/Analysis/Wavelet/Multiresolution` under the index reversal `j' = −j`. The material is
[quarteroni2000numerical] §10.12 (Definition 10.4, (10.85)–(10.87) and §10.12.2); the existing
wavelet modules start from the dyadic case because [han2009theoretical] §4.4–4.5 state only that.

## Main definitions

* `Wavelet.dilateTranslate h s τ` — the wavelet `h_{s,τ}`; it is in `L²` with the same `L²` norm
  as `h` (`memLp_dilateTranslate`, `eLpNorm_dilateTranslate`) and integrable when `h` is
  (`integrable_dilateTranslate`).
* `Wavelet.continuousTransform h f s τ` — the continuous wavelet transform `W_f(s, τ)`, the `L²`
  inner product `⟪h_{s,τ}, f⟫` in Mathlib's convention (`continuousTransform_eq_inner`).
* `Wavelet.discrete h s₀ τ₀ j k` and `Wavelet.discreteTransform h s₀ τ₀ f j k` — the discrete
  wavelets and the discrete wavelet transform.

## Main statements

* `Wavelet.fourier_dilateTranslate` — the filter (10.86), from the translation and scaling rules
  of `Numlib/Analysis/Fourier/FourierIntegral`.
* `Wavelet.continuousTransform_eq_integral_fourier` — the transform as a bank of filters,
  `W_f(s, τ) = √s ∫ 𝓕f(ν) conj (𝓕h(sν)) e^{2πiντ} dν` for `f, h ∈ L¹ ∩ L²`; Plancherel on
  `L¹ ∩ L²` (`Real.integral_conj_fourier_mul_fourier`) followed by the filter identity.
* `Wavelet.discrete_two_one_ae_eq_scalingSystem`, `Wavelet.discrete_two_one_eq_waveletSystem` —
  at `s₀ = 2`, `τ₀ = 1` the discrete wavelets of an `L²` function `ψ` are the dyadic system
  `scalingSystem ψ (−j) k`, and for `ψ = mraWavelet φ` the `waveletSystem φ (−j) k` of a
  multiresolution analysis, almost everywhere.

## Not here

The inversion formula of the continuous wavelet transform (Calderón's admissibility condition
`∫ |𝓕h(ν)|²/|ν| dν < ∞` and `f = C_h⁻¹ ∫∫ W_f(s,τ) h_{s,τ} ds dτ/s²`), which the textbook does not
state either, and the Heisenberg uncertainty inequality, absent from Mathlib. The orthonormality
and reconstruction theorems for the dyadic system are `IsMultiresolutionAnalysis.
orthonormal_waveletSystem_prod` and `IsMultiresolutionAnalysis.hasSum_inner_smul_waveletSystem` of
`Multiresolution`. Dilation as a unitary of the real `L²(ℝ)` is `MeasureTheory.Lp.dilationₗᵢ` of
`Numlib/Analysis/Wavelet/Haar` and translation `MeasureTheory.Lp.translationₗᵢ` of
`Multiresolution`; the pointwise family here is what those act on when `h` is given as a
function, and `discrete_two_one_ae_eq_scalingSystem` is the dictionary.
-/

open MeasureTheory Filter Topology Complex

open scoped FourierTransform ComplexConjugate Real ENNReal

namespace Wavelet

/-! ### Dilations and translations of an elementary wavelet -/

/-- **The wavelet `h_{s,τ}`** ([quarteroni2000numerical] (10.85)) obtained from the elementary
wavelet `h : ℝ → ℂ` by the dilation with scale `s` and the translation by `τ`:
`h_{s,τ}(t) = s^{-1/2} h((t − τ)/s)`. Meaningful for `s > 0`, where the factor `s^{-1/2}` keeps
the `L²` norm (`eLpNorm_dilateTranslate`). -/
noncomputable def dilateTranslate (h : ℝ → ℂ) (s τ : ℝ) : ℝ → ℂ :=
  fun t => (Real.sqrt s : ℂ)⁻¹ * h ((t - τ) / s)

theorem dilateTranslate_apply (h : ℝ → ℂ) (s τ t : ℝ) :
    dilateTranslate h s τ t = (Real.sqrt s : ℂ)⁻¹ * h ((t - τ) / s) := rfl

/-- The affine change of variables `t ↦ (t − τ) / s`, `s > 0`, scales Lebesgue measure by `s`. -/
theorem map_volume_sub_div {s : ℝ} (hs : 0 < s) (τ : ℝ) :
    Measure.map (fun t : ℝ => (t - τ) / s) volume = ENNReal.ofReal s • volume := by
  have hfun : (fun t : ℝ => (t - τ) / s) = (fun u : ℝ => s⁻¹ * u) ∘ fun t : ℝ => t - τ := by
    funext t
    simp [div_eq_inv_mul]
  rw [hfun, ← Measure.map_map (measurable_const_mul _) (measurable_sub_const _),
    map_sub_right_eq_self, Real.map_volume_mul_left (inv_ne_zero hs.ne'), inv_inv, abs_of_pos hs]

theorem aemeasurable_sub_div (s τ : ℝ) : AEMeasurable (fun t : ℝ => (t - τ) / s) volume :=
  ((measurable_sub_const τ).div_const s).aemeasurable

/-- A wavelet of scale `s > 0` generated by an `L²` elementary wavelet is in `L²`. -/
theorem memLp_dilateTranslate {h : ℝ → ℂ} (hh : MemLp h 2) {s : ℝ} (hs : 0 < s) (τ : ℝ) :
    MemLp (dilateTranslate h s τ) 2 := by
  have h1 : MemLp h 2 (Measure.map (fun t : ℝ => (t - τ) / s) volume) := by
    rw [map_volume_sub_div hs]
    exact hh.smul_measure ENNReal.ofReal_ne_top
  exact ((memLp_map_measure_iff h1.aestronglyMeasurable (aemeasurable_sub_div s τ)).mp
    h1).const_mul _

/-- **The normalization of the wavelets**: `h_{s,τ}` has the `L²` norm of `h`, which is what the
factor `s^{-1/2}` is for. -/
theorem eLpNorm_dilateTranslate {h : ℝ → ℂ} (hh : AEStronglyMeasurable h volume) {s : ℝ}
    (hs : 0 < s) (τ : ℝ) : eLpNorm (dilateTranslate h s τ) 2 volume = eLpNorm h 2 volume := by
  have hsq : (0 : ℝ) < Real.sqrt s := Real.sqrt_pos.mpr hs
  have hmap := map_volume_sub_div hs τ
  have hh' : AEStronglyMeasurable h (Measure.map (fun t : ℝ => (t - τ) / s) volume) := by
    rw [hmap]
    exact hh.mono_ac Measure.smul_absolutelyContinuous
  have h1 := eLpNorm_map_measure (p := 2) hh' (aemeasurable_sub_div s τ)
  rw [hmap, eLpNorm_smul_measure_of_ne_top (by norm_num) _ _ hh] at h1
  have h2 : dilateTranslate h s τ = ((Real.sqrt s : ℂ)⁻¹) • (h ∘ fun t => (t - τ) / s) := by
    funext t
    simp [dilateTranslate_apply]
  rw [h2, eLpNorm_const_smul, ← h1, smul_eq_mul, ← mul_assoc]
  have h3 : ‖((Real.sqrt s : ℂ)⁻¹)‖ₑ * ENNReal.ofReal s ^ ((1 : ℝ≥0∞) / 2).toReal = 1 := by
    rw [enorm_inv (by exact_mod_cast hsq.ne'), ← ofReal_norm, Complex.norm_real,
      Real.norm_eq_abs, abs_of_pos hsq, show ((1 : ℝ≥0∞) / 2).toReal = (1 / 2 : ℝ) by simp,
      ENNReal.ofReal_rpow_of_nonneg hs.le (by norm_num), ← Real.sqrt_eq_rpow,
      ← ENNReal.ofReal_inv_of_pos hsq, ← ENNReal.ofReal_mul (inv_nonneg.mpr hsq.le),
      inv_mul_cancel₀ hsq.ne', ENNReal.ofReal_one]
  rw [h3, one_mul]

/-- A wavelet generated by an integrable elementary wavelet is integrable. -/
theorem integrable_dilateTranslate {h : ℝ → ℂ} (hh : Integrable h) {s : ℝ} (hs : s ≠ 0)
    (τ : ℝ) : Integrable (dilateTranslate h s τ) :=
  ((hh.comp_div hs).comp_sub_right τ).const_mul _

/-- **The filter of the wavelet transform** ([quarteroni2000numerical] (10.86)): the Fourier
transform of `h_{s,τ}` is `𝓕 h_{s,τ}(ν) = √s 𝓕h(sν) e^{−2πiντ}` — the textbook's
`H_{s,τ}(ω) = √s H(sω) e^{−iωτ}` in the variable `ω = 2πν`. A dilation by `s` in time is a
contraction by `s` in frequency, so `1/s` plays the role of a frequency. The translation and
scaling rules `Real.fourierIntegral_comp_sub_right` and `Real.fourierIntegral_comp_mul_left`; no
integrability is needed, the identity holding with both sides `0` otherwise. -/
theorem fourier_dilateTranslate {h : ℝ → ℂ} {s : ℝ} (hs : 0 < s) (τ ν : ℝ) :
    𝓕 (dilateTranslate h s τ) ν
      = Real.sqrt s * 𝓕 h (s * ν) * Complex.exp (-(2 * π * ν * τ) * I) := by
  have hsq : (0 : ℝ) < Real.sqrt s := Real.sqrt_pos.mpr hs
  have h1 : dilateTranslate h s τ
      = fun t => ((Real.sqrt s : ℂ)⁻¹) • (fun v : ℝ => (fun u : ℝ => h (s⁻¹ * u)) (v - τ)) t := by
    funext t
    simp only [dilateTranslate_apply, smul_eq_mul, div_eq_inv_mul]
  rw [h1, Real.fourierIntegral_const_smul,
    Real.fourierIntegral_comp_sub_right (fun u : ℝ => h (s⁻¹ * u)) τ ν,
    Real.fourierIntegral_comp_mul_left (inv_ne_zero hs.ne'), abs_inv, inv_inv, div_inv_eq_mul,
    abs_of_pos hs]
  simp only [smul_eq_mul, Circle.smul_def, Real.fourierChar_apply, Complex.real_smul]
  have hs' : (Real.sqrt s : ℂ) * Real.sqrt s = s := by
    rw [← Complex.ofReal_mul, Real.mul_self_sqrt hs.le]
  rw [mul_comm ν s]
  have hexp : Complex.exp (↑(2 * π * -(τ * ν)) * I) = Complex.exp (-(2 * π * ν * τ) * I) := by
    congr 1
    push_cast
    ring
  rw [hexp]
  have hsqC : (Real.sqrt s : ℂ) ≠ 0 := by exact_mod_cast hsq.ne'
  field_simp
  rw [← hs']
  ring

/-! ### The continuous wavelet transform -/

/-- **The continuous wavelet transform** ([quarteroni2000numerical] Definition 10.4, (10.87)) of
`f` with respect to the elementary wavelet `h`:

`W_f(s, τ) = ∫ f(t) conj (h_{s,τ}(t)) dt`,

a function of the scale `s` and the time shift `τ`, the *time-scale representation* of `f`. For
`f, h ∈ L²` it is the inner product `⟪h_{s,τ}, f⟫` of `L²` in Mathlib's convention, conjugate-linear
in the first argument (`continuousTransform_eq_inner`). -/
noncomputable def continuousTransform (h f : ℝ → ℂ) (s τ : ℝ) : ℂ :=
  ∫ t, f t * conj (dilateTranslate h s τ t)

theorem continuousTransform_def (h f : ℝ → ℂ) (s τ : ℝ) :
    continuousTransform h f s τ = ∫ t, f t * conj (dilateTranslate h s τ t) := rfl

/-- For `f, h ∈ L²` and `s > 0`, the wavelet transform is the `L²` inner product `⟪h_{s,τ}, f⟫`. -/
theorem continuousTransform_eq_inner {h f : ℝ → ℂ} (hh : MemLp h 2) (hf : MemLp f 2) {s : ℝ}
    (hs : 0 < s) (τ : ℝ) :
    continuousTransform h f s τ
      = inner ℂ ((memLp_dilateTranslate hh hs τ).toLp _) (hf.toLp f) := by
  rw [L2.inner_def, continuousTransform_def]
  refine integral_congr_ae ?_
  filter_upwards [(memLp_dilateTranslate hh hs τ).coeFn_toLp, hf.coeFn_toLp] with t h1 h2
  rw [RCLike.inner_apply', h1, h2, mul_comm]

/-- **The wavelet transform as a bank of filters** ([quarteroni2000numerical] §10.12.1, the
Fourier-side form of (10.87)): for `f, h ∈ L¹ ∩ L²` and `s > 0`,

`W_f(s, τ) = √s ∫ 𝓕f(ν) conj (𝓕h(sν)) e^{2πiντ} dν`,

the textbook's `(√s/2π) ∫ F(ω) conj (H(sω)) e^{iωτ} dω` in the variable `ω = 2πν`. Plancherel's
identity on `L¹ ∩ L²` (`Real.integral_conj_fourier_mul_fourier`) applied to `h_{s,τ}` and `f`,
followed by the filter identity `fourier_dilateTranslate`. -/
theorem continuousTransform_eq_integral_fourier {h f : ℝ → ℂ} (hh1 : MemLp h 1) (hh2 : MemLp h 2)
    (hf1 : MemLp f 1) (hf2 : MemLp f 2) {s : ℝ} (hs : 0 < s) (τ : ℝ) :
    continuousTransform h f s τ
      = Real.sqrt s * ∫ ν, 𝓕 f ν * conj (𝓕 h (s * ν)) * Complex.exp ((2 * π * ν * τ) * I) := by
  have hd1 : MemLp (dilateTranslate h s τ) 1 :=
    memLp_one_iff_integrable.mpr
      (integrable_dilateTranslate (memLp_one_iff_integrable.mp hh1) hs.ne' τ)
  have hd2 : MemLp (dilateTranslate h s τ) 2 := memLp_dilateTranslate hh2 hs τ
  have hpl := Real.integral_conj_fourier_mul_fourier hd1 hd2 hf1 hf2
  rw [continuousTransform_def, ← integral_const_mul]
  rw [show (∫ t, f t * conj (dilateTranslate h s τ t))
      = ∫ t, conj (dilateTranslate h s τ t) * f t from
    integral_congr_ae (Eventually.of_forall fun t => mul_comm _ _), ← hpl]
  refine integral_congr_ae (Eventually.of_forall fun ν => ?_)
  simp only
  rw [fourier_dilateTranslate hs, map_mul, map_mul, Complex.conj_ofReal, ← Complex.exp_conj]
  simp only [map_mul, map_neg, map_ofNat, Complex.conj_ofReal, Complex.conj_I]
  ring_nf

/-! ### Discrete wavelets -/

/-- **The discrete wavelets** ([quarteroni2000numerical] §10.12.2): for a scale step `s₀ > 1` and
a shift step `τ₀`, the wavelet of scale `s = s₀^j` and shift `τ = k τ₀ s₀^j`,

`h_{j,k}(t) = s₀^{−j/2} h(s₀^{−j}(t − k τ₀ s₀^j)) = s₀^{−j/2} h(s₀^{−j} t − k τ₀)`,

`j, k : ℤ`; the shift step is proportional to the scale, so that the wavelets of small scale
(large negative `j`) are concentrated and finely spaced. The second form is `discrete_apply`. -/
noncomputable def discrete (h : ℝ → ℂ) (s₀ τ₀ : ℝ) (j k : ℤ) : ℝ → ℂ :=
  dilateTranslate h (s₀ ^ j) (k * τ₀ * s₀ ^ j)

theorem discrete_def (h : ℝ → ℂ) (s₀ τ₀ : ℝ) (j k : ℤ) :
    discrete h s₀ τ₀ j k = dilateTranslate h (s₀ ^ j) (k * τ₀ * s₀ ^ j) := rfl

/-- The discrete wavelet in the textbook's second form, `s₀^{−j/2} h(s₀^{−j} t − k τ₀)`. -/
theorem discrete_apply (h : ℝ → ℂ) {s₀ : ℝ} (hs₀ : 0 < s₀) (τ₀ : ℝ) (j k : ℤ) (t : ℝ) :
    discrete h s₀ τ₀ j k t = (Real.sqrt (s₀ ^ j) : ℂ)⁻¹ * h (s₀ ^ (-j) * t - k * τ₀) := by
  rw [discrete_def, dilateTranslate_apply]
  congr 2
  have : s₀ ^ j ≠ 0 := zpow_ne_zero j hs₀.ne'
  rw [zpow_neg]
  field_simp

/-- **The discrete wavelet transform** ([quarteroni2000numerical] §10.12.2):
`W_f(j, k) = ∫ f(t) conj (h_{j,k}(t)) dt`, the continuous transform sampled at the discrete
scales and shifts (`discreteTransform_eq_continuousTransform`). The textbook writes `f ∈ L¹(ℝ)`;
the natural domain is `L²(ℝ)`, where it is the inner product `⟪h_{j,k}, f⟫`. -/
noncomputable def discreteTransform (h : ℝ → ℂ) (s₀ τ₀ : ℝ) (f : ℝ → ℂ) (j k : ℤ) : ℂ :=
  ∫ t, f t * conj (discrete h s₀ τ₀ j k t)

theorem discreteTransform_eq_continuousTransform (h : ℝ → ℂ) (s₀ τ₀ : ℝ) (f : ℝ → ℂ) (j k : ℤ) :
    discreteTransform h s₀ τ₀ f j k = continuousTransform h f (s₀ ^ j) (k * τ₀ * s₀ ^ j) := rfl

open MeasureTheory.Lp in
/-- **The dyadic discrete wavelets are the dyadic system of `Multiresolution`**: for a real `L²`
function `ψ` and the parameters `s₀ = 2`, `τ₀ = 1`, the discrete wavelet `h_{j,k}` of `ψ` is,
almost everywhere, the function `2^{−j/2} ψ(2^{−j} t − k)` underlying `scalingSystem ψ (−j) k` —
the level index is reversed between the two conventions, the textbook's scale `2^j` being the
level `−j` of a multiresolution analysis. Unfolding `MeasureTheory.Lp.dilationₗᵢ` and
`MeasureTheory.Lp.translationₗᵢ` on representatives. -/
theorem discrete_two_one_ae_eq_scalingSystem (ψ : Lp ℝ 2 (volume : Measure ℝ)) (j k : ℤ) :
    discrete (fun t => ((ψ : ℝ → ℝ) t : ℂ)) 2 1 j k
      =ᵐ[volume] fun t => ((scalingSystem ψ (-j) k : ℝ → ℝ) t : ℂ) := by
  have hc : ((2 : ℝ) ^ (-j)) ≠ 0 := zpow_ne_zero _ two_ne_zero
  have hd := dilationₗᵢ_apply ((2 : ℝ) ^ (-j)) hc (translates ψ k)
  have ht := ae_comp_const_mul hc (translationₗᵢ_apply (-(k : ℝ)) ψ)
  filter_upwards [hd, ht] with t hdt htt
  rw [scalingSystem, hdt]
  simp only [translates] at htt ⊢
  rw [htt, discrete_apply _ two_pos]
  have h2j : (0 : ℝ) < 2 ^ j := zpow_pos two_pos j
  rw [abs_of_pos (zpow_pos two_pos _), ← Real.sqrt_eq_rpow, zpow_neg, Real.sqrt_inv]
  push_cast
  congr 3
  ring

/-- **The dyadic discrete wavelets of a multiresolution analysis** are its `waveletSystem`: for
the wavelet `ψ = mraWavelet φ` of a scaling function `φ`, the discrete wavelets at `s₀ = 2`,
`τ₀ = 1` are `waveletSystem φ (−j) k`, almost everywhere. So the orthonormality
`IsMultiresolutionAnalysis.orthonormal_waveletSystem_prod` and the reconstruction formula
`IsMultiresolutionAnalysis.hasSum_inner_smul_waveletSystem` of `Multiresolution` are the
statements of [quarteroni2000numerical] §10.12.2 about orthonormal wavelet bases. -/
theorem discrete_two_one_eq_waveletSystem (φ : Lp ℝ 2 (volume : Measure ℝ)) (j k : ℤ) :
    discrete (fun t => ((mraWavelet φ : ℝ → ℝ) t : ℂ)) 2 1 j k
      =ᵐ[volume] fun t => ((waveletSystem φ (-j) k : ℝ → ℝ) t : ℂ) :=
  discrete_two_one_ae_eq_scalingSystem (mraWavelet φ) j k

end Wavelet
