import Numlib.Analysis.Wavelet.Haar
import Numlib.Analysis.Wavelet.QuadratureMirror

/-!
# Multiresolution analysis

A *multiresolution analysis* of `L²(ℝ)` is a ladder of closed subspaces `V j`, `j : ℤ`, generated by
the dilates and integer translates of a single *scaling function* `φ`. This module states the
definition as a bundled predicate, derives the orthonormal system of each level and the scaling
equation, constructs the wavelet and proves Mallat's theorem, and shows that the Haar system of
`Numlib/Analysis/Wavelet/Haar` is an instance.

## Main definitions

* `MeasureTheory.Lp.translationₗᵢ a` is translation, `f ↦ (x ↦ f (x + a))`, as a linear isometry of
  `L²(ℝ)`; it is `MeasureTheory.Lp.compMeasurePreservingₗᵢ` along `x ↦ x + a`, which is measure
  preserving. Dilation, which is not measure preserving, is `MeasureTheory.Lp.dilationₗᵢ` of
  `Numlib/Analysis/Wavelet/Haar`.
* `scalingSystem φ j k` is `2 ^ (j / 2) φ (2 ^ j x - k)`, the dilate by `2 ^ j` of the translate of
  `φ` by `k`, and `translates φ k = scalingSystem φ 0 k` up to the identification of the dilation by
  `1` with the identity.
* `IsMultiresolutionAnalysis V φ` is [han2009theoretical] Definition 4.5.1. Two of its clauses
  depart from the book's phrasing, and deliberately. *Shift invariance* is stated as orthonormality
  of the translates together with `V 0` being the closed span of them, rather than as "the
  translates are an orthonormal basis of `V 0`": the two are equivalent, the former is what a
  construction proves, and `Orthonormal.hilbertBasisTopologicalClosure` turns it into a
  `HilbertBasis` on demand. *Scale invariance* is stated as `V j = (V 0).map (dilation (2 ^ j))`
  rather than as the equivalence `f ∈ V j ↔ dilation (2 ^ (-j)) f ∈ V 0`, because that is the form a
  construction proves and the form under which images of spans compute.
* `scalingCoeff φ k = ⟪√2 φ (2 · - k), φ⟫` are the dilation coefficients, `mraWavelet φ` the wavelet
  `ψ = ∑_k (-1)^k p_{1-k} √2 φ(2 · - k)` they define, `waveletSystem φ j k` its dilates and
  translates, and `waveletSpace V j = V_{j+1} ⊖ V_j` the wavelet spaces.

## Main statements

* `IsMultiresolutionAnalysis.orthonormal_scaled` is Proposition 4.5.2: the system of level `j` is
  orthonormal, and with `IsMultiresolutionAnalysis.eq_topologicalClosure_span_scalingSystem` it is a
  Hilbert basis of `V j`.
* `IsMultiresolutionAnalysis.hasSum_scalingEquation` is the scaling equation: `φ` is the sum of its
  level-`1` coefficients against the level-`1` system.
* `IsMultiresolutionAnalysis.hasSum_scalingCoeff_mul` is the necessary condition on those
  coefficients that orthonormality of the translates imposes, `∑_k p_k p_{k - 2l} = δ_{0l}`
  ([han2009theoretical], Exercise 4.5.2).  It rests on `MeasureTheory.Lp.translationₗᵢ_dilationₗᵢ`,
  the commutation of translation with dilation, and on its corollary
  `translationₗᵢ_scalingSystem_one`: a unit translation at level `0` is a translation by two at
  level `1`.  Restated as `IsMultiresolutionAnalysis.isQMFCoeff`, it says that the dilation
  coefficients are a quadrature mirror filter, which is what lets
  `Numlib/Analysis/Wavelet/QuadratureMirror` take over.
* `IsMultiresolutionAnalysis.waveletSpace_eq` and
  `IsMultiresolutionAnalysis.orthonormal_waveletSystem` are **Mallat's theorem** at one level: the
  level-`j` wavelet system is an orthonormal basis of `W_j = V_{j+1} ⊖ V_j`.
  `IsMultiresolutionAnalysis.orthonormal_waveletSystem_prod`,
  `IsMultiresolutionAnalysis.hasSum_inner_smul_waveletSystem` and
  `IsMultiresolutionAnalysis.hilbertBasis` are Mallat's theorem over all levels: the wavelets of all
  levels are an orthonormal basis of `L²(ℝ)`.
* `Haar.isMultiresolutionAnalysis` is the Haar instance. Its scaling coefficients are computed in
  `NumlibSurface.AtkinsonHan.Chapter04.haar_scalingCoeff`, in the surface rather than here, because
  the book states them and nothing in this layer consumes them yet.

## Design note: no Fourier transform

The textbook proof of Mallat's theorem runs on the Fourier side, through the periodisation
`∑_k |φ̂(ξ + 2πk)|² = 1`, the `2π`-periodic symbol `m₀` and the quadrature identity
`|m₀(ξ)|² + |m₀(ξ + π)|² = 1`. None of that is used here. The orthonormality of the two channels is
a finite computation with the coefficient sequence, and the completeness relation
`∑_l (p_{k-2l}² + q_{k-2l}²) = 1` is the splitting of `∑_k p_k² = 1` into the two residue classes
mod `2`; that is `Numlib/Analysis/Wavelet/QuadratureMirror`. What remains — that a vector orthogonal
to every wavelet vanishes — follows from the axioms alone: its orthogonal projections onto the
scaling spaces are all equal, hence lie in `⨅ j, V j = ⊥`, and the density axiom finishes.

What is *not* here is the existence theory: the construction of a scaling function from a prescribed
sequence of dilation coefficients (the cascade iteration, or the infinite product
`φ̂(ξ) = ∏_{j ≥ 1} m₀(2^{-j} ξ)`), and with it Daubechies' compactly supported families. Those do
need the Fourier-side theory of the symbol, and the quadrature mirror condition alone is not
sufficient for them.
-/

open scoped ENNReal

noncomputable section

namespace MeasureTheory.Lp

/-! ### Translation of `L²(ℝ)` -/

/-- Translation of `L²(ℝ)` by `a`: `f ↦ (x ↦ f (x + a))`, a linear isometry, since `x ↦ x + a`
preserves the Lebesgue measure. -/
def translationₗᵢ (a : ℝ) :
    Lp ℝ 2 (volume : Measure ℝ) →ₗᵢ[ℝ] Lp ℝ 2 (volume : Measure ℝ) :=
  compMeasurePreservingₗᵢ ℝ (fun x : ℝ => x + a) (measurePreserving_add_right volume a)

theorem translationₗᵢ_apply (a : ℝ) (f : Lp ℝ 2 (volume : Measure ℝ)) :
    translationₗᵢ a f =ᵐ[volume] fun x => f (x + a) :=
  coeFn_compMeasurePreserving _ _

@[simp]
theorem translationₗᵢ_zero (f : Lp ℝ 2 (volume : Measure ℝ)) : translationₗᵢ 0 f = f := by
  refine Lp.ext ?_
  filter_upwards [translationₗᵢ_apply 0 f] with x hx
  rw [hx, add_zero]

/-- Two translations compose into one. -/
theorem translationₗᵢ_trans (a b : ℝ) (f : Lp ℝ 2 (volume : Measure ℝ)) :
    translationₗᵢ a (translationₗᵢ b f) = translationₗᵢ (b + a) f := by
  refine Lp.ext ?_
  filter_upwards [translationₗᵢ_apply a (translationₗᵢ b f),
    (translationₗᵢ_apply b f).comp_tendsto
      (measurePreserving_add_right volume a).quasiMeasurePreserving.tendsto_ae,
    translationₗᵢ_apply (b + a) f] with x h1 h2 h3
  simp only [Function.comp_apply] at h2
  rw [h1, h3, h2, add_assoc, add_comm a b]

/-- **Translation commutes with dilation**: translating by `a` the dilate by `c` of `f` is the
dilate by `c` of the translate of `f` by `c * a`.  It is what identifies the coefficients of the
dilated scaling equation with the coefficients of the scaling equation reindexed. -/
theorem translationₗᵢ_dilationₗᵢ (a c : ℝ) (hc : c ≠ 0) (f : Lp ℝ 2 (volume : Measure ℝ)) :
    translationₗᵢ a (dilationₗᵢ c hc f) = dilationₗᵢ c hc (translationₗᵢ (c * a) f) := by
  refine Lp.ext ?_
  filter_upwards [translationₗᵢ_apply a (dilationₗᵢ c hc f),
    (dilationₗᵢ_apply c hc f).comp_tendsto
      (measurePreserving_add_right volume a).quasiMeasurePreserving.tendsto_ae,
    dilationₗᵢ_apply c hc (translationₗᵢ (c * a) f),
    ae_comp_const_mul hc (translationₗᵢ_apply (c * a) f)] with x h1 h2 h3 h4
  simp only [Function.comp_apply] at h2
  rw [h1, h2, h3, h4, mul_add]

/-- The translate of `r` times the indicator of `s` is `r` times the indicator of the translated set
`(fun x => x + a) ⁻¹' s`. -/
theorem translationₗᵢ_indicatorConstLp (a : ℝ) {s : Set ℝ} (hs : MeasurableSet s)
    (hμs : volume s ≠ ∞) (r : ℝ) :
    translationₗᵢ a (indicatorConstLp 2 hs hμs r)
      = indicatorConstLp 2 (hs.preimage (measurable_add_const a))
          (by rw [(measurePreserving_add_right volume a).measure_preimage
                hs.nullMeasurableSet]; exact hμs) r := by
  refine Lp.ext ?_
  filter_upwards [translationₗᵢ_apply a (indicatorConstLp 2 hs hμs r),
    (indicatorConstLp_coeFn (p := 2) (hs := hs) (hμs := hμs) (c := r)).comp_tendsto
      (measurePreserving_add_right volume a).quasiMeasurePreserving.tendsto_ae,
    indicatorConstLp_coeFn (p := 2) (hs := hs.preimage (measurable_add_const a))
      (hμs := by rw [(measurePreserving_add_right volume a).measure_preimage
        hs.nullMeasurableSet]; exact hμs) (c := r)] with x hx hx2 hx3
  simp only [Function.comp_apply] at hx2
  rw [hx, hx2, hx3]
  by_cases hxs : x + a ∈ s
  · rw [Set.indicator_of_mem hxs,
      Set.indicator_of_mem (show x ∈ (fun x : ℝ => x + a) ⁻¹' s from hxs)]
  · rw [Set.indicator_of_notMem hxs,
      Set.indicator_of_notMem (show x ∉ (fun x : ℝ => x + a) ⁻¹' s from hxs)]

end MeasureTheory.Lp

open MeasureTheory

/-! ### The system generated by a scaling function -/

/-- The integer translates `φ (· - k)` of a scaling function. -/
def translates (φ : Lp ℝ 2 (volume : Measure ℝ)) (k : ℤ) : Lp ℝ 2 (volume : Measure ℝ) :=
  Lp.translationₗᵢ (-(k : ℝ)) φ

/-- The system generated by a scaling function: `scalingSystem φ j k` is `2 ^ (j / 2) φ (2 ^ j x -
k)`, the dilate by `2 ^ j` of the `k`-th translate of `φ`. -/
def scalingSystem (φ : Lp ℝ 2 (volume : Measure ℝ)) (j k : ℤ) : Lp ℝ 2 (volume : Measure ℝ) :=
  Lp.dilationₗᵢ ((2 : ℝ) ^ j) (zpow_ne_zero j two_ne_zero) (translates φ k)

theorem scalingSystem_eq_dilation (φ : Lp ℝ 2 (volume : Measure ℝ)) (j : ℤ) :
    scalingSystem φ j = ⇑(Lp.dilationₗᵢ ((2 : ℝ) ^ j) (zpow_ne_zero j two_ne_zero)) ∘
      translates φ := rfl

@[simp]
theorem scalingSystem_zero (φ : Lp ℝ 2 (volume : Measure ℝ)) :
    scalingSystem φ 0 = translates φ := by
  funext k
  unfold scalingSystem
  refine Lp.ext ?_
  filter_upwards [Lp.dilationₗᵢ_apply ((2 : ℝ) ^ (0 : ℤ)) (zpow_ne_zero 0 two_ne_zero)
    (translates φ k)] with x hx
  rw [hx, zpow_zero, one_mul, abs_one, Real.one_rpow, one_mul]

@[simp]
theorem translates_zero (φ : Lp ℝ 2 (volume : Measure ℝ)) : translates φ 0 = φ := by
  rw [translates, Int.cast_zero, neg_zero]
  exact Lp.translationₗᵢ_zero φ

/-- **A unit translation at level `0` is a translation by two at level `1`**: translating the
level-one system member `2^{1/2} φ(2 x - k)` by `l` gives `2^{1/2} φ(2 x - (k - 2 l))`.  This is
what makes the coefficients of the dilated scaling equation the sequence `p` of the scaling
equation, reindexed. -/
theorem translationₗᵢ_scalingSystem_one (φ : Lp ℝ 2 (volume : Measure ℝ)) (k l : ℤ) :
    Lp.translationₗᵢ (l : ℝ) (scalingSystem φ 1 k) = scalingSystem φ 1 (k - 2 * l) := by
  have harg : -(k : ℝ) + (2 : ℝ) ^ (1 : ℤ) * (l : ℝ) = -((k - 2 * l : ℤ) : ℝ) := by
    rw [zpow_one]
    push_cast
    ring
  simp only [scalingSystem, translates]
  rw [Lp.translationₗᵢ_dilationₗᵢ, Lp.translationₗᵢ_trans, harg]

/-! ### The definition -/

/-- **A multiresolution analysis of `L²(ℝ)`**: a ladder `V : ℤ → Submodule ℝ (L²(ℝ))` of scaling
spaces generated by the dilates and integer translates of a scaling function `φ`.

The five clauses are shift invariance (here: the translates of `φ` are orthonormal and span `V 0`
densely), scale invariance, nesting, density and separation.

Reference: [han2009theoretical], Definition 4.5.1. -/
structure IsMultiresolutionAnalysis (V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ)))
    (φ : Lp ℝ 2 (volume : Measure ℝ)) : Prop where
  /-- The integer translates of the scaling function are orthonormal. -/
  orthonormal_translates : Orthonormal ℝ (translates φ)
  /-- `V 0` is the closed span of the integer translates of the scaling function. -/
  eq_topologicalClosure_span :
    V 0 = (Submodule.span ℝ (Set.range (translates φ))).topologicalClosure
  /-- Scale invariance: `V j` is the image of `V 0` under the dilation by `2 ^ j`. -/
  eq_map_dilation : ∀ j : ℤ, V j = (V 0).map
    (Lp.dilationₗᵢ ((2 : ℝ) ^ j) (zpow_ne_zero j two_ne_zero)).toLinearEquiv.toLinearMap
  /-- Nesting: each scaling space sits inside the next. -/
  le_succ : ∀ j : ℤ, V j ≤ V (j + 1)
  /-- Density: the union of the scaling spaces is dense in `L²(ℝ)`. -/
  topologicalClosure_iSup : (⨆ j : ℤ, V j).topologicalClosure = ⊤
  /-- Separation: the scaling spaces meet in `0`. -/
  iInf_eq_bot : (⨅ j : ℤ, V j) = ⊥

namespace IsMultiresolutionAnalysis

variable {V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ))} {φ : Lp ℝ 2 (volume : Measure ℝ)}

/-- The image of the closure of a subspace under a surjective linear isometry is the closure of the
image. -/
private theorem map_topologicalClosure
    (D : Lp ℝ 2 (volume : Measure ℝ) ≃ₗᵢ[ℝ] Lp ℝ 2 (volume : Measure ℝ))
    (K : Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ))) :
    K.topologicalClosure.map D.toLinearEquiv.toLinearMap
      = (K.map D.toLinearEquiv.toLinearMap).topologicalClosure := by
  refine SetLike.ext' ?_
  rw [Submodule.map_coe, Submodule.topologicalClosure_coe, Submodule.topologicalClosure_coe,
    Submodule.map_coe]
  exact D.toHomeomorph.image_closure _

/-- **The scaling system of every level is orthonormal.** The level-`j` system is the image of the
level-`0` system under the unitary dilation by `2 ^ j`.

Together with `IsMultiresolutionAnalysis.eq_topologicalClosure_span_scalingSystem` this is
[han2009theoretical] Proposition 4.5.2, that `{2 ^ (j/2) φ (2 ^ j x - k)}` is an orthonormal basis
of `V j`; `IsMultiresolutionAnalysis.hilbertBasis` is that basis.

Reference: [han2009theoretical], Proposition 4.5.2. -/
theorem orthonormal_scaled (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    Orthonormal ℝ (scalingSystem φ j) := by
  rw [scalingSystem_eq_dilation]
  exact h.orthonormal_translates.comp_linearIsometryEquiv _

/-- Each scaling space is the closed span of the scaling system of its level. -/
theorem eq_topologicalClosure_span_scalingSystem (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    V j = (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure := by
  have himg : (Lp.dilationₗᵢ ((2 : ℝ) ^ j)
      (zpow_ne_zero j two_ne_zero)).toLinearEquiv.toLinearMap ''
        Set.range (translates φ) = Set.range (scalingSystem φ j) := by
    rw [← Set.range_comp]
    rfl
  rw [h.eq_map_dilation j, h.eq_topologicalClosure_span, map_topologicalClosure,
    Submodule.map_span, himg]

theorem scalingSystem_mem (h : IsMultiresolutionAnalysis V φ) (j k : ℤ) :
    scalingSystem φ j k ∈ V j := by
  rw [h.eq_topologicalClosure_span_scalingSystem j]
  exact Submodule.le_topologicalClosure _ (Submodule.subset_span (Set.mem_range_self k))

/-- **Every element of `V j` is the sum of its coefficients against the level-`j` scaling system.**
With `IsMultiresolutionAnalysis.orthonormal_scaled` this is the content of [han2009theoretical]
Proposition 4.5.2: the system is an orthonormal basis of `V j`.

Reference: [han2009theoretical], Proposition 4.5.2. -/
theorem hasSum_inner_smul (h : IsMultiresolutionAnalysis V φ) (j : ℤ)
    {f : Lp ℝ 2 (volume : Measure ℝ)} (hf : f ∈ V j) :
    HasSum (fun k : ℤ => (inner ℝ (scalingSystem φ j k) f) • scalingSystem φ j k) f := by
  have hmem : ∀ k : ℤ, scalingSystem φ j k ∈
      (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure := fun k =>
    Submodule.le_topologicalClosure _ (Submodule.subset_span (Set.mem_range_self k))
  have hfK : f ∈ (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure := by
    rw [← h.eq_topologicalClosure_span_scalingSystem j]; exact hf
  set b := (h.orthonormal_scaled j).hilbertBasisTopologicalClosure with hbdef
  have hbcoe : ∀ k : ℤ,
      ((b k : (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure) :
        Lp ℝ 2 (volume : Measure ℝ)) = scalingSystem φ j k := by
    intro k
    simp only [hbdef, Orthonormal.hilbertBasisTopologicalClosure]
    rw [HilbertBasis.coe_mkOfOrthogonalEqBot]
    rfl
  have hsum := (b.hasSum_repr ⟨f, hfK⟩).mapL
    (Submodule.span ℝ (Set.range (scalingSystem φ j))).topologicalClosure.subtypeL
  refine hsum.congr_fun fun k => ?_
  rw [ContinuousLinearMap.map_smul, Submodule.subtypeL_apply, hbcoe k,
    HilbertBasis.repr_apply_apply, Submodule.coe_inner, hbcoe k]

/-- The scaling function lies in `V 0`. -/
theorem mem_zero (h : IsMultiresolutionAnalysis V φ) : φ ∈ V 0 := by
  have h0 : translates φ 0 = φ := by
    rw [translates, Int.cast_zero, neg_zero]
    exact Lp.translationₗᵢ_zero φ
  rw [h.eq_topologicalClosure_span]
  exact Submodule.le_topologicalClosure _ (Submodule.subset_span ⟨0, h0⟩)

/-- **The scaling equation.** In a multiresolution analysis the scaling function is the sum of the
level-`1` system against its own level-`1` coefficients `p k = ⟪√2 φ (2 · - k), φ⟫`: `φ` lies in `V
0 ≤ V 1`, and is expanded in the orthonormal system of `V 1`.

Reference: [han2009theoretical], (4.5.1)–(4.5.3). -/
theorem hasSum_scalingEquation (h : IsMultiresolutionAnalysis V φ) :
    HasSum (fun k : ℤ => (inner ℝ (scalingSystem φ 1 k) φ) • scalingSystem φ 1 k) φ :=
  h.hasSum_inner_smul 1 (h.le_succ 0 h.mem_zero)

/-- **The necessary condition on the dilation coefficients** ([han2009theoretical], Exercise
4.5.2). If the integer translates of the scaling function are orthonormal, its dilation
coefficients `p_k = ⟪√2 φ(2 · - k), φ⟫` satisfy

`∑_k p_k p_{k - 2l} = δ_{0l}`.

The proof is the orthonormality of the translates read through the scaling equation: translating
that equation by `l` reindexes the level-one system by `k ↦ k - 2l`, and pairing the result with
`φ` turns `⟪φ(· - l), φ⟫ = δ_{0l}` into the displayed sum. -/
theorem hasSum_scalingCoeff_mul (h : IsMultiresolutionAnalysis V φ) (l : ℤ) :
    HasSum (fun k : ℤ => inner ℝ (scalingSystem φ 1 k) φ
        * inner ℝ (scalingSystem φ 1 (k - 2 * l)) φ)
      (if l = 0 then (1 : ℝ) else 0) := by
  have htrans : Lp.translationₗᵢ (l : ℝ) φ = translates φ (-l) := by
    rw [translates, show -(((-l : ℤ)) : ℝ) = (l : ℝ) by push_cast; ring]
  -- the value: orthonormality of the translates
  have hval : (inner ℝ φ (Lp.translationₗᵢ (l : ℝ) φ) : ℝ) = if l = 0 then 1 else 0 := by
    have hon := orthonormal_iff_ite.mp h.orthonormal_translates 0 (-l)
    rw [translates_zero] at hon
    rw [htrans, hon]
    by_cases hl : l = 0
    · rw [ite_eq_left (by omega), ite_eq_left hl]
    · rw [ite_eq_right (by omega), ite_eq_right hl]
  -- translate the scaling equation and pair it with `φ`
  have hT := (h.hasSum_scalingEquation.mapL
    (Lp.translationₗᵢ (l : ℝ)).toContinuousLinearMap).mapL (innerSL ℝ φ)
  simp only [LinearIsometry.coe_toContinuousLinearMap, innerSL_apply_apply ℝ, map_smul,
    translationₗᵢ_scalingSystem_one φ _ l, real_inner_smul_right] at hT
  rw [hval] at hT
  refine hT.congr_fun fun k => ?_
  simp only [real_inner_comm φ]

end IsMultiresolutionAnalysis

/-! ### The dilation coefficients, the wavelet and the wavelet spaces -/

namespace MeasureTheory.Lp

/-- Dilations by equal factors agree, whatever the proofs that the factors do not vanish. -/
theorem dilationₗᵢ_congr {c d : ℝ} (hc : c ≠ 0) (hd : d ≠ 0) (h : c = d)
    (f : Lp ℝ 2 (volume : Measure ℝ)) : dilationₗᵢ c hc f = dilationₗᵢ d hd f := by
  subst h; rfl

/-- **Translation is unitary, with adjoint the opposite translation.** -/
theorem inner_translationₗᵢ (a : ℝ) (x y : Lp ℝ 2 (volume : Measure ℝ)) :
    inner ℝ (translationₗᵢ a x) y = inner ℝ x (translationₗᵢ (-a) y) := by
  have h : translationₗᵢ a (translationₗᵢ (-a) y) = y := by
    rw [translationₗᵢ_trans, neg_add_cancel, translationₗᵢ_zero]
  conv_lhs => rw [← h]
  exact (translationₗᵢ a).inner_map_map x _

end MeasureTheory.Lp

/-- Dilating the level-`i` scaling system by `2 ^ j` gives the level-`(j + i)` system. -/
theorem dilationₗᵢ_scalingSystem (φ : Lp ℝ 2 (volume : Measure ℝ)) (j i k : ℤ) :
    Lp.dilationₗᵢ ((2 : ℝ) ^ j) (zpow_ne_zero j two_ne_zero) (scalingSystem φ i k)
      = scalingSystem φ (j + i) k := by
  simp only [scalingSystem]
  rw [Lp.dilationₗᵢ_trans]
  exact Lp.dilationₗᵢ_congr _ _ (by rw [← zpow_add₀ (two_ne_zero' ℝ), add_comm]) _

/-- **(4.5.2)**, the dilation coefficients of a scaling function:
`p_k = ∫ √2 φ(2x - k) φ(x) dx = ⟪φ_{1,k}, φ⟫`.

Reference: [han2009theoretical], (4.5.2). -/
def scalingCoeff (φ : Lp ℝ 2 (volume : Measure ℝ)) (k : ℤ) : ℝ :=
  inner ℝ (scalingSystem φ 1 k) φ

/-- **(4.5.4)**, the wavelet attached to a scaling function:
`ψ(x) = ∑_k (-1)^k p_{1-k} √2 φ(2x - k)`.

The sum is the high-pass channel `qmfHigh` of the dilation coefficients against the level-`1`
scaling system; it converges because the coefficients are square summable, which is
`IsMultiresolutionAnalysis.hasSum_mraWavelet`.

Reference: [han2009theoretical], (4.5.4). -/
def mraWavelet (φ : Lp ℝ 2 (volume : Measure ℝ)) : Lp ℝ 2 (volume : Measure ℝ) :=
  ∑' k : ℤ, qmfHigh (scalingCoeff φ) k • scalingSystem φ 1 k

/-- The system `2 ^ (j/2) ψ(2 ^ j x - k)` generated by the wavelet of a scaling function. -/
def waveletSystem (φ : Lp ℝ 2 (volume : Measure ℝ)) : ℤ → ℤ → Lp ℝ 2 (volume : Measure ℝ) :=
  scalingSystem (mraWavelet φ)

/-- The **wavelet space** of level `j` of a ladder of scaling spaces: the part of `V (j+1)`
orthogonal to `V j`, written `W j = V_{j+1} ⊖ V_j`. -/
def waveletSpace (V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ))) (j : ℤ) :
    Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ)) :=
  (V j)ᗮ ⊓ V (j + 1)

namespace IsMultiresolutionAnalysis

variable {V : ℤ → Submodule ℝ (Lp ℝ 2 (volume : Measure ℝ))} {φ : Lp ℝ 2 (volume : Measure ℝ)}

/-! ### Elementary consequences of the axioms -/

/-- The scaling spaces increase. -/
theorem monotone (h : IsMultiresolutionAnalysis V φ) : Monotone V :=
  monotone_int_of_le_succ h.le_succ

theorem isClosed_V (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    IsClosed (V j : Set (Lp ℝ 2 (volume : Measure ℝ))) := by
  rw [h.eq_topologicalClosure_span_scalingSystem j]
  exact Submodule.isClosed_topologicalClosure _

theorem completeSpace_V (h : IsMultiresolutionAnalysis V φ) (j : ℤ) : CompleteSpace (V j) :=
  (h.isClosed_V j).completeSpace_coe

/-- Dilation by `2 ^ i` carries the scaling space of level `j` onto that of level `i + j`. -/
theorem map_dilation_V (h : IsMultiresolutionAnalysis V φ) (i j : ℤ) :
    (V j).map (Lp.dilationₗᵢ ((2 : ℝ) ^ i)
        (zpow_ne_zero i two_ne_zero)).toLinearEquiv.toLinearMap = V (i + j) := by
  have himg : (Lp.dilationₗᵢ ((2 : ℝ) ^ i)
      (zpow_ne_zero i two_ne_zero)).toLinearEquiv.toLinearMap ''
        Set.range (scalingSystem φ j) = Set.range (scalingSystem φ (i + j)) := by
    rw [← Set.range_comp]
    exact congrArg Set.range (funext fun k => dilationₗᵢ_scalingSystem φ i j k)
  rw [h.eq_topologicalClosure_span_scalingSystem j,
    h.eq_topologicalClosure_span_scalingSystem (i + j), map_topologicalClosure,
    Submodule.map_span, himg]

theorem dilation_mem_V (h : IsMultiresolutionAnalysis V φ) {i j : ℤ}
    {y : Lp ℝ 2 (volume : Measure ℝ)} (hy : y ∈ V j) :
    Lp.dilationₗᵢ ((2 : ℝ) ^ i) (zpow_ne_zero i two_ne_zero) y ∈ V (i + j) := by
  rw [← h.map_dilation_V i j]
  exact ⟨y, hy, rfl⟩

/-! ### The scaling equation as a filter -/

/-- The coefficients of the scaling equation, read against a translate: `⟪φ_{1,k}, φ(· - l)⟫` is
`p_{k - 2l}`.  It is the commutation of translation with dilation. -/
theorem inner_scalingSystem_one_translates (φ : Lp ℝ 2 (volume : Measure ℝ)) (k l : ℤ) :
    inner ℝ (scalingSystem φ 1 k) (translates φ l) = scalingCoeff φ (k - 2 * l) := by
  rw [scalingCoeff, ← translationₗᵢ_scalingSystem_one φ k l,
    Lp.inner_translationₗᵢ (l : ℝ) (scalingSystem φ 1 k) φ]
  rfl

/-- **The dilation coefficients of a scaling function are a quadrature mirror filter.** This is the
necessary condition `∑_k p_k p_{k - 2l} = δ_{0l}` of [han2009theoretical] Exercise 4.5.2, packaged
as `IsQMFCoeff` so that the two-channel theory of `Numlib/Analysis/Wavelet/QuadratureMirror`
applies. -/
theorem isQMFCoeff (h : IsMultiresolutionAnalysis V φ) : IsQMFCoeff (scalingCoeff φ) :=
  fun l => h.hasSum_scalingCoeff_mul l

/-- **The scaling equation for a translate of the scaling function**: `φ(· - l)` is the low-pass
channel of the level-`1` system at shift `l`.  At `l = 0` it is [han2009theoretical] (4.5.1). -/
theorem hasSum_translates_low (h : IsMultiresolutionAnalysis V φ) (l : ℤ) :
    HasSum (fun k : ℤ => scalingCoeff φ (k - 2 * l) • scalingSystem φ 1 k) (translates φ l) := by
  have h01 : V 0 ≤ V 1 := by simpa using h.le_succ 0
  have hmem : translates φ l ∈ V 1 := by
    refine h01 ?_
    rw [h.eq_topologicalClosure_span]
    exact Submodule.le_topologicalClosure _ (Submodule.subset_span (Set.mem_range_self l))
  refine (h.hasSum_inner_smul 1 hmem).congr_fun fun k => ?_
  rw [inner_scalingSystem_one_translates]

/-! ### The wavelet -/

/-- The series defining the wavelet converges: its coefficients are square summable, because they
are a rearrangement of the dilation coefficients. -/
theorem hasSum_mraWavelet (h : IsMultiresolutionAnalysis V φ) :
    HasSum (fun k : ℤ => qmfHigh (scalingCoeff φ) k • scalingSystem φ 1 k) (mraWavelet φ) := by
  refine Summable.hasSum ?_
  refine ((h.orthonormal_scaled 1).summable_smul_iff _).2 ?_
  simpa using h.isQMFCoeff.summable_high_sq 0

/-- **The translates of the wavelet are the high-pass channel** of the level-`1` scaling system. -/
theorem hasSum_translates_high (h : IsMultiresolutionAnalysis V φ) (l : ℤ) :
    HasSum (fun k : ℤ => qmfHigh (scalingCoeff φ) (k - 2 * l) • scalingSystem φ 1 k)
      (translates (mraWavelet φ) l) := by
  have hT := h.hasSum_mraWavelet.mapL (Lp.translationₗᵢ (-(l : ℝ))).toContinuousLinearMap
  simp only [LinearIsometry.coe_toContinuousLinearMap, map_smul] at hT
  have hT2 : HasSum (fun k : ℤ => qmfHigh (scalingCoeff φ) k • scalingSystem φ 1 (k + 2 * l))
      (translates (mraWavelet φ) l) := by
    refine hT.congr_fun fun k => ?_
    rw [show -(l : ℝ) = ((-l : ℤ) : ℝ) by push_cast; ring, translationₗᵢ_scalingSystem_one φ k (-l),
      show k - 2 * -l = k + 2 * l by ring]
  rw [← Equiv.hasSum_iff (Equiv.subRight (2 * l))] at hT2
  refine hT2.congr_fun fun k => ?_
  simp only [Function.comp_apply, Equiv.subRight_apply]
  rw [show k - 2 * l + 2 * l = k by ring]

/-! ### Every level -/

/-- **The scaling relation** [han2009theoretical] (4.5.3): the level-`j` scaling function at shift
`l` is the low-pass channel of the level-`(j+1)` system. -/
theorem hasSum_scalingSystem_low (h : IsMultiresolutionAnalysis V φ) (j l : ℤ) :
    HasSum (fun k : ℤ => scalingCoeff φ (k - 2 * l) • scalingSystem φ (j + 1) k)
      (scalingSystem φ j l) := by
  have hD := (h.hasSum_translates_low l).mapL
    (Lp.dilationₗᵢ ((2 : ℝ) ^ j)
      (zpow_ne_zero j two_ne_zero)).toLinearIsometry.toContinuousLinearMap
  simp only [LinearIsometry.coe_toContinuousLinearMap, LinearIsometryEquiv.coe_toLinearIsometry,
    map_smul] at hD
  refine hD.congr_fun fun k => ?_
  rw [dilationₗᵢ_scalingSystem]

/-- The level-`j` wavelet is the high-pass channel of the level-`(j+1)` scaling system. -/
theorem hasSum_waveletSystem (h : IsMultiresolutionAnalysis V φ) (j l : ℤ) :
    HasSum (fun k : ℤ => qmfHigh (scalingCoeff φ) (k - 2 * l) • scalingSystem φ (j + 1) k)
      (waveletSystem φ j l) := by
  have hD := (h.hasSum_translates_high l).mapL
    (Lp.dilationₗᵢ ((2 : ℝ) ^ j)
      (zpow_ne_zero j two_ne_zero)).toLinearIsometry.toContinuousLinearMap
  simp only [LinearIsometry.coe_toContinuousLinearMap, LinearIsometryEquiv.coe_toLinearIsometry,
    map_smul] at hD
  refine hD.congr_fun fun k => ?_
  rw [dilationₗᵢ_scalingSystem]

/-- **The scaling and wavelet systems of level `j` are together an orthonormal basis of `V (j+1)`**:
they are orthonormal … -/
theorem orthonormal_sumElim_scalingSystem (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    Orthonormal ℝ (Sum.elim (scalingSystem φ j) (waveletSystem φ j)) :=
  h.isQMFCoeff.orthonormal_sumElim (h.orthonormal_scaled (j + 1))
    (h.hasSum_scalingSystem_low j) (h.hasSum_waveletSystem j)

/-- … and their closed span is `V (j+1)`. -/
theorem topologicalClosure_span_sumElim_scalingSystem (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    (Submodule.span ℝ
        (Set.range (Sum.elim (scalingSystem φ j) (waveletSystem φ j)))).topologicalClosure
      = V (j + 1) := by
  rw [h.isQMFCoeff.topologicalClosure_span_sumElim (h.orthonormal_scaled (j + 1))
    (h.hasSum_scalingSystem_low j) (h.hasSum_waveletSystem j),
    ← h.eq_topologicalClosure_span_scalingSystem (j + 1)]

/-- **The wavelet system of level `j` is orthonormal.** -/
theorem orthonormal_waveletSystem (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    Orthonormal ℝ (waveletSystem φ j) :=
  (h.orthonormal_sumElim_scalingSystem j).comp Sum.inr Sum.inr_injective

/-- **The wavelet space of level `j` is the closed span of the level-`j` wavelet system.** With
`IsMultiresolutionAnalysis.orthonormal_waveletSystem` this is the first clause of Mallat's theorem:
`{2^{j/2} ψ(2^j x - k)}_k` is an orthonormal basis of `W_j = V_{j+1} ⊖ V_j`. -/
theorem waveletSpace_eq (h : IsMultiresolutionAnalysis V φ) (j : ℤ) :
    waveletSpace V j
      = (Submodule.span ℝ (Set.range (waveletSystem φ j))).topologicalClosure := by
  have key := (h.orthonormal_sumElim_scalingSystem j).topologicalClosure_span_comp_inr
  rw [show Sum.elim (scalingSystem φ j) (waveletSystem φ j) ∘ Sum.inr = waveletSystem φ j from rfl,
    show Sum.elim (scalingSystem φ j) (waveletSystem φ j) ∘ Sum.inl = scalingSystem φ j from rfl,
    h.topologicalClosure_span_sumElim_scalingSystem j,
    ← h.eq_topologicalClosure_span_scalingSystem j] at key
  exact key.symm

theorem waveletSystem_mem_waveletSpace (h : IsMultiresolutionAnalysis V φ) (j k : ℤ) :
    waveletSystem φ j k ∈ waveletSpace V j := by
  rw [h.waveletSpace_eq j]
  exact Submodule.le_topologicalClosure _ (Submodule.subset_span (Set.mem_range_self k))

theorem waveletSystem_mem_V_succ (h : IsMultiresolutionAnalysis V φ) (j k : ℤ) :
    waveletSystem φ j k ∈ V (j + 1) := (h.waveletSystem_mem_waveletSpace j k).2

theorem waveletSystem_mem_orthogonal_V (h : IsMultiresolutionAnalysis V φ) (j k : ℤ) :
    waveletSystem φ j k ∈ (V j)ᗮ := (h.waveletSystem_mem_waveletSpace j k).1

/-- The wavelet lies in the scaling space of level `1`. -/
theorem mraWavelet_mem_V_one (h : IsMultiresolutionAnalysis V φ) : mraWavelet φ ∈ V 1 := by
  have hm := h.waveletSystem_mem_V_succ 0 0
  rw [show (0 : ℤ) + 1 = 1 by ring,
    show waveletSystem φ 0 0 = mraWavelet φ by
      rw [waveletSystem, scalingSystem_zero, translates_zero]] at hm
  exact hm

/-- **The wavelet spaces are mutually orthogonal**: `W i` sits inside `V (i+1) ≤ V j` for `i < j`,
and `W j` is orthogonal to `V j`. -/
theorem inner_waveletSpace_eq_zero_of_lt (h : IsMultiresolutionAnalysis V φ) {i j : ℤ}
    (hij : i < j) {u v : Lp ℝ 2 (volume : Measure ℝ)} (hu : u ∈ waveletSpace V i)
    (hv : v ∈ waveletSpace V j) : inner ℝ u v = 0 :=
  (Submodule.mem_orthogonal (V j) v).1 hv.1 u (h.monotone (by omega) hu.2)

/-! ### The wavelets of all levels -/

/-- **Wavelets of different levels are orthogonal.** Dilating by `2 ^ (-j)` puts the level-`i`
wavelet into `V 0` and the level-`j` one into `(V 0)ᗮ`. -/
theorem inner_waveletSystem_eq_zero_of_lt (h : IsMultiresolutionAnalysis V φ) {i j : ℤ}
    (hij : i < j) (k l : ℤ) : inner ℝ (waveletSystem φ i k) (waveletSystem φ j l) = 0 := by
  have hD : ∀ m n : ℤ, Lp.dilationₗᵢ ((2 : ℝ) ^ (-j)) (zpow_ne_zero (-j) two_ne_zero)
      (waveletSystem φ m n) = waveletSystem φ (-j + m) n := fun m n =>
    dilationₗᵢ_scalingSystem (mraWavelet φ) (-j) m n
  rw [← LinearIsometryEquiv.inner_map_map (Lp.dilationₗᵢ ((2 : ℝ) ^ (-j))
    (zpow_ne_zero (-j) two_ne_zero)), hD, hD, neg_add_cancel]
  have hmem : waveletSystem φ (-j + i) k ∈ V 0 :=
    h.monotone (by omega) (h.waveletSystem_mem_V_succ (-j + i) k)
  exact (Submodule.mem_orthogonal (V 0) _).1 (h.waveletSystem_mem_orthogonal_V 0 l) _ hmem

/-- **The wavelets of all levels are orthonormal.** -/
theorem orthonormal_waveletSystem_prod (h : IsMultiresolutionAnalysis V φ) :
    Orthonormal ℝ fun jk : ℤ × ℤ => waveletSystem φ jk.1 jk.2 := by
  rw [orthonormal_iff_ite]
  rintro ⟨i, k⟩ ⟨j, l⟩
  rcases lt_trichotomy i j with hij | rfl | hij
  · rw [h.inner_waveletSystem_eq_zero_of_lt hij]
    exact (ite_eq_right (by simp only [Prod.mk.injEq]; omega)).symm
  · rw [orthonormal_iff_ite.mp (h.orthonormal_waveletSystem i) k l]
    by_cases hkl : k = l <;> simp [hkl]
  · rw [real_inner_comm, h.inner_waveletSystem_eq_zero_of_lt hij]
    exact (ite_eq_right (by simp only [Prod.mk.injEq]; omega)).symm

/-! ### Completeness -/

/-- The orthogonal projections onto the scaling spaces of a vector orthogonal to every wavelet do
not depend on the level: `V (j+1) = V j ⊕ W j`, and the `W j` component vanishes. -/
theorem starProjection_V_succ_eq (h : IsMultiresolutionAnalysis V φ)
    {x : Lp ℝ 2 (volume : Measure ℝ)}
    (hx : ∀ j k : ℤ, inner ℝ (waveletSystem φ j k) x = 0) (j : ℤ)
    [(V j).HasOrthogonalProjection] [(V (j + 1)).HasOrthogonalProjection] :
    (V (j + 1)).starProjection x = (V j).starProjection x := by
  have hxW : ∀ w ∈ waveletSpace V j, (inner ℝ w x : ℝ) = 0 := by
    intro w hw
    rw [h.waveletSpace_eq j] at hw
    have hxperp : x ∈ ((Submodule.span ℝ
        (Set.range (waveletSystem φ j))).topologicalClosure)ᗮ := by
      rw [Submodule.orthogonal_closure]
      exact Submodule.mem_orthogonal_span_range (hx j)
    exact (Submodule.mem_orthogonal _ _).1 hxperp w hw
  have hymem : (V (j + 1)).starProjection x ∈ V (j + 1) := Submodule.starProjection_apply_mem _ _
  have hsplit : (V (j + 1)).starProjection x ∈ V j ⊔ (V j)ᗮ ⊓ V (j + 1) := by
    rw [Submodule.sup_orthogonal_inf_of_hasOrthogonalProjection (h.le_succ j)]
    exact hymem
  rw [Submodule.mem_sup] at hsplit
  obtain ⟨u, hu, w, hw, huw⟩ := hsplit
  have h1 : (inner ℝ w (x - (V (j + 1)).starProjection x) : ℝ) = 0 :=
    (Submodule.mem_orthogonal _ _).1 (Submodule.sub_starProjection_mem_orthogonal x) w hw.2
  have h2 : (inner ℝ w x : ℝ) = 0 := hxW w hw
  have h3 : (inner ℝ w u : ℝ) = 0 := by
    rw [real_inner_comm]
    exact (Submodule.mem_orthogonal _ _).1 hw.1 u hu
  have h4 : (inner ℝ w w : ℝ) = 0 := by
    rw [inner_sub_right, h2] at h1
    rw [← huw, inner_add_right, h3, zero_add] at h1
    linarith
  have hwzero : w = 0 := inner_self_eq_zero.mp h4
  have hyj : (V (j + 1)).starProjection x ∈ V j := by
    rw [← huw, hwzero, add_zero]
    exact hu
  refine (Submodule.eq_starProjection_of_mem_of_inner_eq_zero hyj fun z hz => ?_).symm
  exact (Submodule.mem_orthogonal' _ _).1 (Submodule.sub_starProjection_mem_orthogonal x) z
    (h.le_succ j hz)

/-- **A vector orthogonal to every wavelet vanishes.** The projections onto the scaling spaces are
all equal by `IsMultiresolutionAnalysis.starProjection_V_succ_eq`, hence lie in `⨅ j, V j = ⊥`; so
the vector is orthogonal to every `V j`, and the density axiom finishes. -/
theorem eq_zero_of_inner_waveletSystem_eq_zero (h : IsMultiresolutionAnalysis V φ)
    {x : Lp ℝ 2 (volume : Measure ℝ)}
    (hx : ∀ j k : ℤ, inner ℝ (waveletSystem φ j k) x = 0) : x = 0 := by
  have hinst : ∀ j : ℤ, (V j).HasOrthogonalProjection := fun j =>
    have : CompleteSpace (V j) := h.completeSpace_V j
    inferInstance
  have hconst : ∀ j : ℤ, (V j).starProjection x = (V 0).starProjection x := by
    intro j
    induction j using Int.induction_on with
    | zero => rfl
    | succ n ih => rw [h.starProjection_V_succ_eq hx (n : ℤ), ih]
    | pred n ih =>
      have hstep := h.starProjection_V_succ_eq hx (-(n : ℤ) - 1)
      rw [show -(n : ℤ) - 1 + 1 = -(n : ℤ) by ring] at hstep
      rw [← hstep, ih]
  have hbotmem : (V 0).starProjection x ∈ ⨅ j : ℤ, V j := by
    rw [Submodule.mem_iInf]
    intro j
    rw [← hconst j]
    exact Submodule.starProjection_apply_mem _ _
  rw [h.iInf_eq_bot, Submodule.mem_bot] at hbotmem
  have hVperp : ∀ j : ℤ, ∀ v ∈ V j, (inner ℝ v x : ℝ) = 0 := by
    intro j v hv
    have hzero : x ∈ (V j)ᗮ := by
      have := Submodule.sub_starProjection_mem_orthogonal (K := V j) x
      rwa [hconst j, hbotmem, sub_zero] at this
    exact (Submodule.mem_orthogonal _ _).1 hzero v hv
  have hle : (⨆ j : ℤ, V j) ≤ (Submodule.span ℝ {x})ᗮ := by
    refine iSup_le fun j v hv => ?_
    exact Submodule.mem_orthogonal_singleton_iff_inner_left.mpr (hVperp j v hv)
  have hxsup : x ∈ (⨆ j : ℤ, V j)ᗮ := by
    rw [Submodule.mem_orthogonal]
    exact fun u hu => Submodule.mem_orthogonal_singleton_iff_inner_left.mp (hle hu)
  have hbot : (⨆ j : ℤ, V j)ᗮ = ⊥ :=
    Submodule.topologicalClosure_eq_top_iff.mp h.topologicalClosure_iSup
  rwa [hbot, Submodule.mem_bot] at hxsup

/-- **Mallat's theorem, completeness half**: the wavelets of all levels span `L²(ℝ)`. -/
theorem topologicalClosure_span_waveletSystem_prod (h : IsMultiresolutionAnalysis V φ) :
    (Submodule.span ℝ
        (Set.range fun jk : ℤ × ℤ => waveletSystem φ jk.1 jk.2)).topologicalClosure = ⊤ := by
  rw [Submodule.topologicalClosure_eq_top_iff, Submodule.eq_bot_iff]
  intro x hx
  refine h.eq_zero_of_inner_waveletSystem_eq_zero fun j k => ?_
  exact (Submodule.mem_orthogonal _ _).1 hx _
    (Submodule.subset_span (Set.mem_range_self (j, k)))

/-- **Mallat's theorem**: every `f ∈ L²(ℝ)` is the sum of its wavelet coefficients against the
wavelets of all levels.  With `IsMultiresolutionAnalysis.orthonormal_waveletSystem_prod` this says
that `{2^{j/2} ψ(2^j x - k)}_{j,k}` is an orthonormal basis of `L²(ℝ)`. -/
theorem hasSum_inner_smul_waveletSystem (h : IsMultiresolutionAnalysis V φ)
    (f : Lp ℝ 2 (volume : Measure ℝ)) :
    HasSum (fun jk : ℤ × ℤ =>
        (inner ℝ (waveletSystem φ jk.1 jk.2) f) • waveletSystem φ jk.1 jk.2) f := by
  refine h.orthonormal_waveletSystem_prod.hasSum_inner_smul_of_mem ?_
  rw [h.topologicalClosure_span_waveletSystem_prod]
  trivial

/-- The wavelets of all levels, bundled as a Hilbert basis of `L²(ℝ)`. -/
def hilbertBasis (h : IsMultiresolutionAnalysis V φ) :
    HilbertBasis (ℤ × ℤ) ℝ (Lp ℝ 2 (volume : Measure ℝ)) :=
  HilbertBasis.mk h.orthonormal_waveletSystem_prod (by
    rw [h.topologicalClosure_span_waveletSystem_prod])

@[simp]
theorem coe_hilbertBasis (h : IsMultiresolutionAnalysis V φ) (jk : ℤ × ℤ) :
    h.hilbertBasis jk = waveletSystem φ jk.1 jk.2 := by
  rw [hilbertBasis, HilbertBasis.coe_mk]

end IsMultiresolutionAnalysis

/-! ### The Haar system -/

namespace Haar

/-- The level-`0` Haar scaling functions are the integer translates of the unit step `φ = 1_[0,1)`.
-/
theorem translates_scalingFun_zero (k : ℤ) :
    translates (scalingFun 0 0) k = scalingFun 0 k := by
  have hset : (fun x : ℝ => x + -(k : ℝ)) ⁻¹' dyadic 0 0 = dyadic 0 k := by
    ext x
    simp only [dyadic, Set.mem_preimage, Set.mem_Ico, neg_zero, zpow_zero, mul_one,
      Int.cast_zero, zero_add]
    constructor
    · rintro ⟨h1, h2⟩; constructor <;> linarith
    · rintro ⟨h1, h2⟩; constructor <;> linarith
  rw [translates, scalingFun_zero_zero, Lp.translationₗᵢ_indicatorConstLp,
    indicatorConstLp_congr_set _ _ (measurableSet_dyadic 0 k) (volume_dyadic_ne_top 0 k) hset,
    scalingFun]
  norm_num

/-- **The Haar system is a multiresolution analysis**, with scaling function the unit step `φ =
1_[0,1)`. Its five clauses are the five parts of [han2009theoretical] Theorem 4.4.1 proved in
`Numlib/Analysis/Wavelet/Haar`.

Reference: [han2009theoretical], §4.5. -/
theorem isMultiresolutionAnalysis : IsMultiresolutionAnalysis V (scalingFun 0 0) where
  orthonormal_translates := by
    have := orthonormal_scalingFun 0
    rwa [← funext translates_scalingFun_zero] at this
  eq_topologicalClosure_span := by
    rw [funext translates_scalingFun_zero]
    rfl
  eq_map_dilation := V_eq_map_dilation
  le_succ := V_le_V_succ
  topologicalClosure_iSup := topologicalClosure_iSup_V
  iInf_eq_bot := iInf_V_eq_bot

end Haar
