namespace = "SaadSparse.Ch05"

[[node]]
id = "mrStep"

[[node]]
id = "rnsdStep"

[[node]]
id = "sdStep"

[[node]]
id = "step1"

[[node]]
id = "equation_5_18"

[[node]]
id = "equation_5_20"

[[node]]
id = "norm_residual_mrStep_eq_sin"
