namespace = "Polynomial"

[[node]]
id = "kernelPolynomial"

[[node]]
id = "_root_.isLeast_of_inner_eq_one"

[[node]]
id = "bilinForm_kernelPolynomial_le"

[[node]]
id = "bilinForm_kernelPolynomial_mul_X"

[[node]]
id = "bilinForm_kernelPolynomial_le_pow"
