namespace = "CyclicReduction"

[[node]]
id = "extend"

[[node]]
id = "constBlockTridiagonal"

[[node]]
id = "constBlockTridiagonal_eq_iff"

[[node]]
id = "constBlockTridiagonal_eq_blockTridiagonal_mulVec"

[[node]]
id = "reducedDiag"

[[node]]
id = "reducedOff"

[[node]]
id = "reducedRhs"

[[node]]
id = "commute_reduced"

[[node]]
id = "extend_odd"

[[node]]
id = "constBlockTridiagonal_reduce"

[[node]]
id = "constBlockTridiagonal_odd_eq"

[[node]]
id = "size"

[[node]]
id = "size_eq"

[[node]]
id = "diagIter"

[[node]]
id = "rhsIter"

[[node]]
id = "constBlockTridiagonal_iterate_reduce"
