[[node]]
id = "Refinement.step"

[[node]]
id = "Refinement.step_eq_stationary_step"

[[node]]
id = "Refinement.step_eq_of_eq_inverse"

[[node]]
id = "Refinement.iterate_sub_eq"

[[node]]
id = "Refinement.norm_iterate_sub_le"

[[node]]
id = "Refinement.forall_tendsto_iff_spectralRadius_lt_one"

[[node]]
id = "Matrix.scaled_mulVec_eq_iff"

[[node]]
id = "norm_apply_div_le_norm_inverse"

[[node]]
id = "condEstimate"

[[node]]
id = "condEstimate_le_condNumber"

[[node]]
id = "Refinement.norm_pow_le_pow_norm"

[[node]]
id = "Refinement.step_error"

[[node]]
id = "Refinement.norm_step_error_le"

[[node]]
id = "Refinement.step_error_fp"
