namespace = "Matrix"

[[node]]
id = "_root_.Finset.sum_two_pow_card_filter_lt_add_one"

[[node]]
id = "_root_.Finset.sum_two_pow_card_filter_gt_add_one"

[[node]]
id = "card_filter_lt_le_eq_card_filter_le_lt"

[[node]]
id = "filter_ge_eq_insert_filter_gt"

[[node]]
id = "card_filter_le_eq_card_filter_lt_add_one"

[[node]]
id = "sum_filter_ge_eq_add"

[[node]]
id = "isUnit_iff_forall_diag_ne_zero_of_isUpperTriangular"

[[node]]
id = "isUnit_iff_forall_diag_ne_zero_of_isLowerTriangular"

[[node]]
id = "IsUpperTriangular.inv"

[[node]]
id = "IsLowerTriangular.inv"

[[node]]
id = "IsUpperTriangular.isLowerTriangular_orderDual"

[[node]]
id = "IsLowerTriangular.isUpperTriangular_orderDual"

[[node]]
id = "forwardSubst"

[[node]]
id = "forwardSubst_apply"

[[node]]
id = "mulVec_apply_of_isLowerTriangular"

[[node]]
id = "mulVec_forwardSubst"

[[node]]
id = "forwardSubst_eq_of_mulVec_eq"

[[node]]
id = "backSubst"

[[node]]
id = "backSubst_apply"

[[node]]
id = "backSubst_eq_forwardSubst_toDual"

[[node]]
id = "mulVec_apply_of_isUpperTriangular"

[[node]]
id = "mulVec_backSubst"

[[node]]
id = "backSubst_eq_of_mulVec_eq"

[[node]]
id = "luSolve"

[[node]]
id = "mulVec_luSolve"

[[node]]
id = "mulVec_luSolve_of_mul"

[[node]]
id = "isUnit_permMatrix"

[[node]]
id = "mulVec_luSolve_permMatrix"

[[node]]
id = "inv_col_eq_backSubst"

[[node]]
id = "inv_toBlock_le_of_isUpperTriangular"

[[node]]
id = "inv_apply_self_of_isUpperTriangular"

[[node]]
id = "inv_apply_of_isUpperTriangular_of_lt"

[[node]]
id = "diag_mul_inv_apply_of_isUpperTriangular"

[[node]]
id = "inv_apply_of_isUpperTriangular"

[[node]]
id = "abs_diag_mul_abs_inv_apply_le"

[[node]]
id = "abs_inv_mul_abs_apply_of_lt"

[[node]]
id = "abs_inv_mul_abs_apply_eq_sum"

[[node]]
id = "abs_inv_apply_self_mul_abs_diag"

[[node]]
id = "abs_inv_apply_mul_abs_diag_le_sum"

[[node]]
id = "abs_inv_apply_mul_abs_diag_le_two_pow"

[[node]]
id = "abs_inv_mul_abs_apply_le_two_pow"

[[node]]
id = "sum_abs_inv_mul_abs_apply_le_two_pow"

[[node]]
id = "abs_apply_le_abs_diag_of_sum_le"

[[node]]
id = "abs_inv_apply_mul_abs_diag_le_one"

[[node]]
id = "abs_inv_mul_abs_apply_le_of_isDiagDominant"

[[node]]
id = "sum_abs_apply_le_of_isDiagDominant"

[[node]]
id = "sum_abs_inv_mul_abs_apply_le_of_isDiagDominant"

[[node]]
id = "sum_abs_inv_mul_abs_apply_le_of_isDiagDominant'"
