[[node]]
id = "TopologicalSpace.Opens.Ioo"

[[node]]
id = "TopologicalSpace.Opens.coe_Ioo"

[[node]]
id = "HasWeakIteratedDerivOn"

[[node]]
id = "HasWeakDerivOn"

[[node]]
id = "hasWeakIteratedDerivOn_one"

[[node]]
id = "hasWeakIteratedDerivOn_iff"

[[node]]
id = "hasWeakDerivOn_iff"

[[node]]
id = "HasWeakIteratedDerivOn.integral_iteratedDeriv_mul"

[[node]]
id = "HasWeakDerivOn.integral_deriv_mul"

[[node]]
id = "TestFunction.iteratedDerivApply_coe"

[[node]]
id = "TestFunction.derivApply_coe"

[[node]]
id = "HasWeakDerivOn.hasWeakIteratedDerivOn_succ"

[[node]]
id = "HasWeakDerivOn.hasWeakIteratedDerivOn_of_succ"

[[node]]
id = "HasWeakIteratedDerivOn.hasWeakDerivOn_of_succ"

[[node]]
id = "hasWeakIteratedLineDerivOn_iff_hasWeakIteratedDerivOn"

[[node]]
id = "TestFunction.eq_zero_of_le_left"

[[node]]
id = "TestFunction.eq_zero_of_le_right"

[[node]]
id = "TestFunction.integral_eq_setIntegral_Ioo"

[[node]]
id = "TestFunction.integrable_volume"

[[node]]
id = "TestFunction.exists_tsupport_subset_Icc"

[[node]]
id = "TestFunction.support_integral_subset"

[[node]]
id = "TestFunction.primitive"

[[node]]
id = "TestFunction.primitive_coe"

[[node]]
id = "TestFunction.deriv_primitive"

[[node]]
id = "exists_testFunction_integral_eq_one"

[[node]]
id = "absolutelyContinuousOnInterval_integral"

[[node]]
id = "ae_deriv_integral_eq"

[[node]]
id = "hasWeakDerivOn_integral"

[[node]]
id = "ae_eq_const_of_hasWeakDerivOn_zero"

[[node]]
id = "HasWeakDerivOn.exists_ae_eq_integral"

[[node]]
id = "HasWeakDerivOn.exists_continuousOn_ae_eq"

[[node]]
id = "multiIndexTuple_singleton"

[[node]]
id = "SobolevInterval"

[[node]]
id = "MemSobolevInterval"

[[node]]
id = "memSobolevInterval_iff"

[[node]]
id = "memSobolevInterval_zero_iff"

[[node]]
id = "memSobolevInterval_succ_iff"

[[node]]
id = "memSobolevInterval_one_iff"
source = 'Quarteroni, Sacco and Saleri, Numerical Mathematics, (12.42)'

[[node]]
id = "SobolevInterval.fn"

[[node]]
id = "SobolevInterval.derivIndex"

[[node]]
id = "SobolevInterval.derivIndexEquiv"

[[node]]
id = "SobolevInterval.deriv"

[[node]]
id = "SobolevInterval.deriv_zero"

[[node]]
id = "SobolevInterval.deriv_add"

[[node]]
id = "SobolevInterval.deriv_smul"

[[node]]
id = "SobolevInterval.deriv_sub"

[[node]]
id = "SobolevInterval.deriv_zero_elem"

[[node]]
id = "SobolevInterval.ext"

[[node]]
id = "SobolevInterval.hasWeakIteratedDerivOn_deriv"

[[node]]
id = "SobolevInterval.hasWeakDerivOn_deriv_succ"

[[node]]
id = "SobolevInterval.memSobolevInterval_fn"

[[node]]
id = "SobolevInterval.integrableOn_deriv"

[[node]]
id = "SobolevInterval.norm_sq_eq"
source = 'Quarteroni, Sacco and Saleri, Numerical Mathematics, (10.35)'

[[node]]
id = "SobolevInterval.inner_eq"
source = 'Quarteroni, Sacco and Saleri, Numerical Mathematics, (10.34)'

[[node]]
id = "SobolevInterval.norm_deriv_le"

[[node]]
id = "SobolevInterval.derivL"

[[node]]
id = "SobolevInterval.derivL_apply"

[[node]]
id = "SobolevInterval.seminorm"
source = 'Quarteroni, Sacco and Saleri, Numerical Mathematics, (12.49)'

[[node]]
id = "SobolevInterval.seminorm_apply"

[[node]]
id = "SobolevInterval.seminorm_le_norm"

[[node]]
id = "SobolevInterval.mk"

[[node]]
id = "SobolevInterval.deriv_mk"

[[node]]
id = "SobolevInterval.fn_mk"

[[node]]
id = "SobolevInterval.derivₗ"

[[node]]
id = "SobolevInterval.deriv_derivₗ"

[[node]]
id = "SobolevInterval.norm_derivₗ_le"

[[node]]
id = "SobolevInterval.derivCLM"

[[node]]
id = "SobolevInterval.deriv_derivCLM"

[[node]]
id = "SobolevInterval.norm_derivCLM_le"

[[node]]
id = "SobolevInterval.inclusionₗ"

[[node]]
id = "SobolevInterval.deriv_inclusionₗ"

[[node]]
id = "SobolevInterval.norm_inclusionₗ_le"

[[node]]
id = "SobolevInterval.inclusionCLM"

[[node]]
id = "SobolevInterval.deriv_inclusionCLM"

[[node]]
id = "SobolevInterval.fn_inclusionCLM"

[[node]]
id = "SobolevInterval.norm_inclusionCLM_le"

[[node]]
id = "abs_setIntegral_le_sqrt_mul_norm"

[[node]]
id = "abs_intervalIntegral_le_sqrt_mul_norm"

[[node]]
id = "integral_abs_le_sqrt_mul_norm"

[[node]]
id = "SobolevInterval.hasWeakDerivOn_fn"

[[node]]
id = "SobolevInterval.repConst"

[[node]]
id = "SobolevInterval.rep"

[[node]]
id = "SobolevInterval.rep_apply"

[[node]]
id = "SobolevInterval.continuousOn_rep"

[[node]]
id = "SobolevInterval.absolutelyContinuousOnInterval_rep"

[[node]]
id = "SobolevInterval.hasWeakDerivOn_rep"

[[node]]
id = "SobolevInterval.ae_deriv_rep_eq"

[[node]]
id = "SobolevInterval.rep_sub_rep"

[[node]]
id = "SobolevInterval.fn_ae_eq_rep"

[[node]]
id = "SobolevInterval.rep_eq_of_continuousOn"

[[node]]
id = "SobolevInterval.rep_add"

[[node]]
id = "SobolevInterval.rep_smul"

[[node]]
id = "SobolevInterval.abs_rep_le"

[[node]]
id = "SobolevInterval.toContinuousMapₗ"

[[node]]
id = "SobolevInterval.norm_toContinuousMapₗ_le"

[[node]]
id = "SobolevInterval.toContinuousMap"

[[node]]
id = "SobolevInterval.toContinuousMap_apply"

[[node]]
id = "SobolevInterval.norm_toContinuousMap_le"

[[node]]
id = "SobolevInterval.norm_toContinuousMap_le'"

[[node]]
id = "SobolevInterval.coe_toContinuousMap_ae_eq"

[[node]]
id = "SobolevInterval.toContinuousMap_eq_of_continuousOn"

[[node]]
id = "SobolevInterval.toContinuousMap_sub_eq_integral"

[[node]]
id = "SobolevInterval.absolutelyContinuousOnInterval_toContinuousMap"

[[node]]
id = "integral_mul_add_mul_of_eq_integral"

[[node]]
id = "SobolevInterval.integral_deriv_mul_add_mul_deriv"

[[node]]
id = "SobolevInterval.integral_deriv_mul_eq_sub_integral_mul_deriv"

[[node]]
id = "SobolevInterval.integral_deriv_mul_contDiffOn"

[[node]]
id = "SobolevInterval.rep_mul_rep_eq"

[[node]]
id = "SobolevInterval.integrableOn_leibniz"

[[node]]
id = "SobolevInterval.hasWeakDerivOn_rep_mul"

[[node]]
id = "SobolevInterval.memLp_leibniz"

[[node]]
id = "SobolevInterval.memSobolevInterval_mul"

[[node]]
id = "integral_Ioo_sub_left"

[[node]]
id = "SobolevInterval.norm_le_of_eq_integral"

[[node]]
id = "SobolevIntervalZero"

[[node]]
id = "SobolevIntervalZero.mem_of_fn_ae_eq"

[[node]]
id = "SobolevIntervalZero.exists_mem_fn_ae_eq"

[[node]]
id = "SobolevIntervalZero.rep_left_eq_zero"

[[node]]
id = "SobolevIntervalZero.rep_right_eq_zero"

[[node]]
id = "SobolevIntervalZero.toContinuousMap_eq_zero"

[[node]]
id = "SobolevIntervalZero.rep_eq_integral"

[[node]]
id = "SobolevIntervalZero.norm_deriv_zero_le"
source = 'Quarteroni, Sacco and Saleri, Numerical Mathematics, (12.16)'

[[node]]
id = "SobolevIntervalZero.norm_le_seminorm"

[[node]]
id = "SobolevIntervalZero.seminorm_eq_zero_iff"

[[node]]
id = "exists_testFunction_eLpNorm_sub_le_of_contDiff"

[[node]]
id = "exists_testFunction_eLpNorm_sub_le"

[[node]]
id = "intervalIntegral_congr_ae_Ioo"

[[node]]
id = "TestFunction.toLp₂"

[[node]]
id = "TestFunction.coeFn_toLp₂"

[[node]]
id = "exists_testFunction_norm_sub_toLp_le"

[[node]]
id = "SobolevIntervalZero.mem_of_rep_eq_zero"

[[node]]
id = "mem_sobolevIntervalZero_of_toContinuousMap_eq_zero"

[[node]]
id = "mem_sobolevIntervalZero_iff"
source = 'Quarteroni, Sacco and Saleri, Numerical Mathematics, (12.42)'

[[node]]
id = "hasWeakIteratedDerivOn_of_contDiffOn"

[[node]]
id = "hasWeakDerivOn_of_contDiffOn"

[[node]]
id = "ContDiffMapIcc.derivLp"

[[node]]
id = "ContDiffMapIcc.coeFn_derivLp"

[[node]]
id = "ContDiffMapIcc.derivLp_add"

[[node]]
id = "ContDiffMapIcc.derivLp_smul"

[[node]]
id = "ContDiffMapIcc.hasWeakIteratedDerivOn_derivLp"

[[node]]
id = "ContDiffMapIcc.toSobolevIntervalₗ"

[[node]]
id = "ContDiffMapIcc.deriv_toSobolevIntervalₗ"

[[node]]
id = "ContDiffMapIcc.norm_derivLp_le"

[[node]]
id = "ContDiffMapIcc.norm_toSobolevIntervalₗ_le"

[[node]]
id = "ContDiffMapIcc.toSobolevInterval"

[[node]]
id = "ContDiffMapIcc.deriv_toSobolevInterval"

[[node]]
id = "ContDiffMapIcc.fn_toSobolevInterval_ae_eq"

[[node]]
id = "ContDiffMapIcc.norm_toSobolevInterval_le"

[[node]]
id = "ContDiffMapIcc.toSobolevInterval_injective"

[[node]]
id = "eq_add_integral_deriv_of_piecewise"

[[node]]
id = "memSobolevInterval_of_piecewise_contDiffOn"

[[node]]
id = "abs_intervalIntegral_le_sqrt_mul_sqrt"

[[node]]
id = "SobolevInterval.exists_contDiff_ae_eq"

[[node]]
id = "SobolevInterval.norm_deriv_sq_eq_integral"

[[node]]
id = "SobolevInterval.seminorm_sq_eq_integral"

[[node]]
id = "SobolevInterval.intervalIntegrable_deriv"

[[node]]
id = "SobolevInterval.intervalIntegrable_deriv_sq"

[[node]]
id = "SobolevInterval.toContinuousMap_injective"

[[node]]
id = "SobolevInterval.exists_toContinuousMap_eq"

[[node]]
id = "SobolevInterval.norm_le_add_norm_deriv"

[[node]]
id = "ContDiffMapIcc.denseRange_toSobolevInterval_one"

[[node]]
id = "SobolevInterval.inner_eq_intervalIntegral"

[[node]]
id = "SobolevInterval.evalCLM"

[[node]]
id = "SobolevInterval.evalCLM_apply"

[[node]]
id = "SobolevInterval.rep_finset_sum"
