namespace = "ContinuousLinearMap"

[[node]]
id = "IsTopEigenpair"

[[node]]
id = "IsSymmetric.exists_isTopEigenpair"

[[node]]
id = "IsSymmetric.eigenvalueSeq"

[[node]]
id = "IsSymmetric.eigenvalueSeq_antitone"

[[node]]
id = "IsSymmetric.tendsto_eigenvalueSeq_zero"

[[node]]
id = "IsSymmetric.abs_eigenvalueSeq_zero"

[[node]]
id = "IsSymmetric.eigenvector"

[[node]]
id = "IsSymmetric.apply_eigenvector"

[[node]]
id = "IsSymmetric.orthonormal_eigenvector"

[[node]]
id = "IsSymmetric.orthogonal_span_range_eigenvector_le_ker"

[[node]]
id = "IsSymmetric.eigenvectorHilbertBasis"

[[node]]
id = "IsSymmetric.coe_eigenvectorHilbertBasis"

[[node]]
id = "IsSymmetric.apply_eigenvectorHilbertBasis"
