[[node]]
id = "exists_isBestApprox_of_isClosed"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 5.2"

[[node]]
id = "existsUnique_isBestApprox"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 5.2"

[[node]]
id = "isBestApprox_bestApprox_of_isClosed"

[[node]]
id = "bestApprox_mem"

[[node]]
id = "inner_sub_bestApprox_le_zero"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 5.2"

[[node]]
id = "bestApprox_eq_iff"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 5.2"

[[node]]
id = "inner_bestApprox_sub_nonneg"

[[node]]
id = "norm_bestApprox_sub_bestApprox_le"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 5.3"

[[node]]
id = "lipschitzWith_bestApprox"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 5.3"

[[node]]
id = "bestApprox_eq_starProjection"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Corollary 5.4"
