namespace = "SimpleGraph"

[[node]]
id = "greedyColoring"

[[node]]
id = "greedyColoring_isColoring"

[[node]]
id = "greedyColoring_le_maxDegree"

[[node]]
id = "colorable_maxDegree_add_one"

[[node]]
id = "greedyColoring_le_one_of_isBipartite"
