namespace = "QuarteroniSaccoSaleri.Chapter04"

[[node]]
id = "affineStep"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.2'

[[node]]
id = "toLp_affineStep"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.2'

[[node]]
id = "toLp_affineStep_iterate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.2'

[[node]]
id = "definition_4_1"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 4.1'

[[node]]
id = "definition_4_1_iff"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 4.1'

[[node]]
id = "example_4_1_consistent"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Example 4.1'

[[node]]
id = "example_4_1_iterate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Example 4.1'

[[node]]
id = "example_4_1_not_tendsto"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Example 4.1'

[[node]]
id = "example_4_1_tendsto"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Example 4.1'

[[node]]
id = "theorem_4_1"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Theorem 4.1'

[[node]]
id = "equation_4_4"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.4'

[[node]]
id = "affineStep_iterate_sub_iterate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.4'

[[node]]
id = "complexSpectralRadius_lt_one_of_forall_tendsto"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Theorem 4.1'

[[node]]
id = "tendsto_of_algebraNorm_lt_one"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Theorem 4.1'

[[node]]
id = "definition_4_2_factor"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 4.2'

[[node]]
id = "definition_4_2_averageFactor"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 4.2'

[[node]]
id = "definition_4_2_rate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 4.2'

[[node]]
id = "definition_4_2_eq"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 4.2'

[[node]]
id = "asymptoticConvergenceRate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.5'

[[node]]
id = "equation_4_5"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.5'

[[node]]
id = "equation_4_5_factor"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.5'

[[node]]
id = "equation_4_5_symm"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 4.5'

[[node]]
id = "exercise_4_1"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Exercise 4.1'
