namespace = "SaadSparse.Chapter14"

[[node]]
id = "interfaceRestrictMatrix"

[[node]]
id = "interfaceProlongMatrix"

[[node]]
id = "inducedPreconditioner"

[[node]]
id = "inducedPreconditioner_eq_schurComplement"

[[node]]
id = "proposition_14_10"

[[node]]
id = "proposition_14_10_of_isILU"

[[node]]
id = "probeVec"

[[node]]
id = "mulVec_probeVec_apply"

[[node]]
id = "probing_eq"
