namespace = "AtkinsonHan"

[[node]]
id = "Chapter09.theorem_9_2_1"

[[node]]
id = "DiscreteInfSup"

[[node]]
id = "InfSupCondition"

[[node]]
id = "PetrovGalerkinProblem"

[[node]]
id = "infSupValue"

[[node]]
id = "Chapter09.remark_9_2_2"
