namespace = "AtkinsonHan.Chapter03"

[[node]]
id = "IsDirectSum"

[[node]]
id = "IsOrthogonalProjectionOperator"

[[node]]
id = "IsProjectionOperator"

[[node]]
id = "example_3_6_7"

[[node]]
id = "exercise_3_6_7"

[[node]]
id = "proposition_3_6_2"

[[node]]
id = "proposition_3_6_9_a"

[[node]]
id = "proposition_3_6_9_b"

[[node]]
id = "proposition_3_6_9_c"

[[node]]
id = "proposition_3_6_9_d"

[[node]]
id = "proposition_3_6_9_e"

[[node]]
id = "example_3_6_5"

[[node]]
id = "example_3_6_6"

[[node]]
id = "example_3_6_8"

[[node]]
id = "example_3_6_8_l2"

[[node]]
id = "exercise_3_6_1"

[[node]]
id = "proposition_3_6_9_c'"
