namespace = "AtkinsonHan.Chapter03"

[[node]]
id = "exists_not_tendsto_of_not_bddAbove"

[[node]]
id = "lebesgue_lemma"

[[node]]
id = "theorem_3_7_1"

[[node]]
id = "theorem_3_7_2"
source = "Atkinson-Han, Theoretical Numerical Analysis, Theorem 3.7.2"

[[node]]
id = "theorem_3_7_3"

[[node]]
id = "theorem_3_7_3_confluent"

[[node]]
id = "equation_3_7_6"

[[node]]
id = "equation_3_7_8"

[[node]]
id = "equation_3_7_9"

[[node]]
id = "equation_3_7_11"

[[node]]
id = "equation_3_7_12"

[[node]]
id = "not_equation_3_7_20"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.7.20)"

[[node]]
id = "norm_trigInterpCLM_bound"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.7.20); Rivlin, An Introduction to the Approximation of Functions, p. 13"

[[node]]
id = "equation_3_7_13"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.7.13)"

[[node]]
id = "equation_3_7_14"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.7.14)"

[[node]]
id = "equation_3_7_15"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.7.15)-(3.7.16)"

[[node]]
id = "equation_3_7_17"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.7.17); (2.2.8)"

[[node]]
id = "chebyshevMeasure"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.5.8), Example 3.7.4"

[[node]]
id = "chebyshevOrthonormal"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.5.9), Example 3.7.4"

[[node]]
id = "chebyshevKernel"
source = "Atkinson-Han, Theoretical Numerical Analysis, Example 3.7.4; Rivlin, Chebyshev Polynomials, p. 133"

[[node]]
id = "chebyshevProj"
source = "Atkinson-Han, Theoretical Numerical Analysis, (3.5.2), Example 3.7.4"

[[node]]
id = "example_3_7_4"
source = "Atkinson-Han, Theoretical Numerical Analysis, Example 3.7.4"

[[node]]
id = "equation_3_7_5"

[[node]]
id = "exists_not_tendsto_fourierProj"

[[node]]
id = "equation_3_7_19"
