namespace = "AtkinsonHan.Chapter03"

[[node]]
id = "corollary_3_4_2"

[[node]]
id = "equation_3_4_6"

[[node]]
id = "exercise_3_4_8"

[[node]]
id = "hilbertBasis_expansion"

[[node]]
id = "lemma_3_4_1"

[[node]]
id = "projConvex"

[[node]]
id = "proposition_3_4_4"

[[node]]
id = "theorem_3_4_3"

[[node]]
id = "theorem_3_4_5"

[[node]]
id = "theorem_3_4_6"

[[node]]
id = "theorem_3_4_7"

[[node]]
id = "proposition_3_4_4'"
