[[node]]
id = "Matrix.pfc_conj"

[[node]]
id = "Matrix.pfc_diagonal"

[[node]]
id = "Matrix.pfc_blockDiagonal'"

[[node]]
id = "Matrix.pfc_fromBlocks_zero"

[[node]]
id = "Matrix.pfc_reindex"

[[node]]
id = "Matrix.pfc_jordanBlock"

[[node]]
id = "Matrix.pfc_jordanBlock_apply"

[[node]]
id = "Matrix.pfc_conj_jordanForm"

[[node]]
id = "Matrix.pfc_transpose"

[[node]]
id = "Matrix.minpoly_transpose"

[[node]]
id = "Matrix.pfc_map_conj"

[[node]]
id = "Matrix.pfc_map_ofReal_of_conj"

[[node]]
id = "AlgEquiv.map_pfc"
