[[node]]
id = "Matrix.spectrum_exp_smul"

[[node]]
id = "Matrix.l2_opNorm_exp_smul_le_of_schur"

[[node]]
id = "Matrix.exp_spectralAbscissa_mul_le_l2_opNorm_exp_smul"

[[node]]
id = "Matrix.l2_opNorm_exp_smul_add_sub_le"

[[node]]
id = "Matrix.isStarNormal_exp_smul"

[[node]]
id = "Matrix.l2_opNorm_exp_smul_of_isStarNormal"

[[node]]
id = "Matrix.expCondNumber_eq_of_isStarNormal"
