
[[node]]
id = "Matrix.IsPolarDecomposition.eq_pfc_sqrt"

[[node]]
id = "Matrix.newtonPolarIterate"
deps = []

[[node]]
id = "Matrix.newtonPolarIterate_eq"

[[node]]
id = "Matrix.tendsto_newtonPolarIterate"

[[node]]
id = "Matrix.matrixSign_hermitianDilation"

[[node]]
id = "Matrix.frobenius_norm_polar_sub_le"

[[node]]
id = "Matrix.PosDef.newtonPolarIterate"

[[node]]
id = "Matrix.l2_opNorm_newtonPolarIterate_sub"

[[node]]
id = "Matrix.newtonPolarIterate_succ_sub_one"

[[node]]
id = "Matrix.l2_opNorm_newtonPolarIterate_succ_sub_one_le"

[[node]]
id = "Matrix.frobenius_norm_le_of_mul_add_mul_eq"

[[node]]
id = "Matrix.IsPolarDecomposition.frobenius_norm_sub_le"

[[node]]
id = "Matrix.IsPolarDecomposition.posSemidef_sub_iInf_colSingularValues"

[[node]]
id = "Matrix.IsPolarDecomposition.frobenius_norm_sub_le_div_iInf_colSingularValues"

[[node]]
id = "Matrix.PosSemidef.trace_mul_le_trace"

[[node]]
id = "Matrix.trace_le_card_sub_two_of_det_eq_neg_one"

[[node]]
id = "Matrix.trace_mul_one_sub_ge"

[[node]]
id = "Matrix.frobenius_norm_one_sub_le_of_mul_add_mul_eq"

[[node]]
id = "Matrix.IsPolarDecomposition.frobenius_norm_sub_le_of_det_mul_pos"

[[node]]
id = "Matrix.IsPolarDecomposition.exists_posSemidef_sub_sortedSingularValues"
