namespace = "Polynomial"

[[node]]
id = "legendre_eval_neg_one"

[[node]]
id = "legendreEnergy"

[[node]]
id = "derivative_legendreEnergy"

[[node]]
id = "eval_legendreEnergy_one"

[[node]]
id = "eval_legendreEnergy_neg_one"

[[node]]
id = "deriv_eval_legendreEnergy"

[[node]]
id = "monotoneOn_eval_legendreEnergy"

[[node]]
id = "antitoneOn_eval_legendreEnergy"

[[node]]
id = "eval_legendreEnergy_le_one"

[[node]]
id = "eval_legendreEnergy_zero_le"

[[node]]
id = "eval_legendre_sq_le_one"

[[node]]
id = "abs_eval_legendre_le_one"

[[node]]
id = "one_le_eval_legendre_zero_sq"

[[node]]
id = "inv_le_eval_legendreEnergy_zero"

[[node]]
id = "inv_le_eval_legendre_sq"

[[node]]
id = "_root_.Quadrature.nodal_eq_lobattoNodal_of_isExactOnMeasure"

[[node]]
id = "_root_.Quadrature.isInterpolatoryMeasure_of_isExactOnMeasure_two_mul_sub_one"

[[node]]
id = "_root_.Quadrature.discreteInner_add_smul_self"

[[node]]
id = "_root_.Quadrature.integral_eval_add_C_mul_sq"

[[node]]
id = "_root_.Quadrature.discreteInner_self_legendre_eq_and_integral_sq_eq"

[[node]]
id = "_root_.Quadrature.integral_sq_le_discreteInner_self_legendre"

[[node]]
id = "_root_.Quadrature.discreteInner_self_legendre_le_three_mul_integral_sq"
