namespace = "AtkinsonHan.Chapter14"

[[node]]
id = "equation_14_3_3"

[[node]]
id = "hyperinterpolation"

[[node]]
id = "hyperinterpolation_mem"

[[node]]
id = "hyperinterpolation_add"

[[node]]
id = "hyperinterpolation_smul"

[[node]]
id = "equation_14_3_5"

[[node]]
id = "equation_14_3_5_idem"

[[node]]
id = "equation_14_3_1"
source = "Atkinson–Han, Theoretical Numerical Analysis, (14.3.1)"
