namespace = "Matrix"

[[node]]
id = "elimMultipliers"

[[node]]
id = "elimMul"

[[node]]
id = "gaussTransform"

[[node]]
id = "gaussTransform_mul"

[[node]]
id = "elimStep"

[[node]]
id = "gemStage"

[[node]]
id = "gemStage_succ_eq_gaussTransform_mul"

[[node]]
id = "gemStage_apply_of_le"

[[node]]
id = "gemStage_apply_eq_zero_of_lt"

[[node]]
id = "gemLower"

[[node]]
id = "isUnitLowerTriangular_gemLower"

[[node]]
id = "gemLowerStage"

[[node]]
id = "gemLowerStage_mul_gemStage"

[[node]]
id = "isLU_gemLower_gemStage"

[[node]]
id = "isLU_leadingPrincipalSubmatrix_gemStage"

[[node]]
id = "gemStage_pivots_ne_zero_iff"

[[node]]
id = "luPacked"

[[node]]
id = "luPacked_of_le"

[[node]]
id = "luPacked_of_lt"

[[node]]
id = "luLower"

[[node]]
id = "luUpper"

[[node]]
id = "luPacked_eq"

[[node]]
id = "isLU_luLower_luUpper"

[[node]]
id = "luLower_eq_gemLower"

[[node]]
id = "croutLower"

[[node]]
id = "croutUpper"

[[node]]
id = "croutLower_mul_croutUpper"
