[[node]]
id = "Jackson.angle"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 3.7.1"

[[node]]
id = "Jackson.coeff"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 3.7.1"

[[node]]
id = "Jackson.kernel"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 3.7.1"

[[node]]
id = "Jackson.kernel_eq_sum"

[[node]]
id = "Jackson.integral_kernel"

[[node]]
id = "Jackson.integral_cos_mul_kernel"

[[node]]
id = "Jackson.integral_sq_mul_kernel_le"

[[node]]
id = "Jackson.integral_abs_mul_kernel_le"

[[node]]
id = "Jackson.approx"

[[node]]
id = "Jackson.approx_mem"

[[node]]
id = "Jackson.approx_coe"

[[node]]
id = "Jackson.abs_sub_approx_le_of_holder"

[[node]]
id = "Jackson.infDist_le_of_holder"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 3.7.1 (the case k = 0)"

[[node]]
id = "Jackson.hasDerivAt_approx"

[[node]]
id = "Jackson.rem"

[[node]]
id = "Jackson.sub_iterate_rem_mem"

[[node]]
id = "Jackson.abs_iterate_rem_le"

[[node]]
id = "Jackson.infDist_le_of_holder_deriv"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 3.7.1"

[[node]]
id = "Jackson.infDist_le_of_holder_deriv'"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 3.7.1"

[[node]]
id = "Jackson.exists_degree_le_eval_cos"

[[node]]
id = "Jackson.infDist_polyLE_le_infDist_trigPolyLE"

[[node]]
id = "Jackson.infDist_polyLE_le_of_holder"
source = "Atkinson-Han, Theoretical Numerical Analysis, Theorem 3.7.2 (the case k = 0)"

[[node]]
id = "Jackson.exists_derivative_eq"

[[node]]
id = "Jackson.infDist_restrictIcc_le_step"

[[node]]
id = "Jackson.infDist_restrictIcc_le_prod"

[[node]]
id = "Jackson.infDist_le_of_holder_poly"
source = "Atkinson-Han, Theoretical Numerical Analysis, Theorem 3.7.2"
