namespace = "Preconditioner.Chebyshev"

[[node]]
id = "State"

[[node]]
id = "step"

[[node]]
id = "iterate"

[[node]]
id = "residual_iterate_eq"

[[node]]
id = "norm_residual_iterate_le"

[[node]]
id = "norm_residual_minRes_le_norm_residual_iterate"
