namespace = "IntegralOperator"

[[node]]
id = "fredholm"

[[node]]
id = "urysohn"

[[node]]
id = "kernelCLM"

[[node]]
id = "norm_kernelCLM"

[[node]]
id = "norm_fredholm"

[[node]]
id = "lipschitzWith_urysohn"

[[node]]
id = "urysohnDerivKernel"

[[node]]
id = "hasFDerivAt_urysohn"

[[node]]
id = "volterra"

[[node]]
id = "volterraCLM"

[[node]]
id = "norm_iterate_volterra_sub_le"

[[node]]
id = "exists_contractingWith_iterate_volterra"

[[node]]
id = "norm_volterraCLM_pow_le"

[[node]]
id = "Bielecki"

[[node]]
id = "Bielecki.norm_le_norm_equiv"

[[node]]
id = "Bielecki.exp_mul_norm_equiv_le_norm"

[[node]]
id = "volterraBielecki"

[[node]]
id = "contractingWith_volterra_bielecki"
