namespace = "IntegralOperator"

[[node]]
id = "fredholm"

[[node]]
id = "urysohn"

[[node]]
id = "kernelCLM"

[[node]]
id = "norm_kernelCLM"

[[node]]
id = "norm_fredholm"

[[node]]
id = "lipschitzWith_urysohn"

[[node]]
id = "urysohnDerivKernel"

[[node]]
id = "hasFDerivAt_urysohn"

[[node]]
id = "volterra"

[[node]]
id = "volterraCLM"

[[node]]
id = "norm_iterate_volterra_sub_le"

[[node]]
id = "exists_contractingWith_iterate_volterra"

[[node]]
id = "norm_volterraCLM_pow_le"

[[node]]
id = "Bielecki"

[[node]]
id = "Bielecki.norm_le_norm_equiv"

[[node]]
id = "Bielecki.exp_mul_norm_equiv_le_norm"

[[node]]
id = "volterraBielecki"

[[node]]
id = "contractingWith_volterra_bielecki"

[[node]]
id = "abs_kernelCLM_sub_kernelCLM_le"

[[node]]
id = "isCompactOperator_kernelCLM"

[[node]]
id = "isCompactOperator_fredholm"

[[node]]
id = "degenerateKernel"

[[node]]
id = "kernelCLM_degenerateKernel"

[[node]]
id = "range_kernelCLM_degenerateKernel_le"

[[node]]
id = "finiteDimensional_range_kernelCLM_degenerateKernel"

[[node]]
id = "norm_kernelCLM_degenerateKernel_le"

[[node]]
id = "regionMeasure"

[[node]]
id = "measureReal_iccMeasure_univ"

[[node]]
id = "iccToLp"

[[node]]
id = "norm_iccToLp_le"
