namespace = "SecondKind"

[[node]]
id = "sub_projection_eq"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.1.27)"

[[node]]
id = "exists_equiv_of_projection"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 12.1.2"

[[node]]
id = "norm_smul_sub_le_of_projection"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.1.24)"

[[node]]
id = "norm_sub_le_of_projection"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 12.1.2"

[[node]]
id = "exists_equiv_smul_sub_comp_comm"
source = "Atkinson–Han, Theoretical Numerical Analysis, Lemma 12.3.1"

[[node]]
id = "isUnit_smul_sub_comp_comm"
source = "Atkinson–Han, Theoretical Numerical Analysis, Lemma 12.3.1"

[[node]]
id = "iterated"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.3.1)"

[[node]]
id = "apply_iterated"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.3.2)"

[[node]]
id = "smul_sub_comp_iterated"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.3.3)"

[[node]]
id = "iterated_error_eq"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.3.11)"

[[node]]
id = "exists_equiv_of_isCompactOperator"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 12.4.3"

[[node]]
id = "norm_sub_le"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.4.24)"

[[node]]
id = "twoGridStep"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.6.20)–(12.6.22)"

[[node]]
id = "twoGridOperator"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.6.28)"

[[node]]
id = "twoGrid_error_eq"
source = "Atkinson–Han, Theoretical Numerical Analysis, (12.6.27)"

[[node]]
id = "tendsto_twoGridIterate"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 12.6.1"

[[node]]
id = "eventually_norm_twoGridOperator_lt_one"
source = "Atkinson–Han, Theoretical Numerical Analysis, Theorem 12.6.1"
