/-
Upstreaming candidate: general material with no numerical-analysis-specific content, written
to Mathlib conventions with a view to contributing it to Mathlib.
Natural home: `Mathlib.RingTheory.Adjoin.Polynomial.Basic`, beside
`Polynomial.aeval_mem_adjoin_singleton`.
Keep it free of dependencies on the rest of `Numlib` other than other upstreaming candidates.
-/
import Mathlib.RingTheory.Adjoin.Polynomial.Basic

/-!
# Polynomials in an element commute with what the element commutes with

If `x` commutes with `a`, it commutes with every polynomial `p(a)` (`Commute.aeval_right`), and
symmetrically (`Commute.aeval_left`): `p(a)` lies in the subalgebra generated by `a`, whose
elements all commute with `x` (`Algebra.commute_of_mem_adjoin_singleton_of_commute`). This is the
step behind every argument that a matrix function or a Padé approximant commutes with the
matrices its argument commutes with.
-/

open Polynomial

variable {R A : Type*} [CommSemiring R] [Semiring A] [Algebra R A] {x a : A}

/-- A polynomial in `a` commutes with everything `a` commutes with. -/
theorem Commute.aeval_right (h : Commute x a) (p : R[X]) : Commute x (aeval a p) :=
  Algebra.commute_of_mem_adjoin_singleton_of_commute (aeval_mem_adjoin_singleton R a) h

/-- A polynomial in `a` commutes with everything `a` commutes with. -/
theorem Commute.aeval_left (h : Commute a x) (p : R[X]) : Commute (aeval a p) x :=
  (h.symm.aeval_right p).symm
