import Mathlib.Topology.Bases
import Mathlib.Topology.Order

/-!
# Brezis §3.1: the coarsest topology for which a collection of maps becomes continuous

Surface file for Haim Brezis, *Functional Analysis, Sobolev Spaces and Partial Differential
Equations*, Universitext, Springer, 2011, §3.1. Everything is Mathlib's: the topology of
Problem 1 is `⨅ i, TopologicalSpace.induced (φ i) inferInstance`, named `weakestTopology` here
so that §3.2 and §3.4 can define `σ(E, E*)` and `σ(E*, E)` by the book's words; Problem 2's
construction is `TopologicalSpace.generateFrom` of the preimages
(`TopologicalSpace.generateFrom_iUnion_isOpen`); Lemma 3.1 is
`TopologicalSpace.isTopologicalBasis_of_subbasis`; Proposition 3.1 is `nhds_iInf` with
`nhds_induced`; Proposition 3.2 is `continuous_iInf_rng` with `continuous_induced_rng`.

## Main results

* `weakestTopology`, `continuous_weakestTopology`, `weakestTopology_le` — the coarsest topology
  making the `φ i` continuous, and its two defining properties.
* `weakestTopology_eq_generateFrom` — Problem 2: it is generated by the sets `φ i ⁻¹' ω`.
* `lemma_3_1` — the finite intersections of a subbasis form a basis.
* `proposition_3_1` — a sequence converges iff its images under every `φ i` converge.
* `proposition_3_2` — a map into `X` is continuous iff its compositions with the `φ i` are.

Remark 1 is discussion. Note that in Mathlib's order on `TopologicalSpace X`, `t ≤ s` means
that `t` is *finer* than `s`, so "the coarsest topology making the `φ i` continuous" is the
*greatest* such topology, `⨅ i, induced (φ i) _`.
-/

open Filter Topology TopologicalSpace

namespace Brezis.Chapter03

variable {X : Type*} {ι : Type*} {Y : ι → Type*} [∀ i, TopologicalSpace (Y i)]

/-- **Problem 1 of §3.1.** The coarsest (weakest, initial) topology on a set `X` for which
every map of a family `φ i : X → Y i` into topological spaces is continuous:
`⨅ i, TopologicalSpace.induced (φ i) _`. -/
@[instance_reducible]
def weakestTopology (φ : ∀ i, X → Y i) : TopologicalSpace X :=
  ⨅ i, TopologicalSpace.induced (φ i) inferInstance

/-- Every `φ i` is continuous for `weakestTopology φ`. -/
theorem continuous_weakestTopology (φ : ∀ i, X → Y i) (i : ι) :
    Continuous[weakestTopology φ, _] (φ i) :=
  continuous_iInf_dom continuous_induced_dom

/-- `weakestTopology φ` is the cheapest such topology: any topology `t` on `X` making every
`φ i` continuous has more open sets, `t ≤ weakestTopology φ`. -/
theorem weakestTopology_le (φ : ∀ i, X → Y i) {t : TopologicalSpace X}
    (h : ∀ i, Continuous[t, _] (φ i)) : t ≤ weakestTopology φ :=
  le_iInf fun i => continuous_iff_le_induced.1 (h i)

/-- **Problem 2 of §3.1, solved.** The coarsest topology in which every set `φ i ⁻¹' ω`, `ω`
open in `Y i`, is open is `weakestTopology φ`. -/
theorem weakestTopology_eq_generateFrom (φ : ∀ i, X → Y i) :
    weakestTopology φ =
      generateFrom {U | ∃ (i : ι) (ω : Set (Y i)), IsOpen ω ∧ U = φ i ⁻¹' ω} := by
  rw [weakestTopology, ← generateFrom_iUnion_isOpen]
  congr 1
  ext U
  simp only [Set.mem_iUnion, Set.mem_ofPred_eq, isOpen_induced_iff]
  constructor
  · rintro ⟨i, ω, hω, rfl⟩
    exact ⟨i, ω, hω, rfl⟩
  · rintro ⟨i, ω, hω, rfl⟩
    exact ⟨i, ω, hω, rfl⟩

/-- **Lemma 3.1.** The family of arbitrary unions of finite intersections of the sets of a
subbasis `s` is stable under finite intersections: the finite intersections of `s` form a
basis of the topology generated by `s`. -/
theorem lemma_3_1 (s : Set (Set X)) :
    @IsTopologicalBasis X (generateFrom s)
      ((fun f => ⋂₀ f) '' {f : Set (Set X) | f.Finite ∧ f ⊆ s}) :=
  @isTopologicalBasis_of_subbasis X (generateFrom s) s rfl

/-- **Proposition 3.1.** A sequence `xₙ` converges to `x` for `weakestTopology φ` iff
`φ i (xₙ) → φ i x` for every `i`. -/
theorem proposition_3_1 (φ : ∀ i, X → Y i) (x : ℕ → X) (a : X) :
    Tendsto x atTop (@nhds X (weakestTopology φ) a) ↔
      ∀ i, Tendsto (fun n => φ i (x n)) atTop (𝓝 (φ i a)) := by
  unfold weakestTopology
  rw [nhds_iInf, tendsto_iInf]
  refine forall_congr' fun i => ?_
  rw [nhds_induced, tendsto_comap_iff]
  rfl

/-- **Proposition 3.2.** Let `Z` be a topological space and `ψ : Z → X`. Then `ψ` is continuous
for `weakestTopology φ` iff `φ i ∘ ψ` is continuous for every `i`. -/
theorem proposition_3_2 (φ : ∀ i, X → Y i) {Z : Type*} [TopologicalSpace Z] (ψ : Z → X) :
    Continuous[_, weakestTopology φ] ψ ↔ ∀ i, Continuous (φ i ∘ ψ) := by
  unfold weakestTopology
  rw [continuous_iInf_rng]
  exact forall_congr' fun i => continuous_induced_rng

end Brezis.Chapter03
