namespace = "AtkinsonHan"

[[node]]
id = "BilinForm.IsEllipticWith.exists_pos"

[[node]]
id = "BilinForm₂.IsBoundedWith"

[[node]]
id = "BilinForm₂.norm_toCLM_le"

[[node]]
id = "BilinForm₂.toCLM"

[[node]]
id = "BilinForm₂.toCLM_apply"

[[node]]
id = "Chapter08.exercise_8_7_1"

[[node]]
id = "Chapter08.theorem_8_7_1"
