namespace = "Arnoldi"

[[node]]
id = "apply_sum"

[[node]]
id = "apply_vec"

[[node]]
id = "apply_vec_of_le"

[[node]]
id = "coe_orthonormalBasis_apply"

[[node]]
id = "coeff"

[[node]]
id = "coeff_eq_zero_of_adjoint_mem"

[[node]]
id = "coeff_eq_zero_of_lt"

[[node]]
id = "coeff_succ_self"

[[node]]
id = "coeff_succ_self_eq_zero_iff"

[[node]]
id = "eq_sum_inner_smul_vec"

[[node]]
id = "hessenberg"

[[node]]
id = "hessenbergSq"

[[node]]
id = "hessenbergSq_eq_toMatrix_compression"

[[node]]
id = "hessenberg_isUpperHessenbergRect"

[[node]]
id = "inner_vec_eq_zero"

[[node]]
id = "norm_vec_eq_one_of_lt_grade"

[[node]]
id = "orthonormal"

[[node]]
id = "orthonormalBasis"

[[node]]
id = "span_vec"

[[node]]
id = "starProjection_apply_vec"

[[node]]
id = "vec"

[[node]]
id = "vec_eq_zero_iff"

[[node]]
id = "vec_mem_orthogonal"

[[node]]
id = "vec_mem_subspace"

[[node]]
id = "vec_succ_eq"

[[node]]
id = "vec_zero"

[[node]]
id = "w"

[[node]]
id = "w_eq_sub_starProjection"
