[[node]]
id = "BCG.NoBreakdown"

[[node]]
id = "BCG.State"

[[node]]
id = "BCG.alpha"

[[node]]
id = "BCG.beta"

[[node]]
id = "BCG.direction"

[[node]]
id = "BCG.dualDirection"

[[node]]
id = "BCG.dualResidual"

[[node]]
id = "BCG.inner_apply_direction_eq_zero_of_mem_subspace"

[[node]]
id = "BCG.inner_dualDirection_apply_direction_eq_zero"

[[node]]
id = "BCG.inner_residual_dualResidual_eq_zero"

[[node]]
id = "BCG.inner_residual_eq_zero_of_mem_subspace"

[[node]]
id = "BCG.isPetrovGalerkin"

[[node]]
id = "BCG.iterate"

[[node]]
id = "BCG.iterate_x_sub_mem"

[[node]]
id = "BCG.residual"

[[node]]
id = "BCG.residual_eq"

[[node]]
id = "BCG.step"

[[node]]
id = "BCG.subspace_le_span_dualDirection"

[[node]]
id = "BCG.subspace_le_span_dualResidual"

[[node]]
id = "BiLanczos.NoBreakdown"

[[node]]
id = "BiLanczos.NoSeriousBreakdown"

[[node]]
id = "BiLanczos.State"

[[node]]
id = "BiLanczos.alpha"

[[node]]
id = "BiLanczos.apply_dualVec"

[[node]]
id = "BiLanczos.apply_vec"

[[node]]
id = "BiLanczos.beta"

[[node]]
id = "BiLanczos.beta_succ"

[[node]]
id = "BiLanczos.coeff"

[[node]]
id = "BiLanczos.delta"

[[node]]
id = "BiLanczos.delta_succ"

[[node]]
id = "BiLanczos.delta_succ_eq_zero_iff"

[[node]]
id = "BiLanczos.dualVec"

[[node]]
id = "BiLanczos.dualVec_mem_subspace"

[[node]]
id = "BiLanczos.dualVec_succ"

[[node]]
id = "BiLanczos.hessenbergRelation"

[[node]]
id = "BiLanczos.inner_aeval_map_eq"

[[node]]
id = "BiLanczos.inner_apply_eq"

[[node]]
id = "BiLanczos.inner_dualVec_apply_vec"

[[node]]
id = "BiLanczos.inner_dualVec_vec"

[[node]]
id = "BiLanczos.inner_dualVec_vec_succ"

[[node]]
id = "BiLanczos.inner_pow_apply_eq"

[[node]]
id = "BiLanczos.inner_vec_dualVec"

[[node]]
id = "BiLanczos.span_dualVec"

[[node]]
id = "BiLanczos.span_vec"

[[node]]
id = "BiLanczos.state"

[[node]]
id = "BiLanczos.step"

[[node]]
id = "BiLanczos.vec"

[[node]]
id = "BiLanczos.vec_mem_subspace"

[[node]]
id = "BiLanczos.vec_succ"

[[node]]
id = "BiLanczos.zeta"

[[node]]
id = "QMR.IsQuasiMinRes"

[[node]]
id = "QMR.norm_quasiResidual_eq_norm_gamma"

[[node]]
id = "QMR.norm_residual_le"

[[node]]
id = "QMR.norm_residual_le_norm_quasiResidual"

[[node]]
id = "QMR.quasiResidual"
