namespace = "Arnoldi"

[[node]]
id = "IsPerturbedRelation"

[[node]]
id = "hessenbergRelation_isPerturbedRelation"

[[node]]
id = "IsPerturbedRelation.residual_eq"

[[node]]
id = "IsPerturbedRelation.norm_residual_sub_le"

[[node]]
id = "IsPerturbedRelation.abs_norm_sq_sub_sum_le"
