namespace = "SaadSparse.Ch06"

[[node]]
id = "C"

[[node]]
id = "C_rec"

[[node]]
id = "Ccomplex"

[[node]]
id = "Chat"

[[node]]
id = "eq_6_109"

[[node]]
id = "eq_6_110"

[[node]]
id = "eq_6_111"

[[node]]
id = "eq_6_112"

[[node]]
id = "thm_6_25_value"
