namespace = "Brezis.Chapter02"

[[node]]
id = "proposition_2_14"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 2.14"

[[node]]
id = "corollary_2_15"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Corollary 2.15"

[[node]]
id = "theorem_2_16"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 2.16"
