namespace = "AtkinsonHan.Ch02"

[[node]]
id = "IsSublinear"

[[node]]
id = "corollary_2_5_6"

[[node]]
id = "corollary_2_5_7"

[[node]]
id = "theorem_2_5_2"

[[node]]
id = "theorem_2_5_5"

[[node]]
id = "theorem_2_5_8"
