namespace = "QuarteroniSaccoSaleri.Chapter05"

[[node]]
id = "powerIterate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.17)'

[[node]]
id = "equation_5_18"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.18)'

[[node]]
id = "theorem_5_6"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Theorem 5.6'

[[node]]
id = "theorem_5_6_rayleigh"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Theorem 5.6'

[[node]]
id = "equation_5_23"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.23)'

[[node]]
id = "equation_5_24"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.24)'

[[node]]
id = "inverseIterate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.28)'

[[node]]
id = "inverseIterate_tendsto"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.28)'

[[node]]
id = "powerIterate_of_eq"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 5.3.3'

[[node]]
id = "rayleighQuotient"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.17)'

[[node]]
id = "powerIterate_eq_krylov"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.17)'

[[node]]
id = "norm_smul_powerIterate"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.22)'

[[node]]
id = "inverseIterate_eq_krylov"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.28)'

[[node]]
id = "sum_repr_erase_mem_iSup_maxGenEigenspace"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (5.19)'

[[node]]
id = "isUnit_sub_smul_one_of_notMem_spectrum"
