namespace = "Stationary"

[[node]]
id = "contractingWith"

[[node]]
id = "exists_norm_iterate_sub_le"

[[node]]
id = "forall_tendsto_iff_spectralRadius_lt_one"

[[node]]
id = "isUnit_one_sub_of_spectralRadius_lt_one"

[[node]]
id = "norm_iterate_sub_le"

[[node]]
id = "spectralRadius_lt_one_of_forall_tendsto"

[[node]]
id = "step"

[[node]]
id = "step_fixed_iff"

[[node]]
id = "step_iterate_sub"

[[node]]
id = "tendsto_of_spectralRadius_lt_one"
