[[node]]
id = "Submodule.exists_dual_eq_zero_of_notMem"

[[node]]
id = "separableSpace_of_separableSpace_strongDual"

[[node]]
id = "exists_seq_strongDual_norming_of_separableSpace"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Problem 10"

[[node]]
id = "AbsConvex.exists_norm_apply_le_one_of_isClosed_of_notMem"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 2.16 (formula (25))"
