[[node]]
id = "NormedSpace.isReflexive_of_uniformConvexSpace"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 3.31"

[[node]]
id = "NormedSpace.instIsReflexiveOfUniformConvexSpace"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Theorem 3.31"
