[[node]]
id = "tendsto_toWeakSpace_iff"

[[node]]
id = "exists_norm_le_of_tendsto_toWeakSpace"

[[node]]
id = "norm_le_liminf_norm_of_weak_tendsto"
source = "Atkinson–Han, Theoretical Numerical Analysis, Example 3.3.5"

[[node]]
id = "tendsto_apply_of_tendsto_toWeakSpace_of_tendsto"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 3.5"

[[node]]
id = "WeakDual.continuous_weakSpace_toWeakDual"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 3.13"

[[node]]
id = "tendsto_toWeakDual_of_tendsto_toWeakSpace"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 3.13"

[[node]]
id = "exists_norm_le_of_tendsto_toWeakDual"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 3.13"

[[node]]
id = "norm_le_liminf_norm_of_weakStar_tendsto"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 3.13"

[[node]]
id = "tendsto_apply_of_tendsto_toWeakDual_of_tendsto"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Proposition 3.13"
