namespace = "LinearMap"

[[node]]
id = "wielandtDeflate"

[[node]]
id = "wielandtDeflate_apply_self"

[[node]]
id = "charpoly_wielandtDeflate"

[[node]]
id = "hasEigenvalue_wielandtDeflate_iff"

[[node]]
id = "wielandtDeflate_adjoint_apply_of_ne"

[[node]]
id = "schurWielandtDeflate_invtSubmodule"

[[node]]
id = "_root_.Matrix.householder_conj_eigenvector_apply"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Remark 5.3'

[[node]]
id = "_root_.Matrix.charpoly_householder_conj_eigenvector"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Remark 5.3'

[[node]]
id = "_root_.Matrix.householder_conj_eigenvector_col"

[[node]]
id = "_root_.Matrix.charpoly_eq_mul_charpoly_submatrix_succ_of_col_zero"
