[[node]]
id = "Matrix.IsHamiltonian.charpoly_comp_neg"

[[node]]
id = "Matrix.IsHamiltonian.neg_mem_spectrum"

[[node]]
id = "Matrix.inv_mem_spectrum_of_mem_symplecticGroup"
deps = []

[[node]]
id = "Matrix.fromBlocks_diagonal_mem_orthoSymplecticGroup"
deps = []

[[node]]
id = "Matrix.planeRotation_inl_inr_mem_orthoSymplecticGroup"

[[node]]
id = "Matrix.exists_orthogonalSymplectic_mulVec_eq"

[[node]]
id = "Matrix.IsHamiltonian.isotropic_of_mul_eq_mul_of_stable"

[[node]]
id = "Matrix.exists_orthogonalSymplectic_hamiltonianSchur"

[[node]]
id = "Matrix.riccati_of_hamiltonianSchur"

[[node]]
id = "Matrix.exists_orthogonalSymplectic_condensed"

[[node]]
id = "Matrix.IsHamiltonian.exists_orthogonalSymplectic_paigeVanLoan"

[[node]]
id = "Matrix.IsSkewHamiltonian.exists_orthogonalSymplectic_hessenberg"

[[node]]
id = "Matrix.IsSkewHamiltonian.exists_orthogonalSymplectic_schur"

[[node]]
id = "Matrix.charpoly_neg"
deps = []
