[[node]]
id = "Module.End.invtSubmodule_eq_iSup_maxGenEigenspace"

[[node]]
id = "Matrix.span_cols_eq_iSup_maxGenEigenspace_of_conj"

[[node]]
id = "Matrix.frobenius_norm_diagonal_mul_mul_inv_le"
deps = []

[[node]]
id = "Matrix.l2_opNorm_pow_le_of_schur"

[[node]]
id = "Matrix.l2_opNorm_inv_pow_le_of_schur"

[[node]]
id = "Matrix.exists_invariant_graph_of_sep"

[[node]]
id = "Submodule.gap_map_linearIsometryEquiv"
deps = []

[[node]]
id = "Matrix.gap_range_fromRows_le"

[[node]]
id = "Krylov.subspaceIterate_graph"

[[node]]
id = "Matrix.gap_subspaceIterate_le_of_schur"

[[node]]
id = "LinearMap.IsSymmetric.gap_subspaceIterate_le"

[[node]]
id = "Module.End.invtSubmodule_le_iSup_maxGenEigenspace"
deps = []

[[node]]
id = "Submodule.exists_eq_graph_of_gap_lt_one"

[[node]]
id = "Submodule.norm_eq_gap_graph_div"

[[node]]
id = "LinearMap.IsSymmetric.gap_subspaceIterate_le_of_invariant"

[[node]]  # added by sv2
id = "Krylov.gap_subspaceIterate_le_of_isCompl"
