namespace = "SaadSparse.Chapter10"

[[node]]
id = "M_sgs"

[[node]]
id = "M_sgs_eq_mul"

[[node]]
id = "sub_M_sgs_eq"

[[node]]
id = "equation_10_4"

[[node]]
id = "equation_10_5"

[[node]]
id = "equation_10_6"
