namespace = "SaadSparse.Ch04"

[[node]]
id = "adiHalfStep"

[[node]]
id = "adiStep"

[[node]]
id = "adiHalfStep_spec"

[[node]]
id = "adiStep_spec"

[[node]]
id = "G_adi"

[[node]]
id = "f_adi"

[[node]]
id = "equation_4_50"

[[node]]
id = "toEuclideanCLM_G_adi"

[[node]]
id = "toLp_f_adi"

[[node]]
id = "adiSplitting"

[[node]]
id = "adiSplitting_m"

[[node]]
id = "equation_4_52"

[[node]]
id = "adiSplitting_iterationOperator"

[[node]]
id = "f_adi_eq"

[[node]]
id = "f_adi_eq_m_inv_mulVec"

[[node]]
id = "isUnit_add_smul_one_of_posDef"

[[node]]
id = "adi_complexSpectralRadius_lt_one"

[[node]]
id = "adi_converges"

[[node]]
id = "adi_tendsto_inv_mulVec"

[[node]]
id = "modelH"

[[node]]
id = "modelV"

[[node]]
id = "laplacian2D_eq_modelH_add_modelV"

[[node]]
id = "modelH_posDef"

[[node]]
id = "modelV_posDef"

[[node]]
id = "adi_model_problem"
