[[node]]
id = "ContDiffOnClosure"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, Chapter 9, footnote 16"

[[node]]
id = "ContDiffOnClosure.exists_continuousOn_closure_iteratedFDeriv"

[[node]]
id = "ContDiffOnClosure.of_le"

[[node]]
id = "ContDiffOnClosure.mono"

[[node]]
id = "ContDiffOnClosure.continuousOn_closure"

[[node]]
id = "ContDiffOn.contDiffOnClosure"
