namespace = "ODE"

[[node]]
id = "LinearMultistep"

[[node]]
id = "LinearMultistep.IsOrbitWith"

[[node]]
id = "LinearMultistep.IsOrbit"

[[node]]
id = "LinearMultistep.opL"

[[node]]
id = "LinearMultistep.lte"

[[node]]
id = "LinearMultistep.globalLte"

[[node]]
id = "LinearMultistep.IsConsistentFor"

[[node]]
id = "LinearMultistep.HasOrderFor"

[[node]]
id = "LinearMultistep.IsConsistent"

[[node]]
id = "LinearMultistep.HasOrder"

[[node]]
id = "LinearMultistep.orderCondition"

[[node]]
id = "LinearMultistep.opL_pow"

[[node]]
id = "LinearMultistep.opL_eq_sum_add_remainder"

[[node]]
id = "LinearMultistep.norm_lte_le_of_orderCondition"

[[node]]
id = "LinearMultistep.isConsistent_iff"

[[node]]
id = "LinearMultistep.hasOrder_iff"

[[node]]
id = "LinearMultistep.errorConstant"

[[node]]
id = "LinearMultistep.rho"

[[node]]
id = "LinearMultistep.sigma"

[[node]]
id = "LinearMultistep.charPoly"

[[node]]
id = "LinearMultistep.rho_isRoot_one"

[[node]]
id = "LinearMultistep.SatisfiesRootCondition"

[[node]]
id = "LinearMultistep.SatisfiesStrongRootCondition"

[[node]]
id = "LinearMultistep.IsZeroStable"

[[node]]
id = "LinearMultistep.toLinearRecurrence"

[[node]]
id = "LinearMultistep.norm_sub_le_of_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.isZeroStable_of_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.satisfiesRootCondition_of_isZeroStable"

[[node]]
id = "LinearMultistep.isZeroStable_iff_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.IsConvergentFor"

[[node]]
id = "LinearMultistep.IsConvergentWithOrderFor"

[[node]]
id = "LinearMultistep.isConvergentFor_of_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.satisfiesRootCondition_of_isConvergentFor"

[[node]]
id = "LinearMultistep.isConvergentFor_iff_isZeroStable"

[[node]]
id = "LinearMultistep.ofOneStep"

[[node]]
id = "LinearMultistep.adamsBashforth"

[[node]]
id = "LinearMultistep.adamsBashforth_hasOrder"

[[node]]
id = "LinearMultistep.adamsMoulton"

[[node]]
id = "LinearMultistep.adamsMoulton_hasOrder"

[[node]]
id = "LinearMultistep.adams_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.bdf"

[[node]]
id = "LinearMultistep.bdf_hasOrder"

[[node]]
id = "LinearMultistep.bdf_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.bdf_satisfiesRootCondition_all"
[[node]]
id = "LinearMultistep.midpoint"

[[node]]
id = "LinearMultistep.simpson"

[[node]]
id = "LinearMultistep.absStabilityRegion"

[[node]]
id = "LinearMultistep.mem_absStabilityRegion_iff"

[[node]]
id = "LinearMultistep.SatisfiesAbsRootCondition"

[[node]]
id = "LinearMultistep.IsAStable"

[[node]]
id = "LinearMultistep.IsThetaStable"

[[node]]
id = "LinearMultistep.absStabilityRegionStar"

[[node]]
id = "LinearMultistep.zero_mem_absStabilityRegionStar_iff"

[[node]]
id = "LinearMultistep.absStabilityRegion_midpoint"

[[node]]
id = "LinearMultistep.absStabilityRegion_ofOneStep"

[[node]]
id = "PredictorCorrector"

[[node]]
id = "PredictorCorrector.heun_eq_pece"

[[node]]
id = "PredictorCorrector.hasOrderFor_of"

[[node]]
id = "PredictorCorrector.abm_charPoly"

[[node]]
id = "_root_.norm_sub_sum_smul_le"

[[node]]
id = "LinearMultistep.rhs"

[[node]]
id = "LinearMultistep.lte_spec"

[[node]]
id = "LinearMultistep.taylorCoeff"

[[node]]
id = "LinearMultistep.remainderConst"

[[node]]
id = "LinearMultistep.isConsistentFor_of_orderCondition"

[[node]]
id = "LinearMultistep.hasOrderFor_of_orderCondition"

[[node]]
id = "LinearMultistep.hasOrderFor_of_contDiff"

[[node]]
id = "LinearMultistep.hasOrder_of_orderCondition"

[[node]]
id = "LinearMultistep.taylorCoeff_eq_zero_of_hasOrder"

[[node]]
id = "LinearMultistep.derivative_rho_eval_one_eq_sigma"

[[node]]
id = "LinearMultistep.toLinearRecurrenceZero"

[[node]]
id = "LinearMultistep.charPoly_toLinearRecurrenceZero"

[[node]]
id = "LinearMultistep.isOrbit_zero_iff_isSolution"

[[node]]
id = "LinearMultistep.charPoly_toLinearRecurrence"

[[node]]
id = "LinearMultistep.isOrbit_testField_iff"

[[node]]
id = "LinearMultistep.norm_sub_le_globalLte_of_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.isConvergentWithOrderFor_of_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.isOrbit_ofOneStep_theta_iff"

[[node]]
id = "LinearMultistep.satisfiesRootCondition_of_p_eq_zero"

[[node]]
id = "LinearMultistep.adamsWeight"

[[node]]
id = "LinearMultistep.sum_pow_mul_adamsWeight"

[[node]]
id = "LinearMultistep.eq_adamsWeight_of_moments"

[[node]]
id = "LinearMultistep.adamsBashforth_one_eq"

[[node]]
id = "LinearMultistep.adamsBashforth_two_eq"

[[node]]
id = "LinearMultistep.adamsBashforth_three_eq"

[[node]]
id = "LinearMultistep.adamsMoulton_two_eq"

[[node]]
id = "LinearMultistep.adamsMoulton_three_eq"

[[node]]
id = "LinearMultistep.adamsMoulton_four_eq"

[[node]]
id = "LinearMultistep.adamsBashforth_errorConstant"

[[node]]
id = "LinearMultistep.adamsMoulton_errorConstant"

[[node]]
id = "LinearMultistep.midpoint_hasOrder"

[[node]]
id = "LinearMultistep.simpson_hasOrder"

[[node]]
id = "LinearMultistep.midpoint_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.simpson_satisfiesRootCondition"

[[node]]
id = "LinearMultistep.isAbsStable_iff_mem"

[[node]]
id = "LinearMultistep.satisfiesAbsRootCondition_iff"

[[node]]
id = "LinearMultistep.IsAStable.isThetaStable"

[[node]]
id = "LinearMultistep.mem_absStabilityRegionStar_iff"

[[node]]
id = "LinearMultistep.absStabilityRegion_subset_star"

[[node]]
id = "LinearMultistep.mem_absStabilityRegion_ofOneStep_iff"

[[node]]
id = "LinearMultistep.pad"

[[node]]
id = "LinearMultistep.rho_pad"

[[node]]
id = "LinearMultistep.sigma_pad"

[[node]]
id = "PredictorCorrector.ofPair"

[[node]]
id = "PredictorCorrector.IsOrbitPEC"

[[node]]
id = "PredictorCorrector.IsOrbitPECE"

[[node]]
id = "PredictorCorrector.abm"

[[node]]
id = "PredictorCorrector.lte"

[[node]]
id = "PredictorCorrector.norm_lte_le"

[[node]]
id = "PredictorCorrector.HasOrderFor"

[[node]]
id = "_root_.LinearRecurrence.norm_le_of_satisfiesRootCondition_of_le"

[[node]]
id = "_root_.LinearRecurrence.norm_le_of_satisfiesRootCondition_smul_of_le"

[[node]]
id = "_root_.LinearRecurrence.exists_isSolution_real_frequently_le"

[[node]]
id = "_root_.Polynomial.satisfiesRootCondition_C_mul_iff"

[[node]]
id = "LinearMultistep.charPoly_monic_of_bm1_eq_zero"

[[node]]
id = "LinearMultistep.exists_neg_notMem_absStabilityRegion_of_bm1_eq_zero"

[[node]]
id = "LinearMultistep.not_isAStable_of_bm1_eq_zero"

[[node]]
id = "LinearMultistep.not_isThetaStable_of_bm1_eq_zero"

[[node]]
id = "_root_.Polynomial.norm_eval_le_two_pow_natDegree"

[[node]]
id = "LinearMultistep.isSchurStable_bdfFactor3"

[[node]]
id = "LinearMultistep.isSchurStable_bdfFactor4"

[[node]]
id = "LinearMultistep.isSchurStable_bdfFactor5"
