namespace = "AtkinsonHan.Ch05"

[[node]]
id = "CGState"

[[node]]
id = "cg"

[[node]]
id = "cgStep"

[[node]]
id = "existsUnique_solution"

[[node]]
id = "theorem_5_6_1"

[[node]]
id = "equation_5_6_10"

[[node]]
id = "theorem_5_6_2"
