namespace = "AtkinsonHan.Chapter05"

[[node]]
id = "ContractiveOn"

[[node]]
id = "LipschitzOn"

[[node]]
id = "NonExpansiveOn"

[[node]]
id = "StronglyMonotoneWith"

[[node]]
id = "example_5_1_1"

[[node]]
id = "exercise_5_1_2"

[[node]]
id = "theorem_5_1_3"

[[node]]
id = "theorem_5_1_4"

[[node]]
id = "example_5_1_1_tendsto_iff"

[[node]]
id = "theorem_5_1_3_existsUnique"

[[node]]
id = "equation_5_1_4"

[[node]]
id = "equation_5_1_5"

[[node]]
id = "equation_5_1_6"

[[node]]
id = "theorem_5_1_3_tendsto"
