namespace = "QuarteroniSaccoSaleri.Chapter03"

[[node]]
id = "equation_3_22"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.22)'

[[node]]
id = "equation_3_23"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.23)'

[[node]]
id = "equation_3_24"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.24)'

[[node]]
id = "equation_3_25"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.25)'

[[node]]
id = "backSubst_componentwise_error"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 3.2.2'

[[node]]
id = "backSubst_error_of_diagDominant"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 3.2.2'

[[node]]
id = "equation_3_26"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.26)'

[[node]]
id = "equation_3_27"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.27)'

[[node]]
id = "equation_3_28"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation (3.28)'
