namespace = "SaadSparse.Chapter09"

[[node]]
id = "cgwM"

[[node]]
id = "cgwN"

[[node]]
id = "cgwM_sub_cgwN"

[[node]]
id = "cgwM_isHermitian"

[[node]]
id = "cgwN_conjTranspose"

[[node]]
id = "isSkewAdjoint_energy"

[[node]]
id = "adjoint_energyEnd"

[[node]]
id = "equation_9_29"

[[node]]
id = "cgw"

[[node]]
id = "cgw_alpha"

[[node]]
id = "cgw_residual_eq"

[[node]]
id = "isShiftedSkewAdjoint_energyEnd"

[[node]]
id = "cgw_eq_CGW_iterate"

[[node]]
id = "cgw_isGalerkinIterate"
