namespace = "SaadSparse.Chapter09"

[[node]]
id = "isPreconditioner"

[[node]]
id = "isSymmetric_energy"

[[node]]
id = "isSymmetric_energyA"

[[node]]
id = "isSymmetric_energyInv"

[[node]]
id = "pcg"

[[node]]
id = "pcg_eq"

[[node]]
id = "pcg_isGalerkinIterate"

[[node]]
id = "problem_9_6"

[[node]]
id = "splitPcg"

[[node]]
id = "splitPcg_eq_pcg"

[[node]]
id = "splitPcg_eq_cg"

[[node]]
id = "rightPcg"

[[node]]
id = "rightPcg_eq_pcg"

[[node]]
id = "pcgEnergyA"

[[node]]
id = "pcgEnergyA_eq"

[[node]]
id = "pcgEnergyA_isGalerkinIterate"

[[node]]
id = "decomp_symm"

[[node]]
id = "equation_9_8"

[[node]]
id = "eisenstat"

[[node]]
id = "eisenstat_eq"
