namespace = 'ConvexAnalysis'

[[node]]
id = 'coneOver'

[[node]]
id = 'slice_hull_union'

[[node]]
id = 'Polyhedral'

[[node]]
id = 'FinitelyGenerated'

[[node]]
id = 'Polyhedral.convex'

[[node]]
id = 'FinitelyGenerated.convex'

[[node]]
id = 'polyhedral_iff_finitelyGenerated'

[[node]]
id = 'Polyhedral.isClosed'

[[node]]
id = 'FinitelyGenerated.isClosed'
