namespace = 'ConvexAnalysis'

[[node]]
id = 'EssentiallySmooth'

[[node]]
id = 'domSubdifferential_eq_interior_convexDom_of_essentiallySmooth'

[[node]]
id = 'subsingleton_subdifferential_iff_essentiallySmooth'
