namespace = "FiniteDifference"

[[node]]
id = "IsSemidiscrete"

[[node]]
id = "IsSemidiscrete.iff_normalForm"

[[node]]
id = "forall_inner_add_eq_iff"

[[node]]
id = "hasDerivWithinAt_equivFun_iff"

[[node]]
id = "isSemidiscreteGalerkin_iff_isSemidiscrete"

[[node]]
id = "massMatrix_posDef"

[[node]]
id = "thetaStep"

[[node]]
id = "thetaAmplification"

[[node]]
id = "thetaFactor"

[[node]]
id = "thetaStep_eq_mulVec_add"

[[node]]
id = "thetaStep_zero_zero"

[[node]]
id = "isUnit_add_smul_of_posDef"

[[node]]
id = "mulVec_thetaStep"

[[node]]
id = "eq_thetaStep_iff"

[[node]]
id = "divided_iff"

[[node]]
id = "eq_thetaStep_iff_divided"

[[node]]
id = "_root_.Variational.IsThetaStep.iff_thetaStep"

[[node]]
id = "MassSpace"

[[node]]
id = "toMass"

[[node]]
id = "inner_toMass"

[[node]]
id = "norm_toMass_sq"

[[node]]
id = "massForm"

[[node]]
id = "massForm_apply"

[[node]]
id = "massFunctional"

[[node]]
id = "massFunctional_apply"

[[node]]
id = "massFunctional_zero"

[[node]]
id = "massForm_isCoerciveWith_zero"

[[node]]
id = "massForm_isHermitian"

[[node]]
id = "isThetaStep_toMass_iff"

[[node]]
id = "isThetaStep_toMass_thetaStep'"

[[node]]
id = "isThetaStep_toMass_thetaStep"

[[node]]
id = "thetaStep_dotProduct_mulVec_le"

[[node]]
id = "thetaStep_dotProduct_mulVec_le_of_le"

[[node]]
id = "exists_conj_eq_diagonal"

[[node]]
id = "thetaAmplification_eq_conj"

[[node]]
id = "charpoly_thetaAmplification"

[[node]]
id = "mem_spectrum_thetaAmplification_iff"

[[node]]
id = "mem_spectrum_complexify_thetaAmplification_iff"

[[node]]
id = "one_add_mul_pos_of_posDef"

[[node]]
id = "thetaAmplification_hasEigenvalue_iff"

[[node]]
id = "complexSpectralRadius_thetaAmplification_lt_one_iff"

[[node]]
id = "forall_tendsto_thetaStep_iff"

[[node]]
id = "backwardEuler_tendsto"

[[node]]
id = "two_sub_two_mul_cos_eq"

[[node]]
id = "mem_spectrum_smul_symmTridiagonalToeplitz_iff"

[[node]]
id = "forwardEuler_heat_tendsto_iff"

[[node]]
id = "forwardEuler_heat_tendsto_of_le"
