namespace = "Matrix"

[[node]]
id = "IsStrictColDiagDominant"

[[node]]
id = "IsStrictColDiagDominant.transpose_iff"

[[node]]
id = "IsStrictDiagDominant"

[[node]]
id = "IsStrictDiagDominant.diag_ne_zero"

[[node]]
id = "IsStrictDiagDominant.isUnit"

[[node]]
id = "IsStrictDiagDominant.isUnit_diagPart"

[[node]]
id = "IsStrictDiagDominant.jacobiContraction_lt_one"

[[node]]
id = "gaussSeidel_spectralRadius_lt_one"

[[node]]
id = "jacobiContraction"

[[node]]
id = "jacobi_spectralRadius_lt_one"

[[node]]
id = "jacobi_spectralRadius_lt_one_of_col"

[[node]]
id = "linfty_opNorm_gaussSeidel_iterMatrix_le"

[[node]]
id = "linfty_opNorm_jacobi_iterMatrix"

[[node]]
id = "sassenfeld"

[[node]]
id = "sassenfeld_eq"

[[node]]
id = "IsIrreduciblyDiagDominant"

[[node]]
id = "IsIrreduciblyColDiagDominant"

[[node]]
id = "IsPatternIrreducible.norm_diag_eq_of_mulVec_eq_zero"

[[node]]
id = "IsPatternIrreducible.norm_sub_eq_of_mem_frontier"

[[node]]
id = "IsPatternIrreducible.isUnit_of_dominant"

[[node]]
id = "IsIrreduciblyDiagDominant.isUnit"

[[node]]
id = "IsIrreduciblyDiagDominant.diag_ne_zero"

[[node]]
id = "IsIrreduciblyDiagDominant.isUnit_diagPart"

[[node]]
id = "IsStrictColDiagDominant.isUnit"

[[node]]
id = "IsIrreduciblyDiagDominant.jacobi_spectralRadius_lt_one"

[[node]]
id = "IsIrreduciblyDiagDominant.gaussSeidel_spectralRadius_lt_one"

[[node]]
id = "gaussSeidel_spectralRadius_lt_one_of_col"
