[[node]]
id = "Matrix.EntrywiseNonneg.of_tendsto"

[[node]]
id = "Matrix.geom_sum_eq_sub_pow_mul"

[[node]]
id = "Matrix.EntrywiseNonneg.complexSpectralRadius_lt_one_iff"

[[node]]
id = "Matrix.IsMMatrix"

[[node]]
id = "Matrix.IsMMatrix.diag_pos"

[[node]]
id = "Stationary.Splitting.IsRegular"

[[node]]
id = "Stationary.Splitting.IsRegular.complexSpectralRadius_lt_one_iff"

[[node]]
id = "Stationary.Splitting.IsRegular.complexSpectralRadius_lt_one_of_isMMatrix"
