namespace = "GolubVanLoan.Chapter01"

[[node]]
id = "table_1_2_1"
source = 'Golub–Van Loan, Matrix Computations, Table 1.2.1'

[[node]]
id = "algorithm_1_2_1"
deps = []
source = 'Golub–Van Loan, Matrix Computations, Algorithm 1.2.1'

[[node]]
id = "algorithm_1_2_1_spec"
source = 'Golub–Van Loan, Matrix Computations, Algorithm 1.2.1'

[[node]]
id = "algorithm_1_2_2"
deps = []
source = 'Golub–Van Loan, Matrix Computations, Algorithm 1.2.2'

[[node]]
id = "algorithm_1_2_2_spec"
source = 'Golub–Van Loan, Matrix Computations, Algorithm 1.2.2'

[[node]]
id = "algorithm_1_2_3"
deps = []
source = 'Golub–Van Loan, Matrix Computations, Algorithm 1.2.3'

[[node]]
id = "algorithm_1_2_3_spec"
source = 'Golub–Van Loan, Matrix Computations, Algorithm 1.2.3'

[[node]]
id = "permutation_mulVec"
deps = []
source = 'Golub–Van Loan, Matrix Computations, §1.2.10, Definition'

[[node]]
id = "permutation_transpose_mul_self"
deps = []
source = 'Golub–Van Loan, Matrix Computations, §1.2.10, Definition'

[[node]]
id = "permutation_mul_mul_transpose"
deps = []
source = 'Golub–Van Loan, Matrix Computations, §1.2.10, Definition'

[[node]]
id = "exchange_eq_permMatrix_rev"
source = 'Golub–Van Loan, Matrix Computations, §1.2.11, Definition'

[[node]]
id = "exchange_mul_self"
source = 'Golub–Van Loan, Matrix Computations, §1.2.11, Definition'

[[node]]
id = "downshift"
source = 'Golub–Van Loan, Matrix Computations, §1.2.11, Definition'

[[node]]
id = "perfectShuffle_mulVec_eq"
source = 'Golub–Van Loan, Matrix Computations, §1.2.11, Definition'

[[node]]
id = "equation_1_2_4"
source = 'Golub–Van Loan, Matrix Computations, Equation (1.2.4)'

