namespace = "Bochner"

[[node]]
id = "ContDiffOnThrough"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, §10.1, the notation `C([0,∞); H)`"

[[node]]
id = "ContDiffOnThrough.contDiffOn"

[[node]]
id = "ContDiffOnThrough.mono"

[[node]]
id = "ContDiffOnThrough.of_le"

[[node]]
id = "ContDiffOnThrough.infty_of_forall_nat"

[[node]]
id = "ContDiffOnThrough.id_iff"

[[node]]
id = "ContDiffOnThrough.comp"

[[node]]
id = "ContDiffOnThrough.of_comp"

[[node]]
id = "ContDiffOnThrough.derivWithin_eq"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, proof of Theorem 7.5"

[[node]]
id = "ContDiffOnThrough.derivWithin"

[[node]]
id = "MemLpThrough"
source = "Brezis, Functional Analysis, Sobolev Spaces and PDE, §10.1, the notation `L²(0,∞; H¹₀(Ω))`"

[[node]]
id = "MemLpThrough.memLp"

[[node]]
id = "MemLpThrough.mono"

[[node]]
id = "MemLpThrough.comp"

[[node]]
id = "MemLpThrough.of_comp"

[[node]]
id = "MemLpThrough.of_contDiffOnThrough_of_integrable"
