import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.Algebra.Polynomial.Module.AEval
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Eigenspace.Minpoly
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.RingTheory.EuclideanDomain
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.PrincipalIdealDomain
import Numlib.Algebra.Polynomial.AevalApply

/-!
# Krylov subspaces

`Krylov.subspace A v m = span {v, A v, …, A^(m-1) v}` for an endomorphism `A` of a module over a
commutative ring, the full Krylov space, the polynomial description `𝒦_m = {p(A) v | deg p < m}`,
and — over a field — the grade of `v` together with its minimal polynomial, the monic generator of
the annihilator ideal `{p | p(A) v = 0}` ([saad2003iterative] §6.2, Prop 6.1–6.2;
[saad2011numerical] Prop 6.1–6.3; [choi2006iterative] Def 2.1; [meurant2006lanczos] §2.1).

The full Krylov space is the least `A`-invariant subspace containing `v`
(`Krylov.fullSubspace_mem_invtSubmodule`, `Krylov.fullSubspace_le_of_mem_invtSubmodule`), so the
grade is the dimension of that subspace ([golub2013matrix] Theorem 11.3.1). Krylov spaces, full
Krylov spaces and grades are invariant under shifts `A ↦ A + c` (`Krylov.subspace_add_algebraMap`,
`Krylov.fullSubspace_add_algebraMap`, `Krylov.grade_add_algebraMap`) and under `A ↦ -A`
(`Krylov.subspace_neg`). A map intertwining two operators carries the Krylov subspaces of one onto
those of the other (`Krylov.map_subspace_of_semiconj`), and the vectors of a three-term
recurrence with nonzero off-diagonal coefficients span the Krylov subspaces
(`Krylov.span_eq_subspace_of_threeTerm`). The rewriting lemmas `Module.End.aeval_mul_apply`, … for
`p(T) v` are in `Numlib.Algebra.Polynomial.AevalApply`.

## Notation

`𝒦[A, v] m` is `Krylov.subspace A v m`, the `m`-th Krylov subspace of `A` at `v`. The notation is
scoped to the `Krylov` namespace.

## Implementation notes

`Krylov.annIdealVec` and `Krylov.minpolyVec` are, declaration for declaration, the module-element
analogue of Mathlib's `Polynomial.annIdeal` and `Polynomial.annIdealGenerator`: the same monic
generator of the same kind of ideal, with the same proofs. They are stated afresh because Mathlib's
are the annihilator of an *algebra element* `a : A` under `Polynomial.aeval a`, whereas what a
Krylov method annihilates is a *vector*, `p ↦ p(A) v`. The two would be one if Mathlib's pair were
generalized to the `𝕜[X]`-module `Module.AEval' A`, where `Krylov.annIdealVec A v` is the
annihilator of the cyclic submodule generated by `v`.
-/

open Polynomial

namespace Krylov

section CommRing

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The `m`-th Krylov subspace `𝒦_m(A, v) = span {v, A v, …, A^(m-1) v}`. -/
def subspace (A : Module.End R M) (v : M) (m : ℕ) : Submodule R M :=
  Submodule.span R (Set.range fun i : Fin m => (A ^ (i : ℕ)) v)

/-- Notation `𝒦[A, v] m` for `Krylov.subspace A v m`. -/
scoped notation "𝒦[" A ", " v "] " m:max => Krylov.subspace A v m

/-- The full Krylov space `span {A^i v | i : ℕ}`, the smallest `A`-invariant subspace containing
`v`. -/
def fullSubspace (A : Module.End R M) (v : M) : Submodule R M :=
  Submodule.span R (Set.range fun i : ℕ => (A ^ i) v)

/-- The evaluation map `p ↦ p(A) v`. -/
noncomputable def polyEval (A : Module.End R M) (v : M) : R[X] →ₗ[R] M where
  toFun p := aeval A p v
  map_add' p q := by simp [map_add]
  map_smul' c p := by simp

/-- `Krylov.polyEval` is evaluation of the polynomial at `A`, applied to `v`. -/
@[simp]
theorem polyEval_apply (A : Module.End R M) (v : M) (p : R[X]) :
    polyEval A v p = aeval A p v := rfl

variable (A : Module.End R M) (v : M)

instance (m : ℕ) : Module.Finite R (subspace A v m) :=
  Module.Finite.span_of_finite R (Set.finite_range _)

/-- No steps span nothing: `𝒦_0 = ⊥`. -/
@[simp]
theorem subspace_zero : subspace A v 0 = ⊥ := by
  simp [subspace]

/-- One step spans the starting direction: `𝒦_1 = R ∙ v`. -/
theorem subspace_one : subspace A v 1 = R ∙ v := by
  simp [subspace, Set.range_unique]

/-- The generators of `𝒦_m`: `A^i v` lies in it for every `i < m`. -/
theorem pow_apply_mem_subspace {i m : ℕ} (h : i < m) : (A ^ i) v ∈ subspace A v m :=
  Submodule.subset_span ⟨⟨i, h⟩, rfl⟩

/-- The starting vector lies in every nontrivial Krylov subspace. -/
theorem self_mem_subspace {m : ℕ} (h : 0 < m) : v ∈ subspace A v m := by
  simpa using pow_apply_mem_subspace A v h

/-- The generating set of `𝒦_m` written as an image of `Set.Iio m`; the form in which it matches
Mathlib's Gram–Schmidt spans. -/
theorem subspace_eq_span_image_Iio (m : ℕ) :
    subspace A v m = Submodule.span R ((fun i : ℕ => (A ^ i) v) '' Set.Iio m) := by
  rw [subspace]
  congr 1
  ext x
  simp only [Set.mem_range, Set.mem_image, Set.mem_Iio, Fin.exists_iff]
  tauto

/-- The Krylov subspaces grow with the number of steps: `𝒦_m ≤ 𝒦_n` for `m ≤ n`. -/
theorem subspace_mono : Monotone (subspace A v) := by
  intro m n h
  simp only [subspace_eq_span_image_Iio]
  exact Submodule.span_mono (Set.image_mono (Set.Iio_subset_Iio h))

/-- `(-A)^i v = (-1)^i (A^i v)`: the generators of the Krylov sequence of `-A` differ from those of
`A` by a sign only. -/
theorem neg_pow_apply (i : ℕ) : ((-A) ^ i) v = (-1 : R) ^ i • (A ^ i) v := by
  rw [← neg_one_smul R A, smul_pow, LinearMap.smul_apply]

/-- **The Krylov subspaces of `-A` are those of `A`**: the generators differ by the signs `(-1)^i`,
which do not change a span. A method whose iterates live in `𝒦_m(A, v)` therefore runs unchanged on
`-A`, which is the reduction that turns a bound on a largest eigenvalue into one on a smallest. -/
theorem subspace_neg (m : ℕ) : subspace (-A) v m = subspace A v m := by
  refine le_antisymm ?_ ?_ <;> rw [subspace, subspace, Submodule.span_le] <;>
    rintro _ ⟨i, rfl⟩ <;> simp only [SetLike.mem_coe]
  · rw [neg_pow_apply]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)
  · have h := neg_pow_apply (-A) v (i : ℕ)
    rw [neg_neg] at h
    rw [h]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- Every Krylov subspace sits inside the full Krylov space. -/
theorem subspace_le_fullSubspace (m : ℕ) : subspace A v m ≤ fullSubspace A v :=
  Submodule.span_mono <| by rintro _ ⟨i, rfl⟩; exact ⟨(i : ℕ), rfl⟩

/-- The full Krylov space is the supremum of the finite ones: `𝒦_∞ = ⨆ m, 𝒦_m`. -/
theorem iSup_subspace : ⨆ m, subspace A v m = fullSubspace A v := by
  refine le_antisymm (iSup_le fun m => subspace_le_fullSubspace A v m) ?_
  rw [fullSubspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  exact le_iSup (subspace A v) (i + 1) (pow_apply_mem_subspace A v i.lt_succ_self)

/-- One application of `A` costs one step: `A 𝒦_m ≤ 𝒦_{m+1}`. -/
theorem map_subspace_le (m : ℕ) : (subspace A v m).map A ≤ subspace A v (m + 1) := by
  rw [subspace, Submodule.map_span, Submodule.span_le]
  rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
  have h : A ((A ^ (i : ℕ)) v) = (A ^ ((i : ℕ) + 1)) v := by rw [pow_succ']; rfl
  rw [SetLike.mem_coe, h]
  exact pow_apply_mem_subspace A v (Nat.succ_lt_succ i.2)

/-- `A^k` maps `𝒦_m` into `𝒦_{m+k}`. -/
theorem pow_apply_mem_subspace_of_mem {x : M} {m : ℕ} (hx : x ∈ subspace A v m) (k : ℕ) :
    (A ^ k) x ∈ subspace A v (m + k) := by
  induction k with
  | zero => simpa using hx
  | succ k ih =>
    have h : (A ^ (k + 1)) x = A ((A ^ k) x) := by rw [pow_succ']; rfl
    rw [h, ← Nat.add_assoc]
    exact map_subspace_le A v (m + k) ⟨_, ih, rfl⟩

/-- The full Krylov space is `A`-invariant; since it also contains `v`, it is the smallest
`A`-invariant subspace that does. -/
theorem fullSubspace_mem_invtSubmodule : fullSubspace A v ∈ Module.End.invtSubmodule A := by
  rw [Module.End.mem_invtSubmodule_iff_map_le, fullSubspace, Submodule.map_span, Submodule.span_le]
  rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
  refine Submodule.subset_span ⟨i + 1, ?_⟩
  change (A ^ (i + 1)) v = A ((A ^ i) v)
  rw [pow_succ']
  rfl

/-- **The full Krylov space is the least invariant subspace containing `v`**: every `A`-invariant
submodule containing `v` contains every `A^i v`. With `Krylov.fullSubspace_mem_invtSubmodule` this
makes the grade the dimension of the smallest invariant subspace containing `v`
([golub2013matrix] Theorem 11.3.1). -/
theorem fullSubspace_le_of_mem_invtSubmodule {W : Submodule R M}
    (hW : W ∈ Module.End.invtSubmodule A) (hv : v ∈ W) : fullSubspace A v ≤ W := by
  rw [fullSubspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  induction i with
  | zero => simpa using hv
  | succ i ih =>
    change (A ^ (i + 1)) v ∈ W
    rw [pow_succ', Module.End.mul_apply]
    exact hW ih

/-- The full Krylov space of the zero vector is trivial. -/
@[simp]
theorem fullSubspace_zero : fullSubspace A (0 : M) = ⊥ := by
  rw [fullSubspace, Submodule.span_eq_bot]
  rintro _ ⟨i, rfl⟩
  simp

/-- [saad2003iterative], §6.2: `𝒦_m = {p(A) v | deg p < m}`, "the subspace of all vectors which can
be written as `x = p(A) v` with `p` of degree not exceeding `m - 1`". -/
theorem subspace_eq_map_degreeLT (m : ℕ) :
    subspace A v m = (degreeLT R m).map (polyEval A v) := by
  refine le_antisymm ?_ ?_
  · rw [subspace, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    refine ⟨X ^ (i : ℕ), ?_, by simp⟩
    rw [X_pow_eq_monomial]
    exact monomial_coe_mem_degreeLT i 1
  · rintro _ ⟨p, hp, rfl⟩
    rw [SetLike.mem_coe, mem_degreeLT] at hp
    rcases eq_or_ne p 0 with rfl | hp0
    · simp
    rw [polyEval_apply, aeval_eq_sum_range' ((natDegree_lt_iff_degree_lt hp0).2 hp) A,
      LinearMap.sum_apply]
    refine Submodule.sum_mem _ fun i hi => ?_
    rw [LinearMap.smul_apply]
    exact Submodule.smul_mem _ _ (pow_apply_mem_subspace A v (Finset.mem_range.1 hi))

/-- The polynomial description of `𝒦_m` element by element: `x` lies in it exactly when `x = p(A) v`
for some polynomial `p` of degree `< m`. -/
theorem mem_subspace_iff_exists_aeval {x : M} {m : ℕ} :
    x ∈ subspace A v m ↔ ∃ p : R[X], p.degree < m ∧ aeval A p v = x := by
  rw [subspace_eq_map_degreeLT]
  constructor
  · rintro ⟨p, hp, rfl⟩
    exact ⟨p, mem_degreeLT.1 hp, rfl⟩
  · rintro ⟨p, hp, rfl⟩
    exact ⟨p, mem_degreeLT.2 hp, rfl⟩

/-- Every polynomial of degree `< m` in `A`, applied to `v`, lands in `𝒦_m`. This is the direction
of the polynomial description that the Krylov methods use. -/
theorem aeval_apply_mem_subspace {p : R[X]} {m : ℕ} (hp : p.degree < m) :
    aeval A p v ∈ subspace A v m :=
  (mem_subspace_iff_exists_aeval A v).2 ⟨p, hp, rfl⟩

/-- One inclusion of `Krylov.subspace_add_algebraMap`: `(A + c)^i v = q(A) v` for
`q = (X + c)^i`, a polynomial of degree at most `i`. -/
private theorem subspace_add_algebraMap_le (c : R) (m : ℕ) :
    subspace (A + algebraMap R (Module.End R M) c) v m ≤ subspace A v m := by
  rw [subspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  have hdeg : ((X + C c) ^ (i : ℕ) : R[X]).degree < (m : ℕ) := by
    refine degree_le_natDegree.trans_lt ?_
    have h1 : (X + C c : R[X]).natDegree ≤ 1 := by rw [natDegree_add_C]; exact natDegree_X_le
    exact_mod_cast (natDegree_pow_le_of_le (i : ℕ) h1).trans_lt (by simp)
  have happ : aeval A ((X + C c) ^ (i : ℕ)) v =
      ((A + algebraMap R (Module.End R M) c) ^ (i : ℕ)) v := by
    simp
  change ((A + algebraMap R (Module.End R M) c) ^ (i : ℕ)) v ∈ subspace A v m
  rw [← happ]
  exact aeval_apply_mem_subspace A v hdeg

/-- **Shift invariance**: the Krylov subspaces of `A + c` are those of `A` for every scalar `c`,
both being `span {v, A v, …, A^(m-1) v}` — `(A + c)^i v` is a combination of the `A^j v`, `j ≤ i`,
and conversely with `-c`. A companion of `Krylov.subspace_neg`. -/
theorem subspace_add_algebraMap (c : R) (m : ℕ) :
    subspace (A + algebraMap R (Module.End R M) c) v m = subspace A v m := by
  refine le_antisymm (subspace_add_algebraMap_le A v c m) ?_
  have h := subspace_add_algebraMap_le (A + algebraMap R (Module.End R M) c) v (-c) m
  rwa [map_neg, add_neg_cancel_right] at h

/-- The full Krylov space is shift invariant: `𝒦_∞(A + c, v) = 𝒦_∞(A, v)`. -/
theorem fullSubspace_add_algebraMap (c : R) :
    fullSubspace (A + algebraMap R (Module.End R M) c) v = fullSubspace A v := by
  simp only [← iSup_subspace, subspace_add_algebraMap]

/-- `𝒦_{m+1} = 𝒦_m` iff `A^m v ∈ 𝒦_m` iff `𝒦_m` is `A`-invariant (for `m ≥ 1` or `v = 0`). -/
theorem subspace_succ_eq_iff (m : ℕ) :
    subspace A v (m + 1) = subspace A v m ↔ (A ^ m) v ∈ subspace A v m := by
  constructor
  · intro h
    rw [← h]
    exact pow_apply_mem_subspace A v m.lt_succ_self
  · intro h
    refine le_antisymm ?_ (subspace_mono A v m.le_succ)
    rw [subspace, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    rcases lt_or_eq_of_le (Nat.lt_succ_iff.1 i.2) with hi | hi
    · exact pow_apply_mem_subspace A v hi
    · rw [SetLike.mem_coe]
      change (A ^ (i : ℕ)) v ∈ subspace A v m
      rw [hi]
      exact h

/-- A Krylov subspace that no longer grows is `A`-invariant. -/
theorem mem_invtSubmodule_of_subspace_succ_eq {m : ℕ}
    (h : subspace A v (m + 1) = subspace A v m) :
    subspace A v m ∈ Module.End.invtSubmodule A :=
  (Module.End.mem_invtSubmodule_iff_map_le A).2 (h ▸ map_subspace_le A v m)

/-- Once the Krylov sequence closes up at step `n` it stays closed. -/
theorem pow_apply_mem_subspace_of_le {n : ℕ} (h : (A ^ n) v ∈ subspace A v n) {m : ℕ}
    (hm : n ≤ m) : (A ^ m) v ∈ subspace A v m := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hm
  have hk := pow_apply_mem_subspace_of_mem A v h k
  have hpow : (A ^ k) ((A ^ n) v) = (A ^ (n + k)) v := by
    rw [← Module.End.mul_apply, ← pow_add, Nat.add_comm]
  rwa [hpow] at hk

/-- [saad2003iterative], Prop 6.1: the Krylov subspaces are constant from the first closure onwards.
-/
theorem subspace_eq_of_pow_apply_mem {n : ℕ} (h : (A ^ n) v ∈ subspace A v n) {m : ℕ}
    (hm : n ≤ m) : subspace A v m = subspace A v n := by
  induction m, hm using Nat.le_induction with
  | base => rfl
  | succ m hm ih =>
    rw [(subspace_succ_eq_iff A v m).2 (pow_apply_mem_subspace_of_le A v h hm), ih]

/-- Once the Krylov sequence closes up at step `n`, that subspace is already everything the sequence
will ever reach: `𝒦_∞ = 𝒦_n`. -/
theorem fullSubspace_eq_of_pow_apply_mem {n : ℕ} (h : (A ^ n) v ∈ subspace A v n) :
    fullSubspace A v = subspace A v n := by
  refine le_antisymm ?_ (subspace_le_fullSubspace A v n)
  rw [fullSubspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  rcases lt_or_ge i n with hi | hi
  · exact pow_apply_mem_subspace A v hi
  · exact subspace_eq_of_pow_apply_mem A v h hi ▸ pow_apply_mem_subspace_of_le A v h hi

/-- Rescaling the starting vector does not enlarge the Krylov subspace. -/
theorem subspace_smul (c : R) (m : ℕ) : subspace A (c • v) m ≤ subspace A v m := by
  rw [subspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  simpa using Submodule.smul_mem _ c (pow_apply_mem_subspace A v i.2)

/-- Rescaling the starting vector does not enlarge the full Krylov subspace. -/
theorem fullSubspace_smul (c : R) : fullSubspace A (c • v) ≤ fullSubspace A v := by
  rw [fullSubspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  have h : (A ^ i) v ∈ fullSubspace A v := Submodule.subset_span ⟨i, rfl⟩
  simpa using Submodule.smul_mem _ c h

/-! ### Krylov subspaces under an intertwining map -/

section Semiconj

variable {M' : Type*} [AddCommGroup M'] [Module R M'] {N : M →ₗ[R] M'} {B : Module.End R M}
  {C : Module.End R M'}

/-- A map intertwining `B` and `C` (`N ∘ B = C ∘ N`) intertwines their powers. -/
theorem pow_apply_of_semiconj (h : Function.Semiconj N B C) (i : ℕ) (x : M) :
    N ((B ^ i) x) = (C ^ i) (N x) := by
  induction i with
  | zero => rfl
  | succ i ih =>
    rw [pow_succ', pow_succ', Module.End.mul_apply, Module.End.mul_apply, h.eq, ih]

/-- An intertwining map carries Krylov subspaces onto Krylov subspaces: `N 𝒦_m(B, b) = 𝒦_m(C, N b)`
when `N ∘ B = C ∘ N`. `N` may map between two modules, as `A` does between the Gram operators
`Aᴴ A` and `A Aᴴ`; `Krylov.map_subspace_comp` is the case `B = B' ∘ N`, `C = N ∘ B'` on one
module. -/
theorem map_subspace_of_semiconj (h : Function.Semiconj N B C) (b : M) (m : ℕ) :
    (subspace B b m).map N = subspace C (N b) m := by
  rw [subspace, subspace, Submodule.map_span]
  congr 1
  ext z
  simp only [Set.mem_image, Set.mem_range]
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, (pow_apply_of_semiconj h i b).symm⟩
  · rintro ⟨i, rfl⟩
    exact ⟨(B ^ (i : ℕ)) b, ⟨i, rfl⟩, pow_apply_of_semiconj h i b⟩

/-- Membership form of `Krylov.map_subspace_of_semiconj`. -/
theorem apply_mem_subspace_of_semiconj (h : Function.Semiconj N B C) {b x : M} {m : ℕ}
    (hx : x ∈ subspace B b m) : N x ∈ subspace C (N b) m :=
  map_subspace_of_semiconj h b m ▸ Submodule.mem_map_of_mem hx

/-- Starting `s` steps later costs `s` steps: `𝒦_m(C, C^s c) ≤ 𝒦_{m+s}(C, c)`. -/
theorem subspace_pow_apply_le (C : Module.End R M') (c : M') (s m : ℕ) :
    subspace C ((C ^ s) c) m ≤ subspace C c (m + s) := by
  rw [subspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  change (C ^ (i : ℕ)) ((C ^ s) c) ∈ subspace C c (m + s)
  rw [← Module.End.mul_apply, ← pow_add]
  exact pow_apply_mem_subspace C c (by have := i.isLt; omega)

/-- The full Krylov space version of `Krylov.map_subspace_of_semiconj`:
`N 𝒦_∞(B, b) = 𝒦_∞(C, N b)` when `N ∘ B = C ∘ N`. -/
theorem map_fullSubspace_of_semiconj (h : Function.Semiconj N B C) (b : M) :
    (fullSubspace B b).map N = fullSubspace C (N b) := by
  rw [fullSubspace, fullSubspace, Submodule.map_span, ← Set.range_comp]
  congr 1
  ext z
  simp only [Set.mem_range, Function.comp_apply, pow_apply_of_semiconj h]

end Semiconj

/-- Swapping a composition through one of its factors: `N ((A N)^i v) = (N A)^i (N v)`, the case
`N ∘ (B N) = (N B) ∘ N` of `Krylov.pow_apply_of_semiconj`. -/
theorem pow_comp_apply (B N : Module.End R M) (i : ℕ) (u : M) :
    N (((B ∘ₗ N) ^ i) u) = ((N ∘ₗ B) ^ i) (N u) :=
  pow_apply_of_semiconj (N := N) (B := B ∘ₗ N) (C := N ∘ₗ B) (fun _ => rfl) i u

/-- `N` carries the Krylov space of `B N` to the Krylov space of `N B`: `N 𝒦_m(B N, v) = 𝒦_m(N B, N
v)`.  This is the identity behind every "change of variables" in a Krylov method — CGNE's `x = Aᴴ
u`, right preconditioning's `x = M⁻¹ u` — which is why the two variants search the same affine
space. It is the case `N ∘ (B N) = (N B) ∘ N` of `Krylov.map_subspace_of_semiconj`. -/
theorem map_subspace_comp (B N : Module.End R M) (u : M) (m : ℕ) :
    (subspace (B ∘ₗ N) u m).map N = subspace (N ∘ₗ B) (N u) m :=
  map_subspace_of_semiconj (N := N) (B := B ∘ₗ N) (C := N ∘ₗ B) (fun _ => rfl) u m

end CommRing

section Field

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

variable (A : Module.End K V) (v : V)

/-- The grade of `v` w.r.t. `A`: the dimension of the cyclic subspace `𝒦_∞(A, v)` — equivalently the
least `m` with `A^m v ∈ 𝒦_m` (`grade_eq_sInf`) and the degree of the minimal polynomial of `v`
([saad2003iterative], §6.2; Liesen–Strakoš, *Krylov Subspace Methods: Principles and Analysis*).
Junk value `0` when the cyclic subspace is infinite-dimensional (Mathlib's `finrank` convention);
the finite-grade hypothesis is `[FiniteDimensional K (fullSubspace A v)]`, automatic when `V` is
finite-dimensional. -/
noncomputable def grade : ℕ := Module.finrank K (fullSubspace A v)

/-- The Krylov vectors `v, A v, …, A^(m-1) v` are linearly independent exactly when no earlier power
of `A` has already fallen into its own Krylov subspace. -/
theorem linearIndependent_iff_forall_pow_notMem {m : ℕ} :
    LinearIndependent K (fun i : Fin m => (A ^ (i : ℕ)) v) ↔
      ∀ k < m, (A ^ k) v ∉ subspace A v k := by
  induction m with
  | zero => exact iff_of_true linearIndependent_empty_type (by simp)
  | succ m ih =>
    have hinit : Fin.init (fun i : Fin (m + 1) => (A ^ (i : ℕ)) v)
        = fun i : Fin m => (A ^ (i : ℕ)) v := rfl
    rw [linearIndependent_finSucc', hinit, ih]
    constructor
    · rintro ⟨h₁, h₂⟩ k hk
      rcases Nat.lt_succ_iff_lt_or_eq.1 hk with hk' | rfl
      · exact h₁ k hk'
      · exact h₂
    · intro h
      exact ⟨fun k hk => h k (hk.trans m.lt_succ_self), h m m.lt_succ_self⟩

/-- The Krylov sequence stabilizes iff the cyclic subspace is finite-dimensional. -/
theorem finiteDimensional_fullSubspace_iff :
    FiniteDimensional K (fullSubspace A v) ↔ ∃ m, (A ^ m) v ∈ subspace A v m := by
  constructor
  · intro h
    by_contra hc
    have hc' : ∀ m, (A ^ m) v ∉ subspace A v m := fun m hm => hc ⟨m, hm⟩
    set n := Module.finrank K (fullSubspace A v) with hn
    have hli : LinearIndependent K (fun i : Fin (n + 1) => (A ^ (i : ℕ)) v) :=
      (linearIndependent_iff_forall_pow_notMem A v).2 fun k _ => hc' k
    have h₁ : Module.finrank K (subspace A v (n + 1)) = n + 1 := by
      rw [subspace]
      simpa using finrank_span_eq_card hli
    have h₂ : Module.finrank K (subspace A v (n + 1)) ≤ n :=
      hn ▸ Submodule.finrank_mono (subspace_le_fullSubspace A v (n + 1))
    omega
  · rintro ⟨m, hm⟩
    rw [fullSubspace_eq_of_pow_apply_mem A v hm]
    infer_instance

/-- `A^m v ∈ 𝒦_m` iff `v` is annihilated by a monic polynomial of degree `m` ([saad2003iterative],
§6.2 defines the grade through the minimal polynomial of `v`). -/
theorem pow_apply_mem_subspace_iff_exists_monic (m : ℕ) :
    (A ^ m) v ∈ subspace A v m ↔ ∃ p : K[X], p.Monic ∧ p.natDegree = m ∧ aeval A p v = 0 := by
  rw [mem_subspace_iff_exists_aeval]
  constructor
  · rintro ⟨q, hq, hqv⟩
    refine ⟨X ^ m - q, monic_X_pow_sub hq, ?_, by simp [hqv]⟩
    refine natDegree_eq_of_degree_eq_some ?_
    rw [degree_sub_eq_left_of_degree_lt (by rwa [degree_X_pow]), degree_X_pow]
  · rintro ⟨p, hp, hpd, hpv⟩
    refine ⟨X ^ m - p, ?_, by simp [hpv]⟩
    have hdp : p.degree = (m : ℕ) := hpd ▸ degree_eq_natDegree hp.ne_zero
    have hlt := degree_sub_lt_left (p := (X : K[X]) ^ m) (q := p) (by rw [degree_X_pow, hdp])
      (monic_X_pow m).ne_zero (by simp [hp.leadingCoeff])
    rwa [degree_X_pow] at hlt

/-! ### The minimal polynomial of a vector -/

/-- The annihilator ideal of `v`: the polynomials `p` with `p(A) v = 0`.  It is an ideal of `K[X]`
and not merely a `K`-subspace, because it is the annihilator of `v` for the `K[X]`-module structure
that `A` puts on `V` (Mathlib's `Module.AEval'`). -/
def annIdealVec : Ideal K[X] where
  carrier := {p | aeval A p v = 0}
  add_mem' {p q} (hp : aeval A p v = 0) (hq : aeval A q v = 0) := by
    change aeval A (p + q) v = 0
    rw [map_add, LinearMap.add_apply, hp, hq, add_zero]
  zero_mem' := by
    change aeval A (0 : K[X]) v = 0
    rw [map_zero, LinearMap.zero_apply]
  smul_mem' c p (hp : aeval A p v = 0) := by
    change aeval A (c • p) v = 0
    rw [smul_eq_mul, map_mul, Module.End.mul_apply, hp, map_zero]

/-- Membership in the annihilator ideal of `v` is annihilation of `v`. -/
@[simp]
theorem mem_annIdealVec {p : K[X]} : p ∈ annIdealVec A v ↔ aeval A p v = 0 := Iff.rfl

/-- The minimal polynomial of `v` with respect to `A`: the monic generator of the annihilator ideal
`{p | p(A) v = 0}`, and `0` when that ideal is trivial, which happens exactly when the cyclic
subspace `𝒦_∞(A, v)` is infinite-dimensional.  Its degree is the grade of `v`
(`natDegree_minpolyVec`), which is how [saad2003iterative], §6.2 defines the grade. -/
noncomputable def minpolyVec : K[X] :=
  let g := Submodule.IsPrincipal.generator (annIdealVec A v)
  g * C g.leadingCoeff⁻¹

/-- The minimal polynomial of `v` vanishes exactly when nothing but `0` annihilates `v`, that is,
when the cyclic subspace is infinite-dimensional. -/
@[simp]
theorem minpolyVec_eq_zero_iff : minpolyVec A v = 0 ↔ annIdealVec A v = ⊥ := by
  simp only [minpolyVec, mul_eq_zero, Submodule.IsPrincipal.eq_bot_iff_generator_eq_zero,
    C_eq_zero, inv_eq_zero, leadingCoeff_eq_zero, or_self_iff]

/-- `minpolyVec` generates the annihilator ideal. -/
@[simp]
theorem span_singleton_minpolyVec : Ideal.span {minpolyVec A v} = annIdealVec A v := by
  by_cases h : minpolyVec A v = 0
  · rw [h, (minpolyVec_eq_zero_iff A v).1 h, Set.singleton_zero, Ideal.span_zero]
  · rw [minpolyVec, Ideal.span_singleton_mul_right_unit, Ideal.span_singleton_generator]
    exact isUnit_C.2 (IsUnit.mk0 _ (inv_eq_zero.not.2
      (leadingCoeff_eq_zero.not.2 (mul_ne_zero_iff.1 h).1)))

/-- The minimal polynomial of `v` belongs to the annihilator ideal it generates. -/
theorem minpolyVec_mem : minpolyVec A v ∈ annIdealVec A v :=
  Ideal.mul_mem_right _ _ (Submodule.IsPrincipal.generator_mem _)

/-- The minimal polynomial of `v` annihilates `v`. -/
theorem aeval_minpolyVec : aeval A (minpolyVec A v) v = 0 := minpolyVec_mem A v

/-- The defining property of the minimal polynomial of a vector: it divides exactly the polynomials
that annihilate `v`. -/
theorem minpolyVec_dvd_iff {p : K[X]} : minpolyVec A v ∣ p ↔ aeval A p v = 0 := by
  rw [← Ideal.mem_span_singleton, span_singleton_minpolyVec, mem_annIdealVec]

/-- The minimal polynomial of `v` is monic whenever it is nonzero, that is, whenever `v` has finite
grade (`minpolyVec_ne_zero`). -/
theorem minpolyVec_monic (h : minpolyVec A v ≠ 0) : (minpolyVec A v).Monic :=
  monic_mul_leadingCoeff_inv (mul_ne_zero_iff.1 h).1

/-- The grade of a vector never exceeds the dimension of the ambient space, so a Krylov method in
finite dimension terminates in at most `dim V` steps. -/
theorem grade_le_finrank [FiniteDimensional K V] : grade A v ≤ Module.finrank K V :=
  Submodule.finrank_le _

/-- The grade is shift invariant: `grade (A + c) v = grade A v`, the full Krylov spaces being
equal (`Krylov.fullSubspace_add_algebraMap`). -/
theorem grade_add_algebraMap (c : K) :
    grade (A + algebraMap K (Module.End K V) c) v = grade A v := by
  rw [grade, grade, fullSubspace_add_algebraMap]

/-- The zero vector has grade `0`. -/
@[simp]
theorem grade_zero : grade A 0 = 0 := by
  rw [grade, fullSubspace_zero, finrank_bot]

/-- The grade vanishes only in the two degenerate cases: `v = 0`, and the junk value taken when the
cyclic subspace is infinite-dimensional. -/
theorem grade_eq_zero_iff :
    grade A v = 0 ↔ v = 0 ∨ ¬FiniteDimensional K (fullSubspace A v) := by
  by_cases h : FiniteDimensional K (fullSubspace A v)
  · simp only [h, not_true_eq_false, or_false, grade, Submodule.finrank_eq_zero]
    constructor
    · intro hb
      have hv : v ∈ fullSubspace A v := Submodule.subset_span ⟨0, by simp⟩
      rw [hb] at hv
      simpa using hv
    · rintro rfl
      exact fullSubspace_zero A
  · simp [h, grade, Module.finrank_of_not_finite h]

/-- Rescaling the starting vector by a nonzero scalar does not change the Krylov subspaces. -/
theorem subspace_smul_of_ne_zero {c : K} (hc : c ≠ 0) (m : ℕ) :
    subspace A (c • v) m = subspace A v m := by
  refine le_antisymm (subspace_smul A v c m) ?_
  simpa [inv_smul_smul₀ hc] using subspace_smul A (c • v) c⁻¹ m

/-- Rescaling the starting vector by a nonzero scalar does not change the full Krylov subspace. -/
theorem fullSubspace_smul_of_ne_zero {c : K} (hc : c ≠ 0) :
    fullSubspace A (c • v) = fullSubspace A v := by
  refine le_antisymm (fullSubspace_smul A v c) ?_
  simpa [inv_smul_smul₀ hc] using fullSubspace_smul A (c • v) c⁻¹

/-- Rescaling the starting vector by a nonzero scalar does not change its grade. -/
theorem grade_smul {c : K} (hc : c ≠ 0) : grade A (c • v) = grade A v := by
  rw [grade, grade, fullSubspace_smul_of_ne_zero A v hc]

/-- A nonzero vector of finite grade has positive grade: the Krylov process takes at least one
step. -/
theorem grade_pos_of_ne_zero [FiniteDimensional K (fullSubspace A v)] (hv : v ≠ 0) :
    0 < grade A v :=
  Nat.pos_of_ne_zero fun h => ((grade_eq_zero_iff A v).1 h).elim hv (· inferInstance)

section FiniteGrade

variable [FiniteDimensional K (fullSubspace A v)]

private theorem exists_pow_apply_mem : {m | (A ^ m) v ∈ subspace A v m}.Nonempty :=
  (finiteDimensional_fullSubspace_iff A v).1 ‹_›

/-- The grade is the least `m` with `A^m v ∈ 𝒦_m` (the definition used by [saad2003iterative],
§6.2). -/
theorem grade_eq_sInf : grade A v = sInf {m | (A ^ m) v ∈ subspace A v m} := by
  set n := sInf {m | (A ^ m) v ∈ subspace A v m} with hn
  have hmem : (A ^ n) v ∈ subspace A v n := Nat.sInf_mem (exists_pow_apply_mem A v)
  have hli : LinearIndependent K (fun i : Fin n => (A ^ (i : ℕ)) v) :=
    (linearIndependent_iff_forall_pow_notMem A v).2 fun k hk =>
      Nat.notMem_of_lt_sInf (hn ▸ hk)
  rw [grade, fullSubspace_eq_of_pow_apply_mem A v hmem, subspace]
  simpa using finrank_span_eq_card hli

/-- At the grade the Krylov sequence closes up: `A^grade v ∈ 𝒦_grade`. -/
theorem pow_grade_apply_mem : (A ^ grade A v) v ∈ subspace A v (grade A v) := by
  rw [grade_eq_sInf]
  exact Nat.sInf_mem (exists_pow_apply_mem A v)

/-- The grade is the exact point at which the Krylov sequence stops growing: `grade ≤ m` iff `A^m v`
has already fallen into `𝒦_m`. The working form of `grade_eq_sInf`. -/
theorem grade_le_iff {m : ℕ} : grade A v ≤ m ↔ (A ^ m) v ∈ subspace A v m :=
  ⟨fun h => pow_apply_mem_subspace_of_le A v (pow_grade_apply_mem A v) h, fun h => by
    rw [grade_eq_sInf]; exact Nat.sInf_le h⟩

/-- Below the grade the Krylov sequence still grows: `A^m v ∉ 𝒦_m` for `m < grade`. -/
theorem pow_apply_notMem_subspace_of_lt_grade {m : ℕ} (h : m < grade A v) :
    (A ^ m) v ∉ subspace A v m := fun hm => absurd ((grade_le_iff A v).2 hm) (not_le.2 h)

/-- [saad2003iterative], Prop 6.1: `𝒦_m = 𝒦_grade` for `m ≥ grade`. -/
theorem subspace_eq_of_grade_le {m : ℕ} (h : grade A v ≤ m) :
    subspace A v m = subspace A v (grade A v) :=
  subspace_eq_of_pow_apply_mem A v (pow_grade_apply_mem A v) h

/-- `grade` steps already exhaust the cyclic subspace: `𝒦_grade = 𝒦_∞`. -/
theorem subspace_grade_eq_fullSubspace : subspace A v (grade A v) = fullSubspace A v :=
  (fullSubspace_eq_of_pow_apply_mem A v (pow_grade_apply_mem A v)).symm

/-- `𝒦_grade` is `A`-invariant: the invariant subspace a Krylov method has built by the time it
terminates. -/
theorem subspace_grade_mem_invtSubmodule :
    subspace A v (grade A v) ∈ Module.End.invtSubmodule A :=
  mem_invtSubmodule_of_subspace_succ_eq A v
    ((subspace_succ_eq_iff A v _).2 (pow_grade_apply_mem A v))

/-- The Krylov vectors `v, A v, …, A^(m-1) v` are linearly independent for `m ≤ grade`. -/
theorem linearIndependent_of_le_grade {m : ℕ} (h : m ≤ grade A v) :
    LinearIndependent K (fun i : Fin m => (A ^ (i : ℕ)) v) :=
  (linearIndependent_iff_forall_pow_notMem A v).2 fun _ hk =>
    pow_apply_notMem_subspace_of_lt_grade A v (hk.trans_le h)

/-- [saad2003iterative], Prop 6.2: `dim 𝒦_m = min m (grade)`. -/
theorem finrank_subspace (m : ℕ) : Module.finrank K (subspace A v m) = min m (grade A v) := by
  rcases le_total m (grade A v) with h | h
  · rw [min_eq_left h, subspace]
    simpa using finrank_span_eq_card (linearIndependent_of_le_grade A v h)
  · rw [min_eq_right h, subspace_eq_of_grade_le A v h, subspace]
    simpa using finrank_span_eq_card (linearIndependent_of_le_grade A v le_rfl)

/-- A vector of finite grade has a nonzero minimal polynomial: the monic annihilator of degree
`grade A v` supplied by `pow_apply_mem_subspace_iff_exists_monic` is a nonzero member of the
annihilator ideal. -/
theorem minpolyVec_ne_zero : minpolyVec A v ≠ 0 := by
  obtain ⟨p, hp, -, hpv⟩ :=
    (pow_apply_mem_subspace_iff_exists_monic A v (grade A v)).1 (pow_grade_apply_mem A v)
  intro h
  exact hp.ne_zero (Ideal.mem_bot.1 (((minpolyVec_eq_zero_iff A v).1 h) ▸ hpv))

/-- [saad2003iterative], §6.2: the grade of `v` is the degree of its minimal polynomial. -/
theorem natDegree_minpolyVec : (minpolyVec A v).natDegree = grade A v := by
  refine le_antisymm ?_ ?_
  · obtain ⟨p, hp, hpd, hpv⟩ :=
      (pow_apply_mem_subspace_iff_exists_monic A v (grade A v)).1 (pow_grade_apply_mem A v)
    exact hpd ▸ natDegree_le_of_dvd ((minpolyVec_dvd_iff A v).2 hpv) hp.ne_zero
  · exact (grade_le_iff A v).2 ((pow_apply_mem_subspace_iff_exists_monic A v _).2
      ⟨minpolyVec A v, minpolyVec_monic A v (minpolyVec_ne_zero A v), rfl, aeval_minpolyVec A v⟩)

/-- Below the grade each step enlarges the Krylov subspace strictly. -/
theorem subspace_strictMono_of_le_grade {m : ℕ} (h : m + 1 ≤ grade A v) :
    subspace A v m < subspace A v (m + 1) :=
  lt_of_le_of_ne (subspace_mono A v m.le_succ) fun he =>
    pow_apply_notMem_subspace_of_lt_grade A v (Nat.lt_of_succ_le h)
      ((subspace_succ_eq_iff A v m).1 he.symm)

end FiniteGrade

/-! ### Three-term recurrences span Krylov subspaces -/

/-- **A three-term recurrence spans the Krylov subspaces.** If `u_0` is a nonzero multiple of `w`
and `B u_a = c₁_a u_{a−1} + c₂_a u_a + c₃_{a+1} u_{a+1}` (with `u_{−1} = 0`) with `c₃_{a+1} ≠ 0`
for `a + 1 < k`, then `span {u_0, …, u_{j−1}} = 𝒦_j(B, w)` for every `j ≤ k`. This is how the
vectors of a Lanczos-type process (symmetric or two-sided, with any normalization) are identified
with a Krylov basis without appeal to orthogonality. -/
theorem span_eq_subspace_of_threeTerm (B : Module.End K V) (u : ℕ → V) (w : V) (k : ℕ) (c : K)
    (c₁ c₂ c₃ : ℕ → K) (h0 : 0 < k → u 0 = c • w ∧ c ≠ 0)
    (hrel : ∀ a, a + 1 < k → B (u a) =
      c₁ a • (if a = 0 then 0 else u (a - 1)) + c₂ a • u a + c₃ (a + 1) • u (a + 1))
    (hne : ∀ a < k, c₃ a ≠ 0) :
    ∀ j ≤ k, Submodule.span K (Set.range fun i : Fin j => u i) = subspace B w j := by
  set U : ℕ → Submodule K V := fun j => Submodule.span K (Set.range fun i : Fin j => u i)
  have hmemU : ∀ {i j : ℕ}, i < j → u i ∈ U j :=
    fun {i j} h => Submodule.subset_span ⟨⟨i, h⟩, rfl⟩
  have hUmono : ∀ {a b : ℕ}, a ≤ b → U a ≤ U b := fun {a b} hab =>
    Submodule.span_le.2 (by rintro _ ⟨l, rfl⟩; exact hmemU (by omega))
  -- each `u_i` lies in `𝒦_{i+1}`
  have hle : ∀ i < k, u i ∈ subspace B w (i + 1) := by
    intro i
    induction i using Nat.strong_induction_on with
    | _ i ih =>
      intro hi
      rcases i with _ | i
      · rw [(h0 hi).1]
        exact Submodule.smul_mem _ _ (self_mem_subspace B w (Nat.succ_pos 0))
      · have hui : u (i + 1) = (c₃ (i + 1))⁻¹ •
            (B (u i) - c₁ i • (if i = 0 then 0 else u (i - 1)) - c₂ i • u i) := by
          rw [hrel i (by omega), (by intro x y z; abel : ∀ x y z : V, x + y + z - x - y = z),
            smul_smul, inv_mul_cancel₀ (hne (i + 1) hi), one_smul]
        rw [hui]
        have hKi := ih i (by omega) (by omega)
        refine Submodule.smul_mem _ _ (Submodule.sub_mem _ (Submodule.sub_mem _ ?_ ?_) ?_)
        · exact map_subspace_le B w (i + 1) ⟨_, hKi, rfl⟩
        · refine Submodule.smul_mem _ _ ?_
          split_ifs with h
          · exact Submodule.zero_mem _
          · exact subspace_mono B w (by omega) (ih (i - 1) (by omega) (by omega))
        · exact Submodule.smul_mem _ _ (subspace_mono B w (by omega) hKi)
  -- `B` maps `U (i+1)` into `U (i+2)` below `k`
  have hmap : ∀ i, i + 1 < k → ∀ x ∈ U (i + 1), B x ∈ U (i + 2) := by
    intro i hi x hx
    refine Submodule.span_induction (fun y hy => ?_) (by simp) (fun y z _ _ hy hz => by
      rw [map_add]; exact Submodule.add_mem _ hy hz) (fun a y _ hy => by
      rw [map_smul]; exact Submodule.smul_mem _ a hy) hx
    obtain ⟨l, rfl⟩ := hy
    rw [hrel l (by omega)]
    refine Submodule.add_mem _ (Submodule.add_mem _ (Submodule.smul_mem _ _ ?_)
      (Submodule.smul_mem _ _ (hmemU (by omega)))) (Submodule.smul_mem _ _ (hmemU (by omega)))
    split_ifs with h
    · exact Submodule.zero_mem _
    · exact hmemU (by omega)
  have hge : ∀ i < k, (B ^ i) w ∈ U (i + 1) := by
    intro i
    induction i with
    | zero =>
      intro hk
      obtain ⟨hu0, hc0⟩ := h0 hk
      have : w = c⁻¹ • u 0 := by rw [hu0, smul_smul, inv_mul_cancel₀ hc0, one_smul]
      rw [pow_zero, Module.End.one_apply, this]
      exact Submodule.smul_mem _ _ (hmemU (by omega))
    | succ i ih =>
      intro hi
      rw [pow_succ', Module.End.mul_apply]
      exact hmap i hi _ (ih (by omega))
  intro j hj
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact subspace_mono B w (by omega) (hle i (by omega))
  · rw [subspace, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact hUmono (by omega) (hge i (by omega))

end Field

end Krylov
