import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.Algebra.Polynomial.Module.AEval
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Eigenspace.Minpoly
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.RingTheory.EuclideanDomain
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Krylov subspaces

`Krylov.subspace A v m = span {v, A v, …, A^(m-1) v}` for an endomorphism `A` of a module over a
commutative ring, the full Krylov space, the polynomial description `𝒦_m = {p(A) v | deg p < m}`,
and — over a field — the grade of `v` together with its minimal polynomial, the monic generator of
the annihilator ideal `{p | p(A) v = 0}` ([saad2003iterative] §6.2, Prop 6.1–6.2;
[saad2011numerical] Prop 6.1–6.3; [choi2006iterative] Def 2.1; [meurant2006lanczos] §2.1).

## Notation

`𝒦[A, v] m` is `Krylov.subspace A v m`, the `m`-th Krylov subspace of `A` at `v`. The notation is
scoped to the `Krylov` namespace.

## Implementation notes

`Krylov.annIdealVec` and `Krylov.minpolyVec` are, declaration for declaration, the module-element
analogue of Mathlib's `Polynomial.annIdeal` and `Polynomial.annIdealGenerator`: the same monic
generator of the same kind of ideal, with the same proofs. They are stated afresh because Mathlib's
are the annihilator of an *algebra element* `a : A` under `Polynomial.aeval a`, whereas what a
Krylov method annihilates is a *vector*, `p ↦ p(A) v`. The two would be one if Mathlib's pair were
generalized to the `𝕜[X]`-module `Module.AEval' A`, where `Krylov.annIdealVec A v` is the
annihilator of the cyclic submodule generated by `v`.
-/

open Polynomial

namespace Krylov

section CommRing

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The `m`-th Krylov subspace `𝒦_m(A, v) = span {v, A v, …, A^(m-1) v}`. -/
def subspace (A : Module.End R M) (v : M) (m : ℕ) : Submodule R M :=
  Submodule.span R (Set.range fun i : Fin m => (A ^ (i : ℕ)) v)

/-- Notation `𝒦[A, v] m` for `Krylov.subspace A v m`. -/
scoped notation "𝒦[" A ", " v "] " m:max => Krylov.subspace A v m

/-- The full Krylov space `span {A^i v | i : ℕ}`, the smallest `A`-invariant subspace containing
`v`. -/
def fullSubspace (A : Module.End R M) (v : M) : Submodule R M :=
  Submodule.span R (Set.range fun i : ℕ => (A ^ i) v)

/-- The evaluation map `p ↦ p(A) v`. -/
noncomputable def polyEval (A : Module.End R M) (v : M) : R[X] →ₗ[R] M where
  toFun p := aeval A p v
  map_add' p q := by simp [map_add]
  map_smul' c p := by simp

/-- `Krylov.polyEval` is evaluation of the polynomial at `A`, applied to `v`. -/
@[simp]
theorem polyEval_apply (A : Module.End R M) (v : M) (p : R[X]) :
    polyEval A v p = aeval A p v := rfl

variable (A : Module.End R M) (v : M)

instance (m : ℕ) : Module.Finite R (subspace A v m) :=
  Module.Finite.span_of_finite R (Set.finite_range _)

/-- No steps span nothing: `𝒦_0 = ⊥`. -/
@[simp]
theorem subspace_zero : subspace A v 0 = ⊥ := by
  simp [subspace]

/-- One step spans the starting direction: `𝒦_1 = R ∙ v`. -/
theorem subspace_one : subspace A v 1 = R ∙ v := by
  simp [subspace, Set.range_unique]

/-- The generators of `𝒦_m`: `A^i v` lies in it for every `i < m`. -/
theorem pow_apply_mem_subspace {i m : ℕ} (h : i < m) : (A ^ i) v ∈ subspace A v m :=
  Submodule.subset_span ⟨⟨i, h⟩, rfl⟩

/-- The starting vector lies in every nontrivial Krylov subspace. -/
theorem self_mem_subspace {m : ℕ} (h : 0 < m) : v ∈ subspace A v m := by
  simpa using pow_apply_mem_subspace A v h

/-- The generating set of `𝒦_m` written as an image of `Set.Iio m`; the form in which it matches
Mathlib's Gram–Schmidt spans. -/
theorem subspace_eq_span_image_Iio (m : ℕ) :
    subspace A v m = Submodule.span R ((fun i : ℕ => (A ^ i) v) '' Set.Iio m) := by
  rw [subspace]
  congr 1
  ext x
  simp only [Set.mem_range, Set.mem_image, Set.mem_Iio, Fin.exists_iff]
  tauto

/-- The Krylov subspaces grow with the number of steps: `𝒦_m ≤ 𝒦_n` for `m ≤ n`. -/
theorem subspace_mono : Monotone (subspace A v) := by
  intro m n h
  simp only [subspace_eq_span_image_Iio]
  exact Submodule.span_mono (Set.image_mono (Set.Iio_subset_Iio h))

/-- Every Krylov subspace sits inside the full Krylov space. -/
theorem subspace_le_fullSubspace (m : ℕ) : subspace A v m ≤ fullSubspace A v :=
  Submodule.span_mono <| by rintro _ ⟨i, rfl⟩; exact ⟨(i : ℕ), rfl⟩

/-- The full Krylov space is the supremum of the finite ones: `𝒦_∞ = ⨆ m, 𝒦_m`. -/
theorem iSup_subspace : ⨆ m, subspace A v m = fullSubspace A v := by
  refine le_antisymm (iSup_le fun m => subspace_le_fullSubspace A v m) ?_
  rw [fullSubspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  exact le_iSup (subspace A v) (i + 1) (pow_apply_mem_subspace A v i.lt_succ_self)

/-- One application of `A` costs one step: `A 𝒦_m ≤ 𝒦_{m+1}`. -/
theorem map_subspace_le (m : ℕ) : (subspace A v m).map A ≤ subspace A v (m + 1) := by
  rw [subspace, Submodule.map_span, Submodule.span_le]
  rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
  have h : A ((A ^ (i : ℕ)) v) = (A ^ ((i : ℕ) + 1)) v := by rw [pow_succ']; rfl
  rw [SetLike.mem_coe, h]
  exact pow_apply_mem_subspace A v (Nat.succ_lt_succ i.2)

/-- `A^k` maps `𝒦_m` into `𝒦_{m+k}`. -/
theorem pow_apply_mem_subspace_of_mem {x : M} {m : ℕ} (hx : x ∈ subspace A v m) (k : ℕ) :
    (A ^ k) x ∈ subspace A v (m + k) := by
  induction k with
  | zero => simpa using hx
  | succ k ih =>
    have h : (A ^ (k + 1)) x = A ((A ^ k) x) := by rw [pow_succ']; rfl
    rw [h, ← Nat.add_assoc]
    exact map_subspace_le A v (m + k) ⟨_, ih, rfl⟩

/-- The full Krylov space is `A`-invariant; since it also contains `v`, it is the smallest
`A`-invariant subspace that does. -/
theorem fullSubspace_mem_invtSubmodule : fullSubspace A v ∈ Module.End.invtSubmodule A := by
  rw [Module.End.mem_invtSubmodule_iff_map_le, fullSubspace, Submodule.map_span, Submodule.span_le]
  rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
  refine Submodule.subset_span ⟨i + 1, ?_⟩
  change (A ^ (i + 1)) v = A ((A ^ i) v)
  rw [pow_succ']
  rfl

/-- The full Krylov space of the zero vector is trivial. -/
@[simp]
theorem fullSubspace_zero : fullSubspace A (0 : M) = ⊥ := by
  rw [fullSubspace, Submodule.span_eq_bot]
  rintro _ ⟨i, rfl⟩
  simp

/-- [saad2003iterative], §6.2: `𝒦_m = {p(A) v | deg p < m}`, "the subspace of all vectors which can
be written as `x = p(A) v` with `p` of degree not exceeding `m - 1`". -/
theorem subspace_eq_map_degreeLT (m : ℕ) :
    subspace A v m = (degreeLT R m).map (polyEval A v) := by
  refine le_antisymm ?_ ?_
  · rw [subspace, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    refine ⟨X ^ (i : ℕ), ?_, by simp⟩
    rw [X_pow_eq_monomial]
    exact monomial_coe_mem_degreeLT i 1
  · rintro _ ⟨p, hp, rfl⟩
    rw [SetLike.mem_coe, mem_degreeLT] at hp
    rcases eq_or_ne p 0 with rfl | hp0
    · simp
    rw [polyEval_apply, aeval_eq_sum_range' ((natDegree_lt_iff_degree_lt hp0).2 hp) A,
      LinearMap.sum_apply]
    refine Submodule.sum_mem _ fun i hi => ?_
    rw [LinearMap.smul_apply]
    exact Submodule.smul_mem _ _ (pow_apply_mem_subspace A v (Finset.mem_range.1 hi))

/-- The polynomial description of `𝒦_m` element by element: `x` lies in it exactly when `x = p(A) v`
for some polynomial `p` of degree `< m`. -/
theorem mem_subspace_iff_exists_aeval {x : M} {m : ℕ} :
    x ∈ subspace A v m ↔ ∃ p : R[X], p.degree < m ∧ aeval A p v = x := by
  rw [subspace_eq_map_degreeLT]
  constructor
  · rintro ⟨p, hp, rfl⟩
    exact ⟨p, mem_degreeLT.1 hp, rfl⟩
  · rintro ⟨p, hp, rfl⟩
    exact ⟨p, mem_degreeLT.2 hp, rfl⟩

/-- Every polynomial of degree `< m` in `A`, applied to `v`, lands in `𝒦_m`. This is the direction
of the polynomial description that the Krylov methods use. -/
theorem aeval_apply_mem_subspace {p : R[X]} {m : ℕ} (hp : p.degree < m) :
    aeval A p v ∈ subspace A v m :=
  (mem_subspace_iff_exists_aeval A v).2 ⟨p, hp, rfl⟩

/-- `𝒦_{m+1} = 𝒦_m` iff `A^m v ∈ 𝒦_m` iff `𝒦_m` is `A`-invariant (for `m ≥ 1` or `v = 0`). -/
theorem subspace_succ_eq_iff (m : ℕ) :
    subspace A v (m + 1) = subspace A v m ↔ (A ^ m) v ∈ subspace A v m := by
  constructor
  · intro h
    rw [← h]
    exact pow_apply_mem_subspace A v m.lt_succ_self
  · intro h
    refine le_antisymm ?_ (subspace_mono A v m.le_succ)
    rw [subspace, Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    rcases lt_or_eq_of_le (Nat.lt_succ_iff.1 i.2) with hi | hi
    · exact pow_apply_mem_subspace A v hi
    · rw [SetLike.mem_coe]
      change (A ^ (i : ℕ)) v ∈ subspace A v m
      rw [hi]
      exact h

/-- A Krylov subspace that no longer grows is `A`-invariant. -/
theorem mem_invtSubmodule_of_subspace_succ_eq {m : ℕ}
    (h : subspace A v (m + 1) = subspace A v m) :
    subspace A v m ∈ Module.End.invtSubmodule A :=
  (Module.End.mem_invtSubmodule_iff_map_le A).2 (h ▸ map_subspace_le A v m)

/-- Once the Krylov sequence closes up at step `n` it stays closed. -/
theorem pow_apply_mem_subspace_of_le {n : ℕ} (h : (A ^ n) v ∈ subspace A v n) {m : ℕ}
    (hm : n ≤ m) : (A ^ m) v ∈ subspace A v m := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hm
  have hk := pow_apply_mem_subspace_of_mem A v h k
  have hpow : (A ^ k) ((A ^ n) v) = (A ^ (n + k)) v := by
    rw [← Module.End.mul_apply, ← pow_add, Nat.add_comm]
  rwa [hpow] at hk

/-- [saad2003iterative], Prop 6.1: the Krylov subspaces are constant from the first closure onwards.
-/
theorem subspace_eq_of_pow_apply_mem {n : ℕ} (h : (A ^ n) v ∈ subspace A v n) {m : ℕ}
    (hm : n ≤ m) : subspace A v m = subspace A v n := by
  induction m, hm using Nat.le_induction with
  | base => rfl
  | succ m hm ih =>
    rw [(subspace_succ_eq_iff A v m).2 (pow_apply_mem_subspace_of_le A v h hm), ih]

/-- Once the Krylov sequence closes up at step `n`, that subspace is already everything the sequence
will ever reach: `𝒦_∞ = 𝒦_n`. -/
theorem fullSubspace_eq_of_pow_apply_mem {n : ℕ} (h : (A ^ n) v ∈ subspace A v n) :
    fullSubspace A v = subspace A v n := by
  refine le_antisymm ?_ (subspace_le_fullSubspace A v n)
  rw [fullSubspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  rcases lt_or_ge i n with hi | hi
  · exact pow_apply_mem_subspace A v hi
  · exact subspace_eq_of_pow_apply_mem A v h hi ▸ pow_apply_mem_subspace_of_le A v h hi

/-- Rescaling the starting vector does not enlarge the Krylov subspace. -/
theorem subspace_smul (c : R) (m : ℕ) : subspace A (c • v) m ≤ subspace A v m := by
  rw [subspace, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  simpa using Submodule.smul_mem _ c (pow_apply_mem_subspace A v i.2)

/-- Swapping a composition through one of its factors: `N ((A N)^i v) = (N A)^i (N v)`. -/
theorem pow_comp_apply (B N : Module.End R M) (i : ℕ) (u : M) :
    N (((B ∘ₗ N) ^ i) u) = ((N ∘ₗ B) ^ i) (N u) := by
  induction i with
  | zero => rfl
  | succ i ih =>
    rw [pow_succ', pow_succ', Module.End.mul_apply, Module.End.mul_apply, LinearMap.comp_apply,
      LinearMap.comp_apply, ← ih]

/-- `N` carries the Krylov space of `B N` to the Krylov space of `N B`: `N 𝒦_m(B N, v) = 𝒦_m(N B, N
v)`.  This is the identity behind every "change of variables" in a Krylov method — CGNE's `x = Aᴴ
u`, right preconditioning's `x = M⁻¹ u` — which is why the two variants search the same affine
space. -/
theorem map_subspace_comp (B N : Module.End R M) (u : M) (m : ℕ) :
    (subspace (B ∘ₗ N) u m).map N = subspace (N ∘ₗ B) (N u) m := by
  rw [subspace, subspace, Submodule.map_span]
  congr 1
  ext z
  simp only [Set.mem_image, Set.mem_range]
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, (pow_comp_apply B N i u).symm⟩
  · rintro ⟨i, rfl⟩
    exact ⟨((B ∘ₗ N) ^ (i : ℕ)) u, ⟨i, rfl⟩, pow_comp_apply B N i u⟩

end CommRing

section Field

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]

variable (A : Module.End K V) (v : V)

/-- The grade of `v` w.r.t. `A`: the dimension of the cyclic subspace `𝒦_∞(A, v)` — equivalently the
least `m` with `A^m v ∈ 𝒦_m` (`grade_eq_sInf`) and the degree of the minimal polynomial of `v`
([saad2003iterative], §6.2; Liesen–Strakoš, *Krylov Subspace Methods: Principles and Analysis*).
Junk value `0` when the cyclic subspace is infinite-dimensional (Mathlib's `finrank` convention);
the finite-grade hypothesis is `[FiniteDimensional K (fullSubspace A v)]`, automatic when `V` is
finite-dimensional. -/
noncomputable def grade : ℕ := Module.finrank K (fullSubspace A v)

/-- The Krylov vectors `v, A v, …, A^(m-1) v` are linearly independent exactly when no earlier power
of `A` has already fallen into its own Krylov subspace. -/
theorem linearIndependent_iff_forall_pow_notMem {m : ℕ} :
    LinearIndependent K (fun i : Fin m => (A ^ (i : ℕ)) v) ↔
      ∀ k < m, (A ^ k) v ∉ subspace A v k := by
  induction m with
  | zero => exact iff_of_true linearIndependent_empty_type (by simp)
  | succ m ih =>
    have hinit : Fin.init (fun i : Fin (m + 1) => (A ^ (i : ℕ)) v)
        = fun i : Fin m => (A ^ (i : ℕ)) v := rfl
    rw [linearIndependent_finSucc', hinit, ih]
    constructor
    · rintro ⟨h₁, h₂⟩ k hk
      rcases Nat.lt_succ_iff_lt_or_eq.1 hk with hk' | rfl
      · exact h₁ k hk'
      · exact h₂
    · intro h
      exact ⟨fun k hk => h k (hk.trans m.lt_succ_self), h m m.lt_succ_self⟩

/-- The Krylov sequence stabilizes iff the cyclic subspace is finite-dimensional. -/
theorem finiteDimensional_fullSubspace_iff :
    FiniteDimensional K (fullSubspace A v) ↔ ∃ m, (A ^ m) v ∈ subspace A v m := by
  constructor
  · intro h
    by_contra hc
    have hc' : ∀ m, (A ^ m) v ∉ subspace A v m := fun m hm => hc ⟨m, hm⟩
    set n := Module.finrank K (fullSubspace A v) with hn
    have hli : LinearIndependent K (fun i : Fin (n + 1) => (A ^ (i : ℕ)) v) :=
      (linearIndependent_iff_forall_pow_notMem A v).2 fun k _ => hc' k
    have h₁ : Module.finrank K (subspace A v (n + 1)) = n + 1 := by
      rw [subspace]
      simpa using finrank_span_eq_card hli
    have h₂ : Module.finrank K (subspace A v (n + 1)) ≤ n :=
      hn ▸ Submodule.finrank_mono (subspace_le_fullSubspace A v (n + 1))
    omega
  · rintro ⟨m, hm⟩
    rw [fullSubspace_eq_of_pow_apply_mem A v hm]
    infer_instance

/-- `A^m v ∈ 𝒦_m` iff `v` is annihilated by a monic polynomial of degree `m` ([saad2003iterative],
§6.2 defines the grade through the minimal polynomial of `v`). -/
theorem pow_apply_mem_subspace_iff_exists_monic (m : ℕ) :
    (A ^ m) v ∈ subspace A v m ↔ ∃ p : K[X], p.Monic ∧ p.natDegree = m ∧ aeval A p v = 0 := by
  rw [mem_subspace_iff_exists_aeval]
  constructor
  · rintro ⟨q, hq, hqv⟩
    refine ⟨X ^ m - q, monic_X_pow_sub hq, ?_, by simp [hqv]⟩
    refine natDegree_eq_of_degree_eq_some ?_
    rw [degree_sub_eq_left_of_degree_lt (by rwa [degree_X_pow]), degree_X_pow]
  · rintro ⟨p, hp, hpd, hpv⟩
    refine ⟨X ^ m - p, ?_, by simp [hpv]⟩
    have hdp : p.degree = (m : ℕ) := hpd ▸ degree_eq_natDegree hp.ne_zero
    have hlt := degree_sub_lt_left (p := (X : K[X]) ^ m) (q := p) (by rw [degree_X_pow, hdp])
      (monic_X_pow m).ne_zero (by simp [hp.leadingCoeff])
    rwa [degree_X_pow] at hlt

/-! ### The minimal polynomial of a vector -/

/-- The annihilator ideal of `v`: the polynomials `p` with `p(A) v = 0`.  It is an ideal of `K[X]`
and not merely a `K`-subspace, because it is the annihilator of `v` for the `K[X]`-module structure
that `A` puts on `V` (Mathlib's `Module.AEval'`). -/
def annIdealVec : Ideal K[X] where
  carrier := {p | aeval A p v = 0}
  add_mem' {p q} (hp : aeval A p v = 0) (hq : aeval A q v = 0) := by
    change aeval A (p + q) v = 0
    rw [map_add, LinearMap.add_apply, hp, hq, add_zero]
  zero_mem' := by
    change aeval A (0 : K[X]) v = 0
    rw [map_zero, LinearMap.zero_apply]
  smul_mem' c p (hp : aeval A p v = 0) := by
    change aeval A (c • p) v = 0
    rw [smul_eq_mul, map_mul, Module.End.mul_apply, hp, map_zero]

/-- Membership in the annihilator ideal of `v` is annihilation of `v`. -/
@[simp]
theorem mem_annIdealVec {p : K[X]} : p ∈ annIdealVec A v ↔ aeval A p v = 0 := Iff.rfl

/-- The minimal polynomial of `v` with respect to `A`: the monic generator of the annihilator ideal
`{p | p(A) v = 0}`, and `0` when that ideal is trivial, which happens exactly when the cyclic
subspace `𝒦_∞(A, v)` is infinite-dimensional.  Its degree is the grade of `v`
(`natDegree_minpolyVec`), which is how [saad2003iterative], §6.2 defines the grade. -/
noncomputable def minpolyVec : K[X] :=
  let g := Submodule.IsPrincipal.generator (annIdealVec A v)
  g * C g.leadingCoeff⁻¹

/-- The minimal polynomial of `v` vanishes exactly when nothing but `0` annihilates `v`, that is,
when the cyclic subspace is infinite-dimensional. -/
@[simp]
theorem minpolyVec_eq_zero_iff : minpolyVec A v = 0 ↔ annIdealVec A v = ⊥ := by
  simp only [minpolyVec, mul_eq_zero, Submodule.IsPrincipal.eq_bot_iff_generator_eq_zero,
    C_eq_zero, inv_eq_zero, leadingCoeff_eq_zero, or_self_iff]

/-- `minpolyVec` generates the annihilator ideal. -/
@[simp]
theorem span_singleton_minpolyVec : Ideal.span {minpolyVec A v} = annIdealVec A v := by
  by_cases h : minpolyVec A v = 0
  · rw [h, (minpolyVec_eq_zero_iff A v).1 h, Set.singleton_zero, Ideal.span_zero]
  · rw [minpolyVec, Ideal.span_singleton_mul_right_unit, Ideal.span_singleton_generator]
    exact isUnit_C.2 (IsUnit.mk0 _ (inv_eq_zero.not.2
      (leadingCoeff_eq_zero.not.2 (mul_ne_zero_iff.1 h).1)))

/-- The minimal polynomial of `v` belongs to the annihilator ideal it generates. -/
theorem minpolyVec_mem : minpolyVec A v ∈ annIdealVec A v :=
  Ideal.mul_mem_right _ _ (Submodule.IsPrincipal.generator_mem _)

/-- The minimal polynomial of `v` annihilates `v`. -/
theorem aeval_minpolyVec : aeval A (minpolyVec A v) v = 0 := minpolyVec_mem A v

/-- The defining property of the minimal polynomial of a vector: it divides exactly the polynomials
that annihilate `v`. -/
theorem minpolyVec_dvd_iff {p : K[X]} : minpolyVec A v ∣ p ↔ aeval A p v = 0 := by
  rw [← Ideal.mem_span_singleton, span_singleton_minpolyVec, mem_annIdealVec]

/-- The minimal polynomial of `v` is monic whenever it is nonzero, that is, whenever `v` has finite
grade (`minpolyVec_ne_zero`). -/
theorem minpolyVec_monic (h : minpolyVec A v ≠ 0) : (minpolyVec A v).Monic :=
  monic_mul_leadingCoeff_inv (mul_ne_zero_iff.1 h).1

/-- The grade of a vector never exceeds the dimension of the ambient space, so a Krylov method in
finite dimension terminates in at most `dim V` steps. -/
theorem grade_le_finrank [FiniteDimensional K V] : grade A v ≤ Module.finrank K V :=
  Submodule.finrank_le _

/-- The zero vector has grade `0`. -/
@[simp]
theorem grade_zero : grade A 0 = 0 := by
  rw [grade, fullSubspace_zero, finrank_bot]

/-- The grade vanishes only in the two degenerate cases: `v = 0`, and the junk value taken when the
cyclic subspace is infinite-dimensional. -/
theorem grade_eq_zero_iff :
    grade A v = 0 ↔ v = 0 ∨ ¬FiniteDimensional K (fullSubspace A v) := by
  by_cases h : FiniteDimensional K (fullSubspace A v)
  · simp only [h, not_true_eq_false, or_false, grade, Submodule.finrank_eq_zero]
    constructor
    · intro hb
      have hv : v ∈ fullSubspace A v := Submodule.subset_span ⟨0, by simp⟩
      rw [hb] at hv
      simpa using hv
    · rintro rfl
      exact fullSubspace_zero A
  · simp [h, grade, Module.finrank_of_not_finite h]

section FiniteGrade

variable [FiniteDimensional K (fullSubspace A v)]

private theorem exists_pow_apply_mem : {m | (A ^ m) v ∈ subspace A v m}.Nonempty :=
  (finiteDimensional_fullSubspace_iff A v).1 ‹_›

/-- The grade is the least `m` with `A^m v ∈ 𝒦_m` (the definition used by [saad2003iterative],
§6.2). -/
theorem grade_eq_sInf : grade A v = sInf {m | (A ^ m) v ∈ subspace A v m} := by
  set n := sInf {m | (A ^ m) v ∈ subspace A v m} with hn
  have hmem : (A ^ n) v ∈ subspace A v n := Nat.sInf_mem (exists_pow_apply_mem A v)
  have hli : LinearIndependent K (fun i : Fin n => (A ^ (i : ℕ)) v) :=
    (linearIndependent_iff_forall_pow_notMem A v).2 fun k hk =>
      Nat.notMem_of_lt_sInf (hn ▸ hk)
  rw [grade, fullSubspace_eq_of_pow_apply_mem A v hmem, subspace]
  simpa using finrank_span_eq_card hli

/-- At the grade the Krylov sequence closes up: `A^grade v ∈ 𝒦_grade`. -/
theorem pow_grade_apply_mem : (A ^ grade A v) v ∈ subspace A v (grade A v) := by
  rw [grade_eq_sInf]
  exact Nat.sInf_mem (exists_pow_apply_mem A v)

/-- The grade is the exact point at which the Krylov sequence stops growing: `grade ≤ m` iff `A^m v`
has already fallen into `𝒦_m`. The working form of `grade_eq_sInf`. -/
theorem grade_le_iff {m : ℕ} : grade A v ≤ m ↔ (A ^ m) v ∈ subspace A v m :=
  ⟨fun h => pow_apply_mem_subspace_of_le A v (pow_grade_apply_mem A v) h, fun h => by
    rw [grade_eq_sInf]; exact Nat.sInf_le h⟩

/-- Below the grade the Krylov sequence still grows: `A^m v ∉ 𝒦_m` for `m < grade`. -/
theorem pow_apply_notMem_subspace_of_lt_grade {m : ℕ} (h : m < grade A v) :
    (A ^ m) v ∉ subspace A v m := fun hm => absurd ((grade_le_iff A v).2 hm) (not_le.2 h)

/-- [saad2003iterative], Prop 6.1: `𝒦_m = 𝒦_grade` for `m ≥ grade`. -/
theorem subspace_eq_of_grade_le {m : ℕ} (h : grade A v ≤ m) :
    subspace A v m = subspace A v (grade A v) :=
  subspace_eq_of_pow_apply_mem A v (pow_grade_apply_mem A v) h

/-- `grade` steps already exhaust the cyclic subspace: `𝒦_grade = 𝒦_∞`. -/
theorem subspace_grade_eq_fullSubspace : subspace A v (grade A v) = fullSubspace A v :=
  (fullSubspace_eq_of_pow_apply_mem A v (pow_grade_apply_mem A v)).symm

/-- `𝒦_grade` is `A`-invariant: the invariant subspace a Krylov method has built by the time it
terminates. -/
theorem subspace_grade_mem_invtSubmodule :
    subspace A v (grade A v) ∈ Module.End.invtSubmodule A :=
  mem_invtSubmodule_of_subspace_succ_eq A v
    ((subspace_succ_eq_iff A v _).2 (pow_grade_apply_mem A v))

/-- The Krylov vectors `v, A v, …, A^(m-1) v` are linearly independent for `m ≤ grade`. -/
theorem linearIndependent_of_le_grade {m : ℕ} (h : m ≤ grade A v) :
    LinearIndependent K (fun i : Fin m => (A ^ (i : ℕ)) v) :=
  (linearIndependent_iff_forall_pow_notMem A v).2 fun _ hk =>
    pow_apply_notMem_subspace_of_lt_grade A v (hk.trans_le h)

/-- [saad2003iterative], Prop 6.2: `dim 𝒦_m = min m (grade)`. -/
theorem finrank_subspace (m : ℕ) : Module.finrank K (subspace A v m) = min m (grade A v) := by
  rcases le_total m (grade A v) with h | h
  · rw [min_eq_left h, subspace]
    simpa using finrank_span_eq_card (linearIndependent_of_le_grade A v h)
  · rw [min_eq_right h, subspace_eq_of_grade_le A v h, subspace]
    simpa using finrank_span_eq_card (linearIndependent_of_le_grade A v le_rfl)

/-- A vector of finite grade has a nonzero minimal polynomial: the monic annihilator of degree
`grade A v` supplied by `pow_apply_mem_subspace_iff_exists_monic` is a nonzero member of the
annihilator ideal. -/
theorem minpolyVec_ne_zero : minpolyVec A v ≠ 0 := by
  obtain ⟨p, hp, -, hpv⟩ :=
    (pow_apply_mem_subspace_iff_exists_monic A v (grade A v)).1 (pow_grade_apply_mem A v)
  intro h
  exact hp.ne_zero (Ideal.mem_bot.1 (((minpolyVec_eq_zero_iff A v).1 h) ▸ hpv))

/-- [saad2003iterative], §6.2: the grade of `v` is the degree of its minimal polynomial. -/
theorem natDegree_minpolyVec : (minpolyVec A v).natDegree = grade A v := by
  refine le_antisymm ?_ ?_
  · obtain ⟨p, hp, hpd, hpv⟩ :=
      (pow_apply_mem_subspace_iff_exists_monic A v (grade A v)).1 (pow_grade_apply_mem A v)
    exact hpd ▸ natDegree_le_of_dvd ((minpolyVec_dvd_iff A v).2 hpv) hp.ne_zero
  · exact (grade_le_iff A v).2 ((pow_apply_mem_subspace_iff_exists_monic A v _).2
      ⟨minpolyVec A v, minpolyVec_monic A v (minpolyVec_ne_zero A v), rfl, aeval_minpolyVec A v⟩)

/-- Below the grade each step enlarges the Krylov subspace strictly. -/
theorem subspace_strictMono_of_le_grade {m : ℕ} (h : m + 1 ≤ grade A v) :
    subspace A v m < subspace A v (m + 1) :=
  lt_of_le_of_ne (subspace_mono A v m.le_succ) fun he =>
    pow_apply_notMem_subspace_of_lt_grade A v (Nat.lt_of_succ_le h)
      ((subspace_succ_eq_iff A v m).1 he.symm)

end FiniteGrade

end Field

end Krylov
