namespace = "QuarteroniSaccoSaleri.Chapter06"

[[node]]
id = "definition_6_1"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 6.1'

[[node]]
id = "definition_6_1_of_convergesWithOrder"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 6.1'

[[node]]
id = "definition_6_1_iff"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Definition 6.1'

[[node]]
id = "definition_6_1_convergenceFactor"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, remark following Definition 6.1'
