namespace = "QuarteroniSaccoSaleri.Chapter06"

[[node]]
id = "equation_6_33"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.33)'

[[node]]
id = "equation_6_33_eq"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.33)'

[[node]]
id = "equation_6_34"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.34)'

[[node]]
id = "equation_6_36"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.36)'

[[node]]
id = "equation_6_36_eq"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.36)'

[[node]]
id = "equation_6_37"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.37)'

[[node]]
id = "equation_6_38"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.38)'

[[node]]
id = "equation_6_38_fixedPoints"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 6.6.1'

[[node]]
id = "property_6_7_one"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Property 6.7'

[[node]]
id = "property_6_7_higher"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Property 6.7'

[[node]]
id = "steffensen"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Exercise 6.5'

[[node]]
id = "exercise_6_5"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Exercise 6.5'

[[node]]
id = "property_6_7_multiple"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Property 6.7'

[[node]]
id = "equation_6_40"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.40)'

[[node]]
id = "equation_6_40_eq"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.40)'

[[node]]
id = "equation_6_40_eq_div"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.40)'

[[node]]
id = "equation_6_40_tendsto"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, Section 6.6.2'

[[node]]
id = "equation_6_39"
source = 'Quarteroni–Sacco–Saleri, Numerical Mathematics, equation (6.39)'
