namespace = "SaadSparse.Ch04"

[[node]]
id = "D"

[[node]]
id = "E"

[[node]]
id = "F"

[[node]]
id = "G_ssor"

[[node]]
id = "M_sor"

[[node]]
id = "M_ssor"

[[node]]
id = "Splitting"

[[node]]
id = "Splitting.step"

[[node]]
id = "affineStep"

[[node]]
id = "backwardGsStep"

[[node]]
id = "backwardSorStep"

[[node]]
id = "f_ssor"

[[node]]
id = "gsStep"

[[node]]
id = "jacobiStep"

[[node]]
id = "sorStep"

[[node]]
id = "ssorStep"

[[node]]
id = "symmetricGsStep"
