[[node]]
id = "ContinuousLinearEquiv.condNumber_eq"

[[node]]
id = "NormedRing.condNumber"

[[node]]
id = "NormedRing.condNumber_smul"

[[node]]
id = "NormedRing.one_le_condNumber"

[[node]]
id = "ContinuousLinearEquiv.condNumber"
source = "Atkinson–Han, Theoretical Numerical Analysis, (2.4.1)"

[[node]]
id = "ContinuousLinearEquiv.one_le_condNumber"
source = "Atkinson–Han, Theoretical Numerical Analysis, §2.4.2"
