namespace = "SaadSparse.Ch06"

[[node]]
id = "Rtilde"

[[node]]
id = "equation_6_62"

[[node]]
id = "equation_6_65"

[[node]]
id = "equation_6_70"

[[node]]
id = "equation_6_71"

[[node]]
id = "equation_6_75"

[[node]]
id = "gtilde"

[[node]]
id = "problem_6_14"

[[node]]
id = "ytilde"

[[node]]
id = "ξ"

[[node]]
id = "ρF"

[[node]]
id = "ρFmin"

[[node]]
id = "ρG"

[[node]]
id = "ρG_succ"
