namespace = 'ConvexAnalysis'

[[node]]
id = 'recessionFn_convexConj'

[[node]]
id = 'recessionFn_eq_supportFn_convexDom_convexConj'

[[node]]
id = 'constancySpace_convexConj'

[[node]]
id = 'recessionConeFn_convexConj'

[[node]]
id = 'recessionConeFn_convexConj_hull'

[[node]]
id = 'recessionConeFn_eq_polarCone_convexDom_convexConj'

[[node]]
id = 'polarCone_recessionConeFn'

[[node]]
id = 'zero_mem_interior_iff_polarCone_eq_zero'

[[node]]
id = 'isBounded_setOf_le_iff_zero_mem_interior_convexDom_convexConj'
