namespace = "FloatingPoint"

[[node]]
id = "RoundsLU"

[[node]]
id = "exists_roundsLU_mul_eq_add"

[[node]]
id = "exists_roundsLU_solve_eq"

[[node]]
id = "abs_le_of_roundsLU_of_entrywiseNonneg"

[[node]]
id = "linfty_opNorm_le_of_roundsLU_solve"

[[node]]
id = "RoundsCholesky"

[[node]]
id = "exists_roundsCholesky_eq_add"

[[node]]
id = "RoundsThomas"

[[node]]
id = "exists_roundsThomas_mul_eq_add"

[[node]]
id = "exists_roundsThomas_mul_eq_add_of_diag_pos"

[[node]]
id = "RoundsLU.isLU_mul"

[[node]]
id = "RoundsLU.abs_mul_sub_apply_le"

[[node]]
id = "three_mul_gamma_add_sq_le"

[[node]]
id = "abs_add_mul_add_mul_add_mul_entrywiseLE"

[[node]]
id = "abs_entrywiseLE_of_abs_mul_eq"

[[node]]
id = "gamma_div_one_sub_gamma"

[[node]]
id = "gamma_lt_one"

[[node]]
id = "_root_.Matrix.supAbs_le_linfty_opNorm"

[[node]]
id = "RoundsCholesky.abs_transpose_mul_sub_apply_le_of_le"

[[node]]
id = "lowerBidiagonalOf"

[[node]]
id = "upperBidiagonalOf"

[[node]]
id = "thomasLower_eq"

[[node]]
id = "thomasUpper_eq"

[[node]]
id = "lowerBidiagonalOf_mul_apply"

[[node]]
id = "RoundsThomas.abs_alpha_add_mul_sub_le"

[[node]]
id = "RoundsThomas.abs_beta_mul_alpha_sub_le"

[[node]]
id = "abs_lowerBidiagonalOf_mul_upperBidiagonalOf"
