namespace = "FloatingPoint"

[[node]]
id = "exists_rounds_sub_dot_div_eq"

[[node]]
id = "RoundsForwardSubst"

[[node]]
id = "RoundsBackSubst"

[[node]]
id = "exists_roundsForwardSubst_eq"

[[node]]
id = "exists_roundsBackSubst_eq"

[[node]]
id = "abs_sub_le_of_roundsBackSubst_of_abs_le_diag"

[[node]]
id = "abs_sub_le_of_roundsBackSubst_of_isDiagDominant"

[[node]]
id = "abs_one_add_mul_one_add_sub_one_le_gamma"

[[node]]
id = "abs_one_add_div_one_add_sub_one_le_gamma"

[[node]]
id = "exists_roundsSumFrom_map_eq"

[[node]]
id = "exists_roundsForwardSubst_row_eq"

[[node]]
id = "roundsBackSubst_iff_roundsForwardSubst_toDual"

[[node]]
id = "abs_sub_le_of_mulVec_eq_of_abs_le"

[[node]]
id = "abs_sub_apply_le_of_mulVec_eq_of_abs_le"
