namespace = "Matrix"

[[node]]
id = "differenceJacobian"
source = "Quarteroni–Sacco–Saleri, Numerical Mathematics, Equation 7.9"

[[node]]
id = "differenceJacobian_apply"

[[node]]
id = "toEuclideanCLM_differenceJacobian_single"

[[node]]
id = "norm_differenceJacobian_col_sub_le"
source = "Quarteroni–Sacco–Saleri, Numerical Mathematics, Property 7.1"

[[node]]
id = "opNorm_toEuclideanCLM_differenceJacobian_sub_le"
source = "Quarteroni–Sacco–Saleri, Numerical Mathematics, Property 7.1"
