namespace = "Matrix"

[[node]]
id = "rankOneSecantUpdate"

[[node]]
id = "broydenUpdate_eq_rankOneSecantUpdate"

[[node]]
id = "rankOneSecantUpdate_mulVec"

[[node]]
id = "sr1Update"

[[node]]
id = "sr1Update_eq"

[[node]]
id = "sr1Update_isSymm"

[[node]]
id = "sr1Update_mulVec"

[[node]]
id = "sr1Update_inv"

[[node]]
id = "symmetrizationStep"

[[node]]
id = "generalSymmetricUpdate"

[[node]]
id = "generalSymmetricUpdate_isSymm"

[[node]]
id = "generalSymmetricUpdate_mulVec"

[[node]]
id = "psbUpdate"

[[node]]
id = "psbUpdate_eq"

[[node]]
id = "psbUpdate_isSymm"

[[node]]
id = "psbUpdate_mulVec"

[[node]]
id = "symmetrizationStep_add_of_isSymm"

[[node]]
id = "symmetrizationStep_of_isSymm"

[[node]]
id = "symmetrizationStep_sub_generalSymmetricUpdate_key"

[[node]]
id = "symmetrizationStep_iterate_succ"

[[node]]
id = "tendsto_symmetrizationStep_iterate"

[[node]]
id = "frobenius_norm_sq_sub_mul_mul_add_sq"

[[node]]
id = "frobenius_norm_sub_mul_mul_le"

[[node]]
id = "psbUpdate_sub_eq_of_isSymm"

[[node]]
id = "frobenius_norm_psbUpdate_sub_le"

[[node]]
id = "frobenius_norm_psbUpdate_sub_lt"

[[node]]
id = "frobenius_norm_psbUpdate_sub_le_add"

[[node]]
id = "dotProduct_mulVec_comm_of_isSymm"

[[node]]
id = "bfgsUpdate"

[[node]]
id = "bfgsUpdate_mulVec"

[[node]]
id = "bfgsUpdate_isSymm"

[[node]]
id = "bfgsUpdate_posDef"

[[node]]
id = "dfpUpdate"

[[node]]
id = "dfpUpdate_mulVec"

[[node]]
id = "dfpUpdate_isSymm"

[[node]]
id = "dfpUpdate_posDef"
