[[node]]
id = "InnerProductSpace.toDualReal"

[[node]]
id = "EuclideanSpace.div"

[[node]]
id = "EuclideanSpace.div_smul_fun"

[[node]]
id = "EuclideanSpace.div_const_smul_single"

[[node]]
id = "EuclideanSpace.div_comp_continuousLinearEquiv"

[[node]]
id = "EuclideanSpace.div_comp_affineIsometryEquiv"

[[node]]
id = "EuclideanSpace.div_gradient_eq_laplacian"

[[node]]
id = "contDiffOnClosure_one_iff"

[[node]]
id = "ContDiffOnClosure.smul"

[[node]]
id = "ContDiffOnClosure.mul"

[[node]]
id = "ContDiffOnClosure.smul_const"

[[node]]
id = "ContDiffOnClosure.exists_continuousOn_fderiv_fderiv"

[[node]]
id = "ContDiffOnClosure.toDual_symm_of_eqOn_fderiv"

[[node]]
id = "BoundaryData"

[[node]]
id = "BoundaryData.memLp_ν_apply_mul"

[[node]]
id = "BoundaryData.integral_div_eq_of_contDiff"

[[node]]
id = "BoundaryData.integral_fderiv_mul_add_eq"

[[node]]
id = "BoundaryData.integral_laplacian_mul_add_eq"

[[node]]
id = "BoundaryData.integral_laplacian_mul_add_eq_of_continuousOn_fderiv"

[[node]]
id = "Elliptic.laplaceForm_toLowerOrderL_eq_integral"

[[node]]
id = "Elliptic.neg_weakLaplacian_add_ae_eq_of_forall_laplaceForm_eq"

[[node]]
id = "BoundaryData.TraceFamily"

[[node]]
id = "BoundaryData.TraceFamily.traceL_eq_zero_of_mem_zero"

[[node]]
id = "BoundaryData.TraceFamily.normalTrace"

[[node]]
id = "BoundaryData.TraceFamily.memLp_normalTrace"

[[node]]
id = "BoundaryData.TraceFamily.green_laplacian"

[[node]]
id = "BoundaryData.TraceFamily.normalTrace_eq_zero_of_forall_laplaceForm_eq"

[[node]]
id = "EuclideanSpace.epigraph"

[[node]]
id = "EuclideanSpace.isBoundaryGraphAt_iff"

[[node]]
id = "EuclideanSpace.isOpen_epigraph"

[[node]]
id = "EuclideanSpace.closure_epigraph"

[[node]]
id = "EuclideanSpace.closure_inter_subset_of_inter_eq"

[[node]]
id = "EuclideanSpace.frontier_epigraph"

[[node]]
id = "IsBoundaryGraphAt.frontier_inter_ball"

[[node]]
id = "AffineIsometryEquiv.measurePreserving"

[[node]]
id = "AffineIsometryEquiv.hasFDerivAt"

[[node]]
id = "AffineIsometryEquiv.setIntegral_comp"
