[[node]]
id = "SobolevEuclidean.HasSmoothDensity"

[[node]]
id = "SobolevEuclidean.HasUniformSmoothDensity"

[[node]]
id = "SobolevEuclidean.smoothRestrictions"

[[node]]
id = "SobolevEuclidean.mem_smoothRestrictions"

[[node]]
id = "SobolevEuclidean.exists_contDiff_of_mem_smoothRestrictions"

[[node]]
id = "SobolevEuclidean.HasSmoothDensity.dense_smoothRestrictions"

[[node]]
id = "SobolevEuclidean.HasSmoothDensity.exists_seq_contDiff_one"

[[node]]
id = "SobolevEuclidean.eqOn_closure_of_ae_eq_of_continuousOn"

[[node]]
id = "IsSobolevExtensionDomain.hasSmoothDensity"

[[node]]
id = "IsContDiffChartDomain.hasSmoothDensity"

[[node]]
id = "IsContDiffDomain.hasSmoothDensity"

[[node]]
id = "EuclideanSpace.hasSmoothDensity_openTriangleOpens"

[[node]]
id = "HasSegmentProperty"

[[node]]
id = "Convex.hasSegmentProperty"

[[node]]
id = "IsBoundaryOfClass.hasSegmentProperty"

[[node]]
id = "IsContDiffDomain.hasSegmentProperty"

[[node]]
id = "IsLipschitzDomain.hasSegmentProperty"

[[node]]
id = "TestFunction.compSubRightOfPreimage"

[[node]]
id = "LocallyIntegrableOn.comp_add_right_of_preimage"

[[node]]
id = "measurePreserving_add_right_restrict_of_preimage"

[[node]]
id = "MeasureTheory.MemLp.comp_add_right_of_preimage"

[[node]]
id = "integral_smul_comp_add_right_of_preimage"

[[node]]
id = "HasWeakIteratedLineDerivOn.comp_add_right_of_preimage"

[[node]]
id = "SobolevEuclidean.hasWeakIteratedLineDerivOn_fn_single"

[[node]]
id = "SobolevEuclidean.memSobolevMultiIndex_one_of_forall"

[[node]]
id = "SobolevEuclidean.weakDeriv_single_ae_eq"

[[node]]
id = "SobolevEuclidean.exists_translatePiece"

[[node]]
id = "MemSobolev.exists_contDiff_hasCompactSupport_sobolevNorm_sub_lt"

[[node]]
id = "SobolevEuclidean.norm_le_sum_norm_translateCurve_sub"

[[node]]
id = "fderiv_add_sum_eq_zero_of_partition"

[[node]]
id = "HasSegmentProperty.exists_translateApprox"

[[node]]
id = "HasSegmentProperty.exists_hasCompactSupport_norm_restrictL_sub_lt"

[[node]]
id = "HasSegmentProperty.exists_contDiff_hasCompactSupport_norm_sub_lt"

[[node]]
id = "HasSegmentProperty.exists_seq_contDiff_hasCompactSupport_tendsto"

[[node]]
id = "HasSegmentProperty.hasSmoothDensity"

[[node]]
id = "HasSegmentProperty.hasUniformSmoothDensity"

[[node]]
id = "Convex.hasSmoothDensity"

[[node]]
id = "Convex.hasUniformSmoothDensity"

[[node]]
id = "EuclideanSpace.hasUniformSmoothDensity_openTriangleOpens"

[[node]]
id = "IsContDiffDomain.hasUniformSmoothDensity"

[[node]]
id = "IsLipschitzDomain.hasSmoothDensity"

[[node]]
id = "IsLipschitzDomain.hasUniformSmoothDensity"
