[[node]]
id = "EuclideanSpace.perp"

[[node]]
id = "EuclideanSpace.inner_perp_map"

[[node]]
id = "EuclideanSpace.linearIndependent_pair_iff_inner_perp_ne_zero"

[[node]]
id = "EuclideanSpace.openTriangle_rotate"

[[node]]
id = "EuclideanSpace.eq_of_affine_eq"

[[node]]
id = "EuclideanSpace.eq_edge_of_mem_openSegment_of_mem_segment"

[[node]]
id = "EuclideanSpace.segment_subset_frontier_openTriangle"

[[node]]
id = "EuclideanSpace.vertex_injective"

[[node]]
id = "EuclideanSpace.edgeMeasure"

[[node]]
id = "EuclideanSpace.edgeMeasure_symm"

[[node]]
id = "EuclideanSpace.integral_edgeMeasure"

[[node]]
id = "EuclideanSpace.edgeNormal"

[[node]]
id = "EuclideanSpace.integral_inner_edgeNormal_of_neg"

[[node]]
id = "EuclideanSpace.inner_symm_edgeNormal"

[[node]]
id = "EuclideanSpace.integral_inner_edgeNormal_affine"

[[node]]
id = "EuclideanSpace.exists_ball_inter_subset_openTriangle"

[[node]]
id = "EuclideanSpace.openTriangle_inter_nonempty_of_same_side"

[[node]]
id = "EuclideanSpace.triangleBoundaryMeasure"

[[node]]
id = "EuclideanSpace.integral_inner_triangleNormal"

[[node]]
id = "EuclideanSpace.integral_referenceTriangle_eq"

[[node]]
id = "EuclideanSpace.integral_fderiv_snd"

[[node]]
id = "EuclideanSpace.integral_div_referenceTriangle"

[[node]]
id = "EuclideanSpace.integral_div_referenceTriangle_eq_integral_inner"

[[node]]
id = "EuclideanSpace.integral_div_openTriangle"

[[node]]
id = "EuclideanSpace.triangleBoundaryData"

[[node]]
id = "Triangulation.IsBoundaryEdge"

[[node]]
id = "Triangulation.not_isBoundaryEdge_iff_exists_partner"

[[node]]
id = "Triangulation.IsPartner.inner_perp_mul_neg"

[[node]]
id = "Triangulation.partner_unique"

[[node]]
id = "Triangulation.IsPartner.edgeMeasure_eq"

[[node]]
id = "Triangulation.IsPartner.edgeNormal_eq"

[[node]]
id = "Triangulation.exists_eq_vertex_of_mem_closedK"

[[node]]
id = "Triangulation.segment_subset_frontier_of_isBoundaryEdge"

[[node]]
id = "Triangulation.openSegment_disjoint_of_isBoundaryEdge"

[[node]]
id = "Triangulation.boundaryMeasure"

[[node]]
id = "Triangulation.boundaryMeasure_pos_of_isOpen"

[[node]]
id = "Triangulation.outwardNormal"

[[node]]
id = "Triangulation.outwardNormal_eq_edgeNormal"

[[node]]
id = "Triangulation.sum_edgeTerm_interior_eq_zero"

[[node]]
id = "Triangulation.integral_div_eq"

[[node]]
id = "Triangulation.boundaryData"

[[node]]
id = "Triangulation.InteriorEdgesSubset"

[[node]]
id = "Triangulation.mem_vertices_or_exists_isBoundaryEdge_of_mem_frontier"

[[node]]
id = "EuclideanSpace.edgeMeasure_le_triangleBoundaryMeasure"

[[node]]
id = "EuclideanSpace.triangleNormal_eq_of_mem_openSegment_rot"

[[node]]
id = "EuclideanSpace.segment_subset_closedTriangle_rot"

[[node]]
id = "EuclideanSpace.integral_mul_triangleNormal_apply"

[[node]]
id = "Triangulation.ae_boundaryMeasure_iff"

[[node]]
id = "Triangulation.edgeMeasure_le_boundaryMeasure"

[[node]]
id = "Triangulation.setIntegral_eq_sum_K"

[[node]]
id = "Triangulation.integrableOn_mul_of_memLp_of_continuousOn"
